- hosts: checkers
  tasks:
  - name: sync catalog
    synchronize: src="../checkers" dest="{{cs_dir}}"

  - name: checkers owner
    file:
      path: "{{cs_dir}}/checkers"
      owner: "{{cs_user}}"
      group: "{{cs_user}}"
      recurse: yes

  - name: install docker deps
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common
    tags: docker

  - name: install docker repo key
    apt_key: url=https://download.docker.com/linux/debian/gpg
    tags: docker

  - name: add docker repo
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
      filename: docker
    tags: docker

  - name: install docker
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    tags: docker

  - name: add cs_user to docker
    user: name="{{cs_user}}" groups=docker append=yes
    tags: docker

  - name: install .net repo key
    apt_key: url=https://packages.microsoft.com/keys/microsoft.asc
    tags: net

  - name: add .net repo
    apt_repository:
      repo: deb [arch=amd64] https://packages.microsoft.com/debian/9/prod stretch main
      filename: microsoft
    tags: net

  - name: install .net sdk
    apt: name=dotnet-sdk-2.2
    tags: net

  - name: install sys deps
    apt:
      name:
        - python3-pip

  - name: python deps
    pip:
      executable: pip3
      name:
        - requests
        - lxml
        - elasticsearch
        - pika

  - name: build binder
    command: ./build.sh
    args:
      chdir: "{{cs_dir}}/checkers/Binder"
    become: yes
    become_user: "{{cs_user}}"
    tags: binder

  - name: binder tmp dir
    file: path="{{cs_dir}}/checkers/Binder/checker/tmp" state=directory owner="{{cs_user}}" group="{{cs_user}}"
    tags: binder

  - name: build rubik
    command: dotnet build -c Release
    args:
      chdir: "{{cs_dir}}/checkers/rubik/src"
    become: yes
    become_user: "{{cs_user}}"
    tags: rubik
