- hosts: cloud_master
  pre_tasks:
   - name: 'Apt update'
     raw: apt update
     changed_when: False
   - name: 'Install python2'
     raw: apt -y install python-simplejson
     changed_when: False
  roles:
    - cloud_master
