version: '2.0'
services:
  updater:
    build: .
    ports:
     - "0.0.0.0:3255:3255"
    volumes:
      - ./site:/var/www/html/
      - ./updater:/var/www/updater
      - ./transport_http:/var/www/transport_http
      - ./transport_http2:/var/www/transport_http2
    restart: unless-stopped
    mem_limit: 2000m
  apache:
    image: php:apache
    ports:
      - "0.0.0.0:8000:80"
    volumes:
      - ./site:/var/www/html/
    environment:
      - LOG_STDOUT=1
      - ALLOW_OVERRIDE=None
    mem_limit: 2000m
