- hostname:
    name: router

- name: install packages
  apt: 
    update_cache: yes
    name:
      - ifupdown
      - isc-dhcp-server

- name: remove packages
  apt:
    name:
      - netplan.io
    state: absent

- name: copy interfaces
  copy: src=interfaces dest=/etc/network/interfaces

- name: copy dhcpd config
  copy: src=dhcpd.conf dest=/etc/dhcp/dhcpd.conf
  notify: enable and restart dhcpd

- name: install packages
  apt: name={{item}} state=latest
  with_items:
    - fping
    - python3-requests
    - conntrack

- name: create users
  user: name={{item}} shell=/bin/false
  with_items:
    - networkclosed
    - antidos
    - connectmon

- name: create cloud user
  user: name=cloud shell=/bin/bash

- name: create control dirs in /root
  file: path=/root/{{item}} state=directory
  with_items:
    - antidos
    - openclosenetwork
    - snat
    - trafdump
    - cloud
    
# create connectmon symlink
#- name: create connectmon symlink
#  file: path=/home/connectmon state=link

- name: copy sudo_cloud
  copy: src=cloud/sudo_cloud dest=/etc/sudoers.d/ mode=0640

- name: copy sudo_cloud scripts
  copy: src=cloud/{{item}} dest=/root/cloud/{{item}} mode=0755
  with_items:
    - isolate_network.sh
    - open_network.sh

- name: copy networkclosed systemd service
  copy: src=networkclosed/networkclosed.service dest=/etc/systemd/system/networkclosed.service
  notify: enable and restart networkclosed

- name: copy networkclosed service
  copy: 
    src: networkclosed/networkclosed_serv.py
    dest: /home/networkclosed/networkclosed_serv.py
    owner: networkclosed
    group: networkclosed
    mode: 0755
  notify: enable and restart networkclosed

- name: copy connectmon systemd service
  copy: src=connectmon/connectmon.service dest=/etc/systemd/system/connectmon.service
  notify: enable and restart connectmon

- name: copy connectmon service
  copy: 
    src: connectmon/connectmon.py
    dest: /home/connectmon/connectmon.py
    owner: connectmon
    group: connectmon
    mode: 0755
  notify: enable and restart connectmon

- name: copy open-close network scripts
  copy: src=networkclosed/{{item}} dest=/root/openclosenetwork/{{item}} mode=0755
  with_items:
    - open_network.sh
    - close_network.sh
    - check_network.sh

- name: copy antidos systemd service
  copy: src=antidos/antidos.service dest=/etc/systemd/system/antidos.service
  notify: enable and restart antidos

- name: copy antidos service
  copy: 
    src: antidos/antidos_serv.py
    dest: /home/antidos/antidos_serv.py
    owner: antidos
    group: antidos
    mode: 0755
  notify: enable and restart antidos

- name: copy antidos root scripts
  copy: src=antidos/{{item}} dest=/root/antidos/{{item}} mode=0755
  with_items:
    - block_team.sh
    - unblock_team.sh
    - list_blocked_teams.sh

- name: copy snat root scripts
  copy: src=snat/{{item}} dest=/root/snat/{{item}} mode=0755
  with_items:
    - add_snat_rules.sh
    - del_snat_rules.sh
    - check_snat_rules.sh

- name: copy trafdump root scripts
  copy: src=trafdump/{{item}} dest=/root/trafdump/{{item}} mode=0755
  with_items:
    - add_trafdump_rules.sh
    - del_trafdump_rules.sh
    - check_trafdump_rules.sh
