[package]
name = "hashsum"
version = "0.1.0"
authors = ["Alexander Bersenev <bay@hackerdom.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.8"
hex = "0.3"