# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_info.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='user_info.proto',
  package='handy',
  syntax='proto3',
  serialized_options=_b('Z\004data'),
  serialized_pb=_b('\n\x0fuser_info.proto\x12\x05handy\"R\n\x08UserInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x15\n\rpassword_hash\x18\x03 \x01(\t\x12\x11\n\tis_master\x18\x04 \x01(\x08\"4\n\rLocalUserInfo\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x11\n\tis_master\x18\x02 \x01(\x08\"B\n\x0fProfileUserInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x11\n\tis_master\x18\x03 \x01(\x08\x42\x06Z\x04\x64\x61tab\x06proto3')
)




_USERINFO = _descriptor.Descriptor(
  name='UserInfo',
  full_name='handy.UserInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='handy.UserInfo.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='username', full_name='handy.UserInfo.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password_hash', full_name='handy.UserInfo.password_hash', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_master', full_name='handy.UserInfo.is_master', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=108,
)


_LOCALUSERINFO = _descriptor.Descriptor(
  name='LocalUserInfo',
  full_name='handy.LocalUserInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='handy.LocalUserInfo.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_master', full_name='handy.LocalUserInfo.is_master', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=162,
)


_PROFILEUSERINFO = _descriptor.Descriptor(
  name='ProfileUserInfo',
  full_name='handy.ProfileUserInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='handy.ProfileUserInfo.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='username', full_name='handy.ProfileUserInfo.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_master', full_name='handy.ProfileUserInfo.is_master', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=230,
)

DESCRIPTOR.message_types_by_name['UserInfo'] = _USERINFO
DESCRIPTOR.message_types_by_name['LocalUserInfo'] = _LOCALUSERINFO
DESCRIPTOR.message_types_by_name['ProfileUserInfo'] = _PROFILEUSERINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserInfo = _reflection.GeneratedProtocolMessageType('UserInfo', (_message.Message,), {
  'DESCRIPTOR' : _USERINFO,
  '__module__' : 'user_info_pb2'
  # @@protoc_insertion_point(class_scope:handy.UserInfo)
  })
_sym_db.RegisterMessage(UserInfo)

LocalUserInfo = _reflection.GeneratedProtocolMessageType('LocalUserInfo', (_message.Message,), {
  'DESCRIPTOR' : _LOCALUSERINFO,
  '__module__' : 'user_info_pb2'
  # @@protoc_insertion_point(class_scope:handy.LocalUserInfo)
  })
_sym_db.RegisterMessage(LocalUserInfo)

ProfileUserInfo = _reflection.GeneratedProtocolMessageType('ProfileUserInfo', (_message.Message,), {
  'DESCRIPTOR' : _PROFILEUSERINFO,
  '__module__' : 'user_info_pb2'
  # @@protoc_insertion_point(class_scope:handy.ProfileUserInfo)
  })
_sym_db.RegisterMessage(ProfileUserInfo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
