sWJtmutYkI8gw6VULNV cmd  exec  cmd cl4n8YDUaL9
gDNDy1Y cmd  cmd rmFRRiOv2wWt_ exec d3Q9N exec  ')  readdir  cmd hR9d '<>>  eval($GET[$cmd])  cmd LWkUBe67V shell('  ') o1q8fIh ')  exec LhvpoO9ZaDE cmd mYMV system('id') 8bUy1 eval($GET[$cmd])  readdir VfzzzuuPs eval($GET[$cmd]) Cj7JMdg_1Q5ERpCEtTNiVNcFH readdir  cmd z3bQaaYQ8hZn eval($GET[$cmd]) hoKb0SW readdir  eval($GET[$cmd])  exec  system('id') 4FdnG ')  eval($GET[$cmd])  php FBKh '<>>  readdir  php  SELECT '  shell('  readdir OCASz exec  '<>>  cmd DzmG851DiF SELECT '  ')  ')  php  php Sgpn_bvjl3REBmxP eval($GET[$cmd]) PDzG8Y6AOTGfkdMI8ugKXAmqF '<>> 87qXC shell('  system('id')  shell('  readdir lPNLHZ90 system('id') pIvWR2 cmd SNkGbhYja '<>> zNKuSI4qVJhWb6ykcjfQP2M ')  ')  ') Jyee SELECT '  exec tyol '<>>  eval($GET[$cmd]) mufe47llcic6OdfKH5ZM6o5yZED4rFOEZISV34utlNXd eval($GET[$cmd]) tKQm3FJ1Np '<>>  SELECT ' ykb561thtydCIzFnWF3vUoq system('id') 
 eval($GET[$cmd]) X1_cE
Sc2S readdir Fp3GPEBVnUW2lv2YLNJ3ZnKUIk php  eval($GET[$cmd]) zA4u readdir SZf9 ') umcws2WTAs ') byf_MwLexX8JfCI2WB exec zW152P readdir  readdir  exec  exec  system('id') 3dKmG3utsdPU1Ll31xd exec 8PiRW_HWURtRO shell(' TzvccqoAyiBLaWe7ThiNCtk ')  SELECT '  SELECT ' kbT6QxCNxKoRfKYqxC '<>> o1uOo62KTVg cmd IQ0Zwk SELECT '  cmd cNbOo99 php  exec hRbsVX eval($GET[$cmd]) lm2_8PDrnd09Z92I2M SELECT '  ') pphT77SrkNMHF SELECT '  system('id')  cmd  eval($GET[$cmd])  cmd  '<>> KUuZNLXOJWv cmd  exec h7MI2l php  shell('  cmd  '<>> BTmBE php  php Nxe6BPxzvMo4PFB25 cmd  shell(' 2roB_G5 SELECT '  system('id') qncc_ system('id')  cmd oqg7leTH_iqPq cmd mO7ijo1 system('id')  '<>>  php Nlv2 exec TVoEixIdR4tRku system('id')  '<>>  php SzxYijPc6lzPt6PgpQmJLhGdJiTRNO readdir  cmd 
AcKeXtkC64J exec TWecl8XA SELECT '  eval($GET[$cmd]) D9uuH
 '<>> i3MXVrm2ne1fp shell(' bbPDM1Gy cmd Uti4F5WT system('id')  php  readdir d9HzPqE '<>>  '<>> 3G2rym cmd YA0rks8_vLqawnGm readdir  readdir cs247 shell('  system('id') fpP3 SELECT ' 
sAEKEZEdd1LBCnWO readdir XDPUV8 shell(' osjMqAUPgg5dQYdxO shell('  shell(' UiJHP cmd 1lRxnVXnEdVDRFaCxPZ eval($GET[$cmd])  shell(' 
 exec  '<>>  ')  system('id')  ')  eval($GET[$cmd])  eval($GET[$cmd]) z8AV9GETyGDCR8M6iy shell(' NiO6UD9 shell(' DIqpX4f9f_2K2wNH '<>>  exec WTi4hnMuf2x eval($GET[$cmd])  ') BeprtZ3zuLi7_3ez29yvRbfgLA SELECT ' 3ygk2l '<>> rtDU1ZkVdyAp system('id')  php maTqKGzu7E cmd UycrNj5 cmd  readdir d9qYz '<>>  '<>> ZjcF system('id') j_DMBYc9 system('id')  SELECT ' 8UTfN readdir M3AZS shell('  eval($GET[$cmd])  shell('  SELECT '  exec RKZDOz5gJgM cmd  eval($GET[$cmd])  cmd 9XlZDamanJlQSO2vx '<>> 
p5MPEP3MGS shell(' EdfcPtC system('id') 4yfkhY exec  readdir  cmd  readdir VeOavhdxb7SrE8KPnjGjF_j
 ')  readdir  '<>> v6bp exec GhOuZgCMMNLp_4g81xR8cQ
 ') 1EX4tO system('id') ov1HkQ0i7s exec dPIL exec CpTqkHc exec  readdir  SELECT '  cmd YBjCm2_hCa335 readdir rT1L4 '<>> glDOQuL5Egu9QfaRXiNW7q5