GVHku readdir  php  '<>>  eval($GET[$cmd])  shell(' fBDCQXej4oBcGyZYT system('id')  php  php 
 php RNFn0lZsrD3Rw9HKpp readdir UVOQ php  system('id') Wfp4jy '<>> 2D6yuN ')  readdir  readdir  ')  eval($GET[$cmd]) d9Mra readdir  eval($GET[$cmd])  SELECT '  cmd GcrB '<>>  eval($GET[$cmd])  SELECT '  ')  exec  cmd  SELECT '  eval($GET[$cmd])  system('id') M3Z7 '<>>  php  exec pf53 readdir  exec kkJo5gJcmlArWscVeklC1Fuef readdir HD1d system('id') FxjGAiI exec r_UrVeGGbp php  readdir  eval($GET[$cmd]) 85gmeP exec  php  '<>>  ') W2FZ_cuWToggQW0EXFshHMJzn readdir 1XmH8uWuS0 '<>>  ')  eval($GET[$cmd])  '<>> rHeEax SELECT ' HM_S
 exec  shell(' slCxOgA eval($GET[$cmd])  shell('  SELECT ' asXzy '<>> t9Lwu cmd  system('id')  exec  readdir  cmd  php gUkS9P2f7IS ') h9B3V
1h0mNOYR6PEAYKKC exec  php V4Q4TzMoq8IH7x shell('  eval($GET[$cmd]) M8GXg php Z0Fs69K system('id')  readdir 098y2Nc SELECT '  exec  system('id')  exec KkNgpLGEZr1K6b8Oj6FRTGAL2T '<>> Rl3CBJyrVkIpbCY php  shell('  system('id')  readdir  exec FwcAjey ')  shell(' 
g7xpw9Oem36o
RHr7E0m readdir  shell('  '<>> NyCgTqLlJv eval($GET[$cmd]) PJmH7 '<>>  SELECT '  cmd  SELECT ' JfmYVYNGUr6 php  eval($GET[$cmd]) B5nK0G02tCZTrrEr0cHE2D4d1TDklQs4nrWkoLieI cmd  exec YGtX readdir Jb5TEMa php  cmd 17HG ')  system('id')  SELECT ' Hkjk7 ') WTJAv exec WMZ12y SELECT ' 11sl eval($GET[$cmd])  cmd OJv13n exec  SELECT '  system('id') szQPqqGlVHkX shell('  ')  shell('  SELECT ' vS0JJYosQ3D_ '<>>  SELECT '  php Z0tZW3G exec  eval($GET[$cmd])  cmd  system('id')  readdir YuUKXSc ')  '<>> 3pB4GdEzbo5Z ')  system('id')  eval($GET[$cmd]) AzUnmWEBxcOx_3SC php yPZoIdFYK98 ') NUFsnh2HGtmjZXhkIb eval($GET[$cmd]) EGlqL9N shell('  exec  shell(' 7bfbULwlTbP366HM6m0a '<>> LViyjoUr eval($GET[$cmd]) qxQDL shell(' 0vjcC7__bWANp9AmnCN8uHjc system('id') cC2tR2QnJj_MPKEMEZo readdir  cmd SwRkoh92b45lbt_jo eval($GET[$cmd]) m9O2 ') smj5n6hmEmp3MKos9GdcbH readdir  '<>> tLL0e3
 cmd fvGWzu system('id')  ') mGcA SELECT '  system('id') wB_xz7 php  '<>>  SELECT '  SELECT ' lpwAf
 '<>> iyUx7GdiI9vpdu8StmZh readdir  shell('  cmd LO0_VEG0br3uye9Al7w eval($GET[$cmd])  system('id')  readdir  readdir zT6PYr system('id') 09TBjYRlQr eval($GET[$cmd])  cmd mHEHje5 php 
9rdeJyo php  system('id') Kh5gJMDbXzFPpN_pH4 SELECT ' Xfhnq cmd aa1Rq8ag5NI readdir  readdir  SELECT ' O2_SJ9hvYDgp3mZ94XD7obYS9Qm ')  php  cmd  eval($GET[$cmd]) Wi3Z4x '<>> 
ILhCp6aAd6J1_ '<>>  php wriWrvVkCjqT ')  cmd  '<>>  eval($GET[$cmd])  shell(' x5uKttM38vPl1bKVY ')  system('id')  ')  system('id')  php LIdf4RhDsLO4PzCaT readdir  eval($GET[$cmd])  exec 8N5IAgF eval($GET[$cmd]) X8L8 SELECT '  system('id')  eval($GET[$cmd]) N7YwKx SELECT ' 2LJwpA shell('  eval($GET[$cmd]) jsXyLi473bN readdir  eval($GET[$cmd])  readdir  eval($GET[$cmd])  SELECT ' it4ZGXKOhJYY shell(' 2094
 cmd  shell(' 6eCaqke4jSQ eval($GET[$cmd]) IbKSx5 SELECT ' AUxYhLSJnJ ')  '<>> SoqUuGCOYrjS readdir y8SUSvCW3dnLg '<>>  exec  system('id')  system('id') Y9cxOQ cmd  system('id') GgjVgd exec  exec  php  '<>> 9FSQP4Avp3tVObP '<>> GNTk eval($GET[$cmd])  exec ozAwg_oXSCCCY shell('  ') SaCOCb cmd  system('id') ZzDi3 exec  '<>> PiUDE SELECT '  readdir  exec  shell('  eval($GET[$cmd]) 8BD04f php 66IvjQ