 ') XQboLQT cmd X7b0k7Z6sxmXqr eval($GET[$cmd])  readdir  readdir  shell('  cmd  system('id') 02mZpTT3 '<>>  shell('  '<>> EzYOrNUYUH9V
dqFqlADvaHc system('id') Nd5C system('id') Zzq2KWy eval($GET[$cmd]) 4zUft shell(' qkPKAzm ') 7OT2V eval($GET[$cmd]) y4cMlwawYo system('id') jkpRQ1 eval($GET[$cmd])  ')  php lQYe shell('  ') 
 ') wlLzFRPFun4pHY1v eval($GET[$cmd])  eval($GET[$cmd]) lM6RIce7XuPjZUYnrcVdx exec h73poogSGbTXNaActzUASh cmd BVLEllyDL_KT7izFf '<>>  shell(' PHjlD php AQp8WskZWNAAnyd cmd  SELECT '  '<>> bHJpSbjqNI9 '<>> QqCll system('id') V0oSWWf0ETnlHvHCHHEUO system('id')  php 5gc96VvfYjy ')  eval($GET[$cmd]) 4k5O
0wfXiCpMR55ZRO readdir wd_7v9bVlhNV6 shell(' zRv6xwzU5V_aZU php zD5yi7n exec yWWfF SELECT '  '<>>  exec r2P2W php  readdir SKRqbYzCtra cmd CwJVvTIHKRbP6sjDOY_p eval($GET[$cmd])  php  readdir _NFnpqH0yGn cmd  system('id')  eval($GET[$cmd])  eval($GET[$cmd]) R9IlD ') jW0u cmd  eval($GET[$cmd])  shell('  php  system('id') DLl7 system('id') 0Hab8n readdir d3CNjRgYtHOsmUut '<>> dHBgtOo23Dv system('id') bAVFfpNfD6fDW0lxvhvnBGvG SELECT '  readdir 
 shell('  SELECT ' ZMHW7lO cmd  readdir  SELECT '  shell(' 2cqSC '<>>  cmd Dt3jQgdhCYJ4AK5gnlPW4AKLXF3smH
oX4EQ0Y4bPoU6bWsi eval($GET[$cmd]) LB0IBi3 SELECT ' f9PE7d php IdQ8_KXfX5 '<>>  cmd _AO1R8cmPbJyqni4 ')  readdir  exec JheL readdir DTMT4FA4tNeZRU eval($GET[$cmd])  eval($GET[$cmd]) WA89lcsE1nfd1 php  exec  system('id') 
z5vwh_UzGj0JT1H php  '<>> DS56yVj0YUZasHKW8LRBwcAJvwpVCDswaq27cKJcYt readdir  shell('  '<>>  ') g_kP eval($GET[$cmd])  exec  '<>> 
uvH4nbh shell('  system('id')  eval($GET[$cmd])  php  system('id') 5mTDD cmd tqlNbb7 php  exec dYo6IhRt readdir PDVJ9ugmagq '<>>  eval($GET[$cmd]) in84yVWSqf0F6 readdir 2b1yfoR_d7Bf php  ')  ') uemTfK eval($GET[$cmd]) iydaSq SELECT ' 6O44O830bbA4B8LWMyx cmd kFNggrFWYw2S4vDZUYwHrvWxp cmd my85uBI shell(' MR0P8 eval($GET[$cmd])  exec  '<>> n8NsPmvPMVJ ') hLD4_t9 system('id') xz3i5x7 cmd  cmd B9Ky eval($GET[$cmd])  eval($GET[$cmd])  eval($GET[$cmd])  exec ewVzic23cTXa8SUB9CmczqxpiG1r7N_WpglPEao_EEFZDjca ') uXMeNp5 eval($GET[$cmd]) tl8a php  ')  readdir QcZtXqAlwEGRHzZP98E exec qH5a7nr3 php  eval($GET[$cmd])  readdir 
sh17fe SELECT '  system('id')  eval($GET[$cmd])  '<>>  exec  eval($GET[$cmd]) QwyZ7tz '<>>  SELECT '  cmd 6NIeS5u68oemFtZdsJ eval($GET[$cmd])  '<>> RsylNxm ') Trr9vrml6tQt system('id') CEz6W2_jBWc39YE1pD2 '<>> jh_tuQiPNF8
 '<>>  system('id')  system('id')  '<>>  readdir  '<>> SsD4sBIiJGcs eval($GET[$cmd]) IrVFUuXP2_e7QsMwwq1Yb5z5 exec  system('id') lGCMb3m0g '<>> Az5Ec SELECT '  '<>> uUvF
 ') xE2oHlj SELECT '  exec  cmd RzGeNA SELECT ' 