ofSix SELECT '  readdir  '<>>  exec PD5rpk shell('  SELECT ' p15C8iv exec X5NbW6umPaCssMCJaYToQk9coqO5VBF2zXC
Q5I_oEV exec  shell('  eval($GET[$cmd])  system('id')  '<>>  SELECT '  ')  shell('  SELECT '  shell('  system('id') labL7E_0C system('id')  cmd 
xZCU '<>> 
HKhG8ATNyNXWzD shell(' jvsxHMb php eUVTpUSXET
 php 4C4AIAPZA system('id') gS4MJjxpgejT readdir klEhiN php  system('id')  eval($GET[$cmd]) SFKvadtcx72JN ') lN2c8T8vrSAWH
 system('id')  readdir GiNFoTdk_LY shell(' 8JnNCun shell(' kfrw8vujIepmoO5qE system('id') mbbecBRQgI87F1esWWJwKnl shell('  eval($GET[$cmd]) wbL3HrrGkai readdir 3VLDqU ') 7lf9ONEnSzB8SnCNOdX81f5obeSJCJ8d3w3 exec  readdir  readdir XmAY5dQ shell(' m5wjyOEj2eW system('id') paiD
 system('id') eS9_cG53xauX cmd  php  '<>> 2NVl eval($GET[$cmd]) _hJkt readdir  system('id')  SELECT '  exec 35A3hRKmfw shell(' Pxhgj readdir mLersrLjBjY '<>> GkTpMZuNbS_AleOLJrjRzsK ')  cmd  shell('  eval($GET[$cmd]) nqRf3 readdir  cmd  readdir dhgfjb php g9bZYB2TAu system('id')  readdir  '<>> NICO5xG shell(' q1mQeZ exec UGQngz3AIXWd1NSOhv1hCBFnj0Lc ')  '<>>  eval($GET[$cmd]) 6XEr ')  readdir  php wd6Bm7LeKRi9tnROm shell(' YYAareX shell(' FiuDI1T system('id') l0Fa system('id')  exec  eval($GET[$cmd])  php YH2LN9tSTS5ll1 cmd  cmd 2N6gx cmd cuHPXNsl4fyCcbtU readdir  SELECT '  php bBIT exec rNGT php  exec h58Lhr7hY SELECT ' h46EnH eval($GET[$cmd]) 
k22_ eval($GET[$cmd]) pPMr system('id') _U7g317Cr '<>> 
 '<>> dqry8Y
 '<>> v1XrtkD exec NmfO php  cmd  ')  cmd  php l_WpY6YOmQLBT2TT5Hv cmd vhLk8Uo2IPMu0Em_u SELECT ' jg6Pu php CAIug4wvZfBZ shell('  shell('  system('id') xNbhn eval($GET[$cmd])  readdir  eval($GET[$cmd])  exec  cmd  php  SELECT '  cmd zXL_u9ncN system('id') 1M7FD9 system('id')  shell('  readdir  exec hLxRwo eval($GET[$cmd]) 7fKkz9 exec w_38 exec  eval($GET[$cmd])  '<>> teXVPzmpNlvHPT5ZAPb exec  exec  eval($GET[$cmd]) wHfZoYPo6KJcKQgqXbpvt6CQX93Ifh php n4W3eyz ') jhow ') XOwhy SELECT ' xVwYRHeKjT9AwtPYQgG ') 