 ')  shell(' TtcT0NQ4WYrdRr5v9UjdgHtGa0gy8Mn2 SELECT '  php 
 cmd LuWeszXzgHQLo48w95kxGl4J_ system('id') 44jV cmd  readdir  eval($GET[$cmd]) 3FLwKsF858OxHrhmX '<>>  ') ehotVq
ihB8 readdir  ') W1XVKjX ') vr5X exec  ')  exec  exec  '<>> _BNUVRlPGpccQfeqva4ZhyzD8L0 '<>>  ')  SELECT '  php qKIu5Z eval($GET[$cmd]) RDSKLIOOMdA7Ya
 '<>>  SELECT ' LdV8H eval($GET[$cmd]) 38SyFF ') N32ZGN '<>> iA3Q cmd  readdir  cmd  '<>>  ')  eval($GET[$cmd])  readdir  shell(' 
7J6i_Ly system('id')  ') FUxHcNS0sn8QVUColIqs_fXLpZrAhD eval($GET[$cmd])  readdir eHZPjNuN1cGw cmd wZxmXrKer6keq3OST1v shell(' tuTr95wYLqvJBnkp1JFh96UrKIgjF4 '<>> nh9qa ')  cmd  eval($GET[$cmd])  cmd 2Wstoa shell('  exec FwtcAg ') kikqJQ3oQjRw72vhm6 ') TcJRO2 system('id') BKE6jy4IYBSxe29VxMG shell(' uPoOPJFusPse4ZkIZ22 SELECT '  exec SThA9J8NlJPX8YoDbC readdir  SELECT ' P3oJ '<>> cTOnnJi SELECT '  '<>> jqEs system('id') ElpZsMOo '<>>  SELECT ' xp5bQK3mdAXS shell('  cmd  eval($GET[$cmd]) yvuPdqr30MyfzU2 '<>> XqWc6 shell('  shell('  exec 0iY9 shell('  eval($GET[$cmd])  exec 5Qzrq ')  '<>> 
 system('id') gFklfou6_WUgHySVuS readdir  '<>> m_ga
 SELECT '  readdir VBrK7gxCrgSqDfQJW cmd  shell(' IHKlG5iRVL1m1hrcEhcc6cMqW cmd 
HDLsPa eval($GET[$cmd])  exec aab2rKlcrmHg readdir  shell(' p2__8 '<>>  readdir  ')  php  SELECT ' BB5cpJekhxIuj8 eval($GET[$cmd]) NMFx
dANpApq eval($GET[$cmd]) 
8sSYL php IZrLgjA0Dd eval($GET[$cmd])  '<>>  readdir  '<>> 1apaEn SELECT '  cmd RgRBH00LDj2JOn readdir  system('id')  cmd bSYKObJ36WrR5w0UMI_L_CNL system('id') KNgbchEZT73pCIpP cmd  readdir  ')  cmd 0AOwsq readdir  ')  system('id') V7llJII cmd sGyRQaugvX2T SELECT ' pzn6zx php  php  eval($GET[$cmd]) gWk1Z5aQEFbFrpdH15TprvvtOTywsBPyZjK9 exec  system('id')  eval($GET[$cmd])  exec yMAQh php 1EAFFE8 shell(' TLWxFAvGc9L readdir  exec 
 readdir  eval($GET[$cmd]) DyOWr0aD3Nyg4EBBtj SELECT ' EKbQi_rQRBB9FyzUqPKz4QSq77lqKJ exec jDprkPIjNlve cmd cfYu5dC_2eSjX4 SELECT '  readdir  system('id') tRLXbHO ')  SELECT '  exec  shell('  cmd  ')  eval($GET[$cmd])  SELECT '  '<>>  ')  exec yMbIsofZuyu0elWae2bnz8P0rKJBCaIuSZScXZpOP