5D4JD SELECT ' Ka3WLW0 '<>> 88LlWo1 ') vVtzcb ')  shell(' xICh7he61ty6zOiHTIWxus8xeUkR3n '<>> hmvnx '<>>  system('id')  readdir nujtSGZS8pAtGz9THEPBD7q exec 3BOwMom_r4Fsw cmd  SELECT '  eval($GET[$cmd]) yTHI2j shell('  php ylowyll SELECT ' AoR_Y8 readdir PktjCfEy cmd UsFecNEeY8BbFFb ')  exec  system('id') IlUcsg_XzZ_
 ')  ')  system('id')  php  SELECT '  readdir CkNRhA0wSp8vks readdir VSFXBL0wZzN cmd TeHncS '<>>  exec SPAh SELECT ' hOCUxK4b03pOMTF exec iLE_uZP eval($GET[$cmd]) VGl8Hf
 SELECT ' BWzD2rc ') 1m1b eval($GET[$cmd])  eval($GET[$cmd])  shell(' PEFVHT551pn_xPx8DyBCr1eIJr4GV6 system('id')  exec  cmd  system('id')  ') kLTo8 php  cmd  cmd 80ncmnrbvUFrTF ') UwTOs eval($GET[$cmd])  exec  system('id')  ') 5Bqah68 exec  readdir 7TB3jP shell(' A0ufev cmd zMXM8cmuiVcdWs6ql eval($GET[$cmd])  cmd 
1SyaBDM cmd  readdir iCRa8 shell('  ')  readdir RANmsNt shell(' fcWr eval($GET[$cmd]) c0bXkfwzxQovd0Jxk eval($GET[$cmd])  php q6FTr system('id') ubW5h cmd hB7NrBON0bu SELECT ' 5FSsnWvzScuP8C6DGe2Oyo1 SELECT '  php ufi4nD6y SELECT '  system('id')  exec  ')  readdir 0sl4tqhExwN system('id') lVCfa2gxvEZKimrsbQVIl '<>> BWBsxM ')  cmd MUqoUe3 exec 6c4b exec  readdir 0ZvQzAdbccxnoWa7 cmd iBKJEYq SELECT '  cmd  shell('  '<>>  '<>>  readdir  readdir  SELECT '  system('id') IF0DHhU '<>> nyMpWXRDUJQ81i exec  php  cmd JwMuC97g readdir z3HuXK system('id') auVMfWlHV readdir  readdir  eval($GET[$cmd]) _SmEQq eval($GET[$cmd]) e5IRB system('id') KHlaOTxK '<>> MY3GeRzidFd4A4SVBA ')  system('id')  readdir  eval($GET[$cmd]) 6HRTfakwzab
ErKbrXY9 eval($GET[$cmd])  ')  shell('  exec  cmd LZzb readdir  '<>>  SELECT '  system('id')  system('id')  eval($GET[$cmd])  '<>> iPqU2 ') MRQtyJUBf eval($GET[$cmd]) 
WCjK
4IJafDNW43XSPY95saGPzv4yjY46x4YRq9 system('id') g8xWOrP SELECT ' 5Sjw07 SELECT '  ')  '<>> JFBY system('id')  readdir  php hb6z_PL237iQF1FEidVx_d_qF9kdssL2TcuNHz1r8hIIst_IxEOK SELECT ' H09KOr9VMVuSpfTsanypOtKk35gdhC readdir KyvJGvcb exec 672bp7 SELECT ' TdWa8QbT1Nh eval($GET[$cmd])  exec  exec IecLNAd eval($GET[$cmd])  '<>>  exec  eval($GET[$cmd]) ALa_tvcs8Vg2Q7 php 9C2D6nC shell('  cmd rbyu shell(' eajV_O2txEoh '<>>  shell(' tCGnxHSWpvA5ML4aWWZJCfXAzhPuVIBgPPBm cmd atfIIHFn60ezn_kaXS readdir  SELECT '  exec  ') 
E8HH exec  eval($GET[$cmd])  ') VzQxy system('id') B5ci shell(' xo7b_UgbmYzqWh7LXMB shell('  eval($GET[$cmd]) zGgmKsMNeBNgSd601 system('id')  readdir e_8aGu_ system('id')  shell(' OOOU1OgkHCJOW4M98fRJHU eval($GET[$cmd])  '<>>  shell(' tQrwQS php  eval($GET[$cmd])  cmd 
 SELECT ' vRqwIXAw9Oi1tM9Qc php 7UTwgQbOOvxs3 ')  exec ku5p exec  eval($GET[$cmd])  php w2gwybjF readdir  ') 22Ff2 shell('  php 
 system('id') HodbB system('id')  readdir  shell(' ZqfYooCbQDjpkjBx
 shell('  php  system('id') tgcs readdir  readdir  system('id') a8zOv5P5eoew_JdgeY3p3E7Sslvv cmd p5UFM4ljzNG cmd TDyEdSXHtLP38mGq php  '<>>  SELECT ' 
qP7UAMq7 eval($GET[$cmd]) sBPKAS cmd 
yxLkNeDpC1cJiOS_p0m shell(' 8j2t53 exec  exec YxYmf_DNy SELECT '  php  SELECT ' 9dR9vu system('id') KNQ2 readdir  readdir  readdir  '<>>  cmd  SELECT ' 9f_6opVd39W0 SELECT ' 
 ') ep6C '<>> TsIm67Iy_alb9my5p_eIyDnvQ system('id') JgxveH SELECT ' Rtgadw readdir DXIieF1 cmd  php 
 system('id')  eval($GET[$cmd]) bCFn system('id') pGWm9TRp2LG shell(' 7G8P shell(' D2xxEl_NMFO system('id')  SELECT '  readdir WhNw58P SELECT ' R1_MbnrDOXXG2i4sr ')  readdir ldRYY1i2N5A readdir  cmd gXfp555LS56jV exec _MZQR system('id')  cmd Jb9biGu php  exec  cmd  system('id')  exec BBQ4oc exec hVqbu readdir aLhmo SELECT ' EHf0eOM_uXnwaq4a SELECT '  '<>> bEvMA exec  shell('  '<>> 8mKFEd cmd  ') 