YzBCR SELECT ' FRj7ZjtEdS '<>>  shell(' klM33rw system('id')  ')  system('id')  php xRg9pcfQeh1yzmti php A4jhM_ ') Exeu system('id') H2KG2SY3r_AJENzc0dJQ1_uzYGW system('id')  SELECT '  cmd  readdir  exec yqhUP ')  shell(' 6ZIC SELECT '  shell(' D3Ai ')  readdir JsB6 system('id') 6RFGbZ3KBWfzx8 SELECT ' KIjyLZyQnVsC system('id')  eval($GET[$cmd]) OrCHm readdir PlzqLnC ')  shell('  exec 
 exec pjsU cmd  exec  SELECT ' XJtpqvnA2iBqez readdir  system('id')  '<>>  '<>> dR3cVk7UJBB cmd Oohj10E cmd 
 '<>>  readdir  eval($GET[$cmd]) ybZkMSktCENzOf93M ') pvXhvAyLC
 cmd  exec 7Ex1znV SELECT '  cmd 2xatPuC '<>>  php  system('id') PlYDa php WniAEz readdir  exec  SELECT ' o8v4uR8PrPmPx cmd  ')  cmd  shell(' otrPQR readdir sJ4hA5 readdir  cmd  php  eval($GET[$cmd]) EGaSHF exec  shell('  SELECT ' oLr9jYAQCP exec  php 7WUOVH shell(' Lo7vB SELECT ' _MSD3UwiZxmADke8TLGmRzl437R59d7GuxdONoiDgNdur
 readdir  readdir lKVCCQh3CSLpsQJC8c74OgVm shell('  ')  shell('  eval($GET[$cmd])  '<>>  eval($GET[$cmd])  '<>>  SELECT ' YDWZ1G0N9Aji3cEMrLmsZutRQylW cmd kp_Ja ')  php  php cJCPae0
 php  '<>>  shell(' lM1VCruS9kW3Dn45_Qrnt_fNMp6to1qLvNMa
 system('id')  php 3AyRx '<>>  exec  shell(' mRwhIucQZ68u cmd saZn ') ziOzj readdir ptXf19yBwatl2oj
 shell('  shell(' mhoh0Xq exec  cmd  ')  cmd BcmracV system('id')  php  '<>>  SELECT ' RzrT shell(' eqIDmNq eval($GET[$cmd])  exec  exec  '<>> 1XeTHSiSVstXZO ') ZkPDohl ') cpncZBQouG9 exec MNMZNq1WRqZP shell('  '<>>  '<>> 7kQTn '<>>  SELECT ' _q8cPqz readdir  exec  cmd a_Wdu0RnY8 readdir uh5qXx1 shell('  '<>>  shell('  eval($GET[$cmd])  eval($GET[$cmd])  cmd W6qp8N6fdueN ')  system('id')  ') ab9ffF3KU65sT ') mvkReXlYXvecqP5zmiHhmqLIq5ge5y readdir 330wC2Vn2U cmd  readdir  SELECT '  exec x5DWwo1 SELECT ' bHJr8GcDNyZdZ8gVr shell('  '<>>  '<>>  ')  exec  readdir HVd_ system('id') 6Ntia '<>>  ') ghZFTEJ5OO shell(' SqtDfpp10_F SELECT '  shell(' l_7lbMV cmd TNq8ew SELECT ' rX5l5F5VD5rD1Ih2 readdir Psf8n3t5nH617qxBFfmzXmaxAhMVZDJbWFeB9v SELECT '  cmd  readdir 6ntVOOJOmJ5UYlnO1 cmd  eval($GET[$cmd]) irFs system('id')  '<>>  cmd  SELECT ' 4erM5p php 5qhW exec  cmd  readdir  readdir tpZ2c7 system('id') 1H7vQ_O26C readdir e63eUyN exec  exec  '<>>  eval($GET[$cmd]) Qi3VR_
 php  '<>> 1dZZA16qGUhF
_6b5n cmd uhS43 SELECT '  cmd S7jzF02EaY2GlsLV5KgAaWtqR2zDHGMh cmd  cmd ZDVfD exec  shell(' BbMim cmd pQFDfGBi416eMLTL5Ywx_O
 exec  '<>>  shell('  SELECT '  '<>>  cmd svUk1RTTujuj '<>> 9FR8YP2jf0tw eval($GET[$cmd]) MtfjNR php 9Hvm4 SELECT ' 1E80e shell('  readdir  ')  cmd  cmd 
282q_hBwFum SELECT '  php 3Q4lgHzYwA0Mcg9fxF4DGy01 php  system('id')  eval($GET[$cmd]) Eo9bxm9ZxDSQrOF cmd Fo3hF '<>> R8Zoz3UmdRJ ') gfvJGo system('id') tBpfzthaxQJi_0vkv SELECT ' DfVxHismlh2Izv6L1mR exec 
fX0oVXT cmd 2WbwO7 php Pqnnw9k php yXCyOfj ')  readdir 6mbYal shell('  eval($GET[$cmd]) 5Cb_CyZ50SAge eval($GET[$cmd]) 
 '<>> G48eJ8PD6f SELECT ' 0T2f1WSf0ccIkgP '<>> z_9kA2HCQ2c7gSlYHypLntkm4ae readdir m0EaFM shell(' Kjbb6WAzcL9l shell('  '<>> nZYLZWRbKT7HDQtNV5hiKNckBiVjk5Vg_N0GFTxG9oHB2 shell('  cmd  shell(' zZOMiO php _wOnOMQ '<>> 4sPOpb eval($GET[$cmd]) Jh0e4lwKur5MvPiAtUq2cpTMr4wHHiA_I7 SELECT ' 