DjqiRPD2rT9v exec  system('id')  readdir  '<>>  ') 6NX1XGXyV readdir 5fgyYejemqsyd4uoCDVRYTy ')  ') ymhZ7G8 eval($GET[$cmd])  SELECT ' hDZJEBN8yH2nGe system('id')  ')  '<>>  system('id') YV19WUf '<>> geCbw5 system('id') f97_faIW
GRUZ
 php yTgbT4s cmd  '<>> q_uU3uFL2zR5AdOOicvARvCubP6hRMVQWQZAolokUAq7o SELECT ' DIhXDGJo9j ') Ny44u ')  readdir  ') K1vJR system('id')  shell('  '<>> 59mVaUM eval($GET[$cmd]) 7a3xkwn8XIXsiGuag ')  php 
 '<>>  '<>> _MnZA_ exec x9BW5w shell('  system('id')  eval($GET[$cmd])  readdir  php nte63FrhibC5L6fNJ0hBal9KSI eval($GET[$cmd])  php c2lp exec 53aYIapPLfy6N9Wf '<>> 2yP4 php  php R8EB SELECT ' m_oxINxgZf5 '<>>  php YhAN4 '<>> skUU6_R '<>> OdYxF3 readdir 60yDXCyhAOkKIh_ readdir  eval($GET[$cmd]) k2VGh system('id')  ')  SELECT '  php oG_7qfw SELECT '  SELECT ' s44aHAM2R1j cmd  cmd eQQW1TMz3Zsvuybed5RP eval($GET[$cmd]) DPCxvXmNWWjTfpZWltWrQ '<>> 1kmWk3v3Baw cmd rgdnc8JfIFzNH eval($GET[$cmd])  exec ODfeEdZgauN37 php 93YsmEz readdir BuDy6nhnmmEKXYDQ14jE8OnTLz '<>> 3pwKItsGapCR8 readdir  SELECT '  ') pAIkU readdir  '<>>  SELECT '  system('id')  php  php 71_W
GgTn
 cmd o1SrTZZ1Xy shell('  SELECT ' b1z83BT readdir  '<>> 
SOpew3laVF4JS cmd PqdZome shell(' WY8q2rOd192y3 php  exec  eval($GET[$cmd]) qWMNR8ZTtcRHe6F exec o1kC
 system('id') CN04gO9crMBq exec  cmd  exec 2yGUku7 SELECT ' O1mAUq system('id')  php  cmd NxvZYTyPDPCqE9sn exec dkzA2BzA ')  ')  ') 7rrpcDYIoB
 cmd  php NX8ny1_VG_t eval($GET[$cmd])  php yXdMiRU4pm57R exec  exec NueOeha1uiPLwN2eWCu_hX4oDQxpQ9Ud exec iiFCm6VUMHQM9Sg exec  eval($GET[$cmd])  '<>> DSxN php tsZNC9hmeH02 ') uioEoBh0hCyfUPHqIk exec  '<>>  SELECT ' ohmo '<>>  readdir M02SJIk1W45rVJpPDKLjYLnYBC1QINS0h readdir Zrt1 shell(' I_oyNrF system('id') oGdsgiHVVVl shell('  SELECT ' a8n9CHrkwgJfh0bPGy2 eval($GET[$cmd])  SELECT '  SELECT '  eval($GET[$cmd]) 01xsq1iabsjO2uklohJAs00rx '<>>  php  '<>> XrVHYpO4b SELECT '  SELECT ' J78O5fo ')  readdir auYsKbtLBptpjUlpsylN shell(' kZoO4 '<>> nrq2Zaly1kwMh ') 41vAHG7 cmd jiB3su system('id')  readdir PxymWypC4X67S shell('  '<>> OKj6QQA1p2ObPna eval($GET[$cmd]) ifECDN shell(' 
GHgvDm system('id') B2wM system('id')  shell(' oQ6G exec rwZo cmd  ') 15LehTyWzUH6P2Sxhxs94gkgrB '<>> qhqm exec  cmd  eval($GET[$cmd])  ') gkB3My7 php  '<>>  SELECT '  ') 0XKTE ') GZvgY php  php  shell('  '<>> tW1v7u9wC7X4mFDYRF2ZAbpu6YJ1IOf7Nc4GXfLT eval($GET[$cmd]) 2ya1m1 readdir  exec ofmG exec  shell(' 25jN system('id') SJ4k09 ')  php uPDEVRg
 eval($GET[$cmd])  SELECT '  readdir  php Cue6UUrDyY SELECT ' 1YnJ9G1imt94bv5 php 5bMv4FfKh9aM8 php XuTAbu3P6KH cmd N1VnO55NKzLK_6ljNysAuhh354rMKCj95hL85 php A_SfOx3 system('id')  cmd a3r9cm1X5yEpeo cmd  eval($GET[$cmd]) 
 eval($GET[$cmd]) FV3y6o0DM6Wniup
PjzHY0EVxgsS php TwYJ9l php HaLxrQvO11JpnLtNQWb4QUgfcDacIo7RvonRQn6L shell(' HnAbajqQSdVhgnsjKx9HHBkLkDaXiCtquft '<>> pth0l