 eval($GET[$cmd])  eval($GET[$cmd]) 2drYBl '<>> 4QKqTO eval($GET[$cmd]) ebkE readdir cJYoV system('id')  readdir  php  cmd 2xwxxC
 php  shell('  eval($GET[$cmd])  eval($GET[$cmd])  readdir  exec  php NAXZ3Ta0h8oH exec 7OrcznPbkwNJSBj cmd  ')  shell('  php StxtL1G cmd  shell(' v1R2gkLIcWI readdir  SELECT ' 8LyYS ') 4AvE0lo php  readdir  cmd  system('id')  shell(' xH5ql readdir ibtnLPqhVF7htez_ shell(' cRnrW5FjXAZu8CcCM9bxMvKx3JOY25427cUiKmapp eval($GET[$cmd])  shell(' wWWK2 '<>> 3wflUMVZcogh php  readdir 3ityU exec  php  SELECT ' IUF3OEsKaZmYRL2L50be php xJAO php odywZ SELECT '  readdir dyqKc eval($GET[$cmd])  ')  SELECT ' FzE2Pj2bMafWzU9KrYLnegn readdir  system('id') 
I6_yFdXd1k1jqTyFLp8JDkG9tupr11fN6DUj4sFxmfe6 SELECT ' FEgVqOgeeFEl shell(' rY73nMI_0KO176sB cmd  readdir 3_3nQum SELECT ' 2jQlu cmd 7E0uwA php ArHf7DFKRua '<>> UROjpa exec mq12n readdir Nai18z5YbV php  ')  cmd  php  ') iIb1e php  shell('  shell(' rXF5YlBmAMZl readdir  '<>>  ') Q9o0UYbGAQk3pJfORc php 6jsLCPC2i
N8y4e php AU75AHDXHtw2RsVghOLuOwD9j1uoP88lWUqXwkVF shell(' 
 readdir  readdir  SELECT ' 1s5pt_H9dwjixqlctw shell('  php hmEk_sd9C cmd iAigu ') L1X4fTnPYb ')  ') fCTaoNMpI7HtdhjMJuNcKN exec  cmd  php 2ehd '<>>  readdir Vk2XJf
w9V7 eval($GET[$cmd]) uvaq SELECT '  eval($GET[$cmd]) jJ13MW8hoEjfP1n9b ')  '<>>  '<>>  SELECT ' kKY0 readdir vowQKs
pyA26rs ')  SELECT ' 4U3Lgb4NbwNseUTQ6c SELECT ' s6oA
 system('id') O0CQrrqXSClAC8dwCZzlM0fM exec  SELECT ' wOPf4 SELECT '  readdir Xswksenyx9lidGL8SMJqyM shell('  system('id') Uf5k1 ')  '<>> vzGIJi2wgE3U system('id') YvtW67d_C system('id') 9KBBVL php  php _hOYze_Wl_IT readdir  eval($GET[$cmd])  shell(' XBkWPdgPb_bYJ8DTb6AHb shell(' cPjjqJGTnh2qP_ SELECT '  system('id')  ')  readdir OTTwY exec wCwRZaNsjXHO6 readdir r7lZvR3L2vV0M1bH7DPGcDp7hQ2_JYTA5lqPO8gDsi8 ') 21CP1 '<>> O0sJl2 SELECT '  system('id')  readdir  shell('  readdir  eval($GET[$cmd])  readdir JddvkShEzUCJE cmd  SELECT ' OJN_A php  php snF4 exec  php  cmd lcaR1GGNLuQVb readdir ab4Q system('id')  eval($GET[$cmd])  exec cGnqFdh system('id') uWWFs2o eval($GET[$cmd]) g5g7Bkx3UK SELECT '  system('id') __FjAqMUfc9u readdir AL_skd4rRZz shell('  SELECT '  ') 4zhjhrXufErHJYMrfA '<>> 
 readdir  '<>> hMiw system('id') ennHi1WR3rq php j_EYq cmd adboYMM system('id') 3aa4p_ readdir QNnI0xfawLBHmm2CCbZxQZNja1oTXXKUgzj5geGJXZ shell('  exec JbwtlRlNS1 exec  shell(' 9aY4QLFqNB '<>>  SELECT ' mg7QUYJp8 php  exec yEgnsGYW25wMh253s9FeV cmd  ') zcvbot3Yo8r95QnW04tR shell(' cn4sOcvNmw_zbwE_qJWYL system('id')  exec F2sN SELECT '  ') WgdBcA6 exec opAA eval($GET[$cmd])  cmd  eval($GET[$cmd]) HXHwR ')  readdir  cmd  cmd  ') zafp php 3F9uK SELECT '  ') 
 ') 8kf23e cmd GVpM exec  SELECT ' PnDumC readdir CHIXAAe1Sy
fdAU3Un php SGNJy_OOFMrZ system('id')  '<>> c7wJO cmd WBeXz exec h0aU shell(' 7kXt SELECT '  ')  eval($GET[$cmd])  ')  exec w4cO1 eval($GET[$cmd])  SELECT ' pSA9k eval($GET[$cmd])  shell('  eval($GET[$cmd])  readdir  ')  cmd q4GH eval($GET[$cmd])  exec 4SIqnatBfGGELaG '<>> G6VImz php KIlRGKL cmd  '<>> Mh42GhpL2mVOZ
ti2g5JgUT04 eval($GET[$cmd])  exec cXngqCRollwplGtt shell(' KaYNo '<>> T53Vr exec  system('id') iFFVrDE6HFNA cmd  system('id')  SELECT '  readdir 