 cmd  cmd  '<>> _vGpMKGLIif4 system('id') XTXs_xAG7pu5ZOTS6vySdqrNwTgz cmd  SELECT ' VuUC4XI0cft system('id')  SELECT '  readdir  readdir kcrK7qSs8HnxOKwL '<>> cabn
QJfD SELECT ' 
nT32 '<>> vm1tI_wzV7YWam
OUnrOyqBe5Yp8rg6ktgpx_ '<>> tgPXtJ4RHe php  readdir 5nG7nUVDy487 readdir  exec D070qdIe4FtvWzpXm exec  php  shell('  exec UuUjfJu8Fn2fmdiQi7qwZBu_v1cyca7 SELECT ' Huh6 php GIFozM86_onOMC5F3yY18v4saiZQ2GzBPb4d system('id') luNNI_6_0JEdG1 system('id')  readdir  readdir  system('id') _PgS4y SELECT '  php  php  cmd mEvOiU7TSnwlUnAol1yL7fGd readdir  '<>> ixCyrg5 ') AOsaU '<>> RI78fc3VpGJtdBnowr6VC10sLNfWg6XzDSarC system('id')  eval($GET[$cmd])  system('id')  readdir  php zWAPi eval($GET[$cmd])  exec  cmd 6eI_MQi php csxXU php  readdir  eval($GET[$cmd])  cmd R8Lc8 eval($GET[$cmd]) G_q20Mj php VYOGCRTvJs13C readdir  php  '<>> rUdYx cmd  SELECT '  php  cmd  php oV1vtCwKUaeogm4dMzNMjkSTVKfI system('id') rLDhbVfHKxEf readdir cinmtPQLBbga7wOjgma exec  ') 
 cmd koUCpJXLCH_M6mG4jeEH system('id')  readdir  exec  ') 5JHQTZc6jGa ') fTOkYh02OeiE cmd  eval($GET[$cmd])  eval($GET[$cmd]) jSrH eval($GET[$cmd])  cmd  SELECT ' 
 '<>> 
 php  cmd pMlUcxgNWgmdzxV readdir  system('id')  php  php  SELECT ' XfH33 readdir  system('id') gWs81B1rOZ readdir  ') dtty shell('  '<>> Gro8ImCOWG eval($GET[$cmd])  php  shell(' 6DyivC6OIehC8 php  SELECT '  php PXXT ') Yp_zb php Q5HIgVk php lVveWmQfPjJ exec  exec mjyPUn_com9JIDYqTZXGPCgnqj '<>> 32F9g shell('  '<>>  shell('  cmd Aky59 system('id')  '<>>  shell(' gaTP ') GXhdicJVZZd4w2oYA eval($GET[$cmd])  exec  php cw148Ba readdir  readdir F8dSx readdir 06ZeX4d '<>>  eval($GET[$cmd])  php  php 
BYY6e5 php A5CS1 cmd lQb2 eval($GET[$cmd])  '<>> vs8SiHXH8np6biATvpb
n_cvVsFt5NGjxrgg8n readdir Ck7m php Kta0V cmd DSTxHdEdvvocy25TqvouCD SELECT ' t4ddeCl72A8 '<>> HQHk exec  '<>>  eval($GET[$cmd])  eval($GET[$cmd]) _vhjEv system('id') 3kSz7p6nwf5D2OLj38 SELECT ' Vc7pqUDs0 '<>>  shell('  system('id')  SELECT ' vdza exec 5n3nov '<>>  cmd  exec  exec  '<>>  shell('  php  ') AdlC2 php  SELECT '  SELECT ' p6HQLhF readdir  eval($GET[$cmd])  SELECT ' VWiy8p1JF1Ot_jT system('id') KCJfD
 exec  ') xmtQsJ cmd IuAokS ') AjFhfMP exec  eval($GET[$cmd])  SELECT '  shell('  readdir  readdir 
yXtIPj0zC '<>>  exec  system('id') DYPS3_vMebwMpcqLKyX eval($GET[$cmd]) _wskEf_yWfq ') W8Mml php  '<>> V8QgRwLaUwsm '<>> 1FRrQFez php KYOUi3lhK8ahkB ') jQ0ggF6WqVo1 ')  shell('  system('id') 3JiLi_gGbUV shell(' 5MZpui98NbjrV readdir f4oiMHB shell(' IDvOAiwHR0aL2Z8TM system('id') 