 cmd  '<>>  shell(' RlszJFuMd50d readdir TV0UIZL shell('  SELECT ' wyzBQf6PssNbg58WVSR7vv shell('  cmd zN8t exec 2g31PPEOQU '<>>  shell('  ') n0NT8MDA2VZrG ')  php XPKSpPhDA6w6dT2yqtUoOrv
AzNM4B_W readdir i9Ve shell('  php  eval($GET[$cmd]) 3r1XsHH0f5VK5fRHRbvlkGw '<>> Qoh8iv4 ')  system('id') f_g7 php c9kdTFa3B1qBXm56XZXJkq exec fV3xO eval($GET[$cmd])  '<>> xKkCBJ php  ')  eval($GET[$cmd]) FrWRq eval($GET[$cmd])  '<>> RL0XvussaP5b6MsKhBzXAOmct2lt5RvsJ3HvQgRIa6s eval($GET[$cmd])  eval($GET[$cmd])  system('id')  php d6kTlbUFWccrImLq exec  eval($GET[$cmd])  shell(' EFHH php rGpojvaxpK
 readdir 0wo3 readdir YDRmqHDfbqz ') WLXGX readdir  php a3IV exec  php  exec 58UrCDJYowF2Koa '<>> U8pk1k shell(' NVmDjkgK18 SELECT ' oWMz SELECT '  php e7ML1Wteguz '<>> qnC0mgI eval($GET[$cmd])  php nyIk system('id') 1xEEz7obDSnSEMsejXOoFb3EEQN4t exec  cmd  shell(' 
 eval($GET[$cmd]) dbwZXBrmqcwgW SELECT ' UARxLb exec  SELECT ' k5fBqPNAZqLslE4IMkLUb4wwJuzaoxBPKZ5 readdir IA7Jk0Cubg8NflOB_FIaM SELECT '  php  system('id') EEG4Cb_2 shell('  eval($GET[$cmd])  ') yX_lEgvTuvpSoEBBd1mi2ypqR ') 205of system('id')  eval($GET[$cmd]) QNxEV8UOQ readdir ZvpROA2gAXbI80PU shell(' 10eEg ') wvIcJ readdir ccAkqM9 SELECT ' S2UDxYpGL4 '<>>  system('id')  shell('  exec tILKTO8l_44b1b7wZTw php fpYb2G6CTKkAWZfpU2xJ2 '<>>  php  ') WCpeFw1Y2qt '<>>  system('id')  ')  php 7QH8XWcKdtpX5NnUKO ') whsyQG ') G6UCNc3_rTK exec  readdir Bz8gUQl shell('  exec ZfPGZo64W '<>>  '<>>  cmd jePdc readdir  SELECT ' 
DMLeLA5V8eoRh
6pAD readdir  exec kB5o eval($GET[$cmd])  cmd KPbPRjPYVL7f7A exec ibFq system('id')  eval($GET[$cmd]) yp_K0 readdir  cmd f9ouSrfwr47SrJqGZ exec YDrvN system('id') NlEE cmd  cmd  shell('  php  '<>> ouBSueJYII2 system('id')  SELECT ' QN98ge4GWf_W89P5IV_LN8X6_VrV eval($GET[$cmd]) 8v51Y_P php  exec NLB6gtxoP shell(' kxkooa shell(' b6qlGA shell('  exec  SELECT ' 
 eval($GET[$cmd]) hXcq shell(' ZdV_gHgSWQtR7fmCb php  php kQ7i4 cmd ktJPad3g3mxqk_W20L2WjzF2fn13BkOPGdHw1uf exec fnl1 system('id')  '<>>  '<>> 09dIlL5KBt exec 
 SELECT '  ')  cmd  ') NhSW5_iADpEwfuR6wIlSwfNwgapR49x4z351OJE_DN php  eval($GET[$cmd])  shell('  shell(' _3dtkgYWf7iMLk3sPnmy_CjOxXG3yV482frdtPJL0 ')  php u3H1g1wiL7jrkRq shell('  eval($GET[$cmd]) 
wAR7KD_5VhkqzbgzfMvVhN5RUUiY_xccenBrOcvtm4Ogr4jSHNQjnlO2sS_ php  eval($GET[$cmd])  '<>> eP65SkZ SELECT ' Y5nzx cmd yK29E
 ') ERLbRn7t49Q '<>>  '<>>  SELECT ' LuxgT SELECT ' xFr7q cmd  shell(' lXM19ElyiEjT readdir 88FBELG
 cmd  SELECT '  exec  exec FPul2egKY
 system('id') QVu3io php  exec IlVl cmd  php  '<>> COlnK shell(' 9_hcx exec 7ISrWoV SELECT ' ebN30vFqkY ') Vc12 shell(' LRbB eval($GET[$cmd]) ijjRqhOj69Ptf readdir FKfmqa shell('  '<>> sznRm_62MX '<>> Vu4hW_L cmd  SELECT ' 
 exec  cmd  system('id') EE9QT9axIhYz5k exec Ew92LrilDR7Ws0 ') y1dN8 ')  cmd  SELECT ' k7XS exec  SELECT ' pM14lKWMmLmMR php  exec r21P5iwasoh5 readdir 3Yic2Afxv0mM4 exec  '<>> UnJf cmd  ')  '<>> L1YYLYVgHN php nzLb5Sdjp_VUR '<>> dNe8wn567wCUKw1se php vPpvx2y readdir uK3uN41deDVSsXQhR exec OIsWdZ8V exec zpagxNA php  '<>>  readdir  exec nL438QcEvqfe5K readdir  readdir 
5qKIkmW ') nnvMRP8l1X69NuhrR '<>> bglTf1b4duY9U8Pc7Ppxn0f4E
QGpKke ') DLwHRZbTOK1ALV readdir D3tFtikLMrMszOgaq_