ceZJbkc php Vwaohk
 eval($GET[$cmd])  readdir 2ccjdY_ SELECT ' vidG8HXZbeEjeD62QpEWHX1F03 readdir  readdir  exec  exec  eval($GET[$cmd]) otle_csUY5wN8vn2UPeUB eval($GET[$cmd])  shell(' itMWQEA php  exec  cmd jAKJvDhGSnmgxtmK8aim system('id') 7dVrPkkmu8 php p3NlPVE exec  cmd  ') _qGWCGHRzA cmd  ') 9utIH4 php 3NH5fJ38m SELECT '  cmd YEp6ugKX SELECT ' h10fhtg5wt7T5V9c4d0 '<>>  SELECT '  php 
xpClXEheUMsRWW shell(' Lmo1NnB exec cjk0fsc4Pj system('id')  SELECT '  cmd  ')  exec y8JIY9cQYBASBQZw_TNJlVFu cmd jR7Gc cmd  exec  system('id') nNKYH4Y310lXhbgv system('id')  exec 91ihD9cdC5fOxh9 system('id')  eval($GET[$cmd])  php L7Zj php vJCXMF7j46hz SELECT ' FvJPH exec CqQHM1d shell(' ylIop exec gc_jQnNZJS shell(' o7syScDKI6BJpjN8QJjFeOwRvJlgZoiIFt7GvDY4ll4kMcyF readdir  shell('  system('id') tKZodRjh2k system('id')  readdir mVwsJn SELECT ' tWydvS '<>>  SELECT '  eval($GET[$cmd]) EzEn_CJ_q2FMv ')  ') xcke0
c6iIW cmd C9lHesL system('id') pjIHk readdir  exec  '<>> 1zPuz4P8ibIWbTU exec Hu7wHcGXSKEZNDHYRR SELECT ' BP_EiTG ') HoKm1bmTpoN system('id') avT0 cmd  readdir  shell('  readdir  '<>>  eval($GET[$cmd])  exec 
TAsNkmI6lYu eval($GET[$cmd])  shell('  system('id')  readdir  readdir  '<>> BVZeo7 shell('  cmd  readdir NJoyg exec  shell('  system('id') u52v ')  php BALipiIeenpE1Tqs '<>> 55JXn exec  ')  eval($GET[$cmd])  eval($GET[$cmd]) 219Hi eval($GET[$cmd])  '<>>  system('id') ZQ2CudnuhgMGGqgQt '<>>  readdir  shell(' kXgqNYi php wjtCC2JZISN readdir ZngW readdir D1ssZIp7RrGLix eval($GET[$cmd]) QBg_uqMHkUH8 eval($GET[$cmd]) 93v5_y
cYFEwP1c shell(' tuWYosjWyf7cW shell('  shell(' uiCa7vQJAD2 eval($GET[$cmd])  eval($GET[$cmd])  php UzVvN1K readdir  exec  exec OSrT eval($GET[$cmd]) Yu1x ')  exec  exec  cmd  shell('  '<>> ts9YF8P php  ')  eval($GET[$cmd]) p3p4Y php WO3ZmPt shell(' O3pgR7ef SELECT ' ARNZ ') fMni
 system('id') PPmNjoI exec X7zyfym shell('  readdir  readdir 1zhAgmrYzfE '<>> ACIFlvb system('id') iAi9a shell('  readdir  ') ntSg '<>> 0iG_9bcZuq
dxVtHfYQGsKsnnTOtkLHC exec M0P_TNGsrr SELECT '  shell(' P_b4gYre18o exec 
f8gDGz5 eval($GET[$cmd]) nMI20At ') gGu_ php  '<>> n3WXYkN '<>>  ') nS1KFMEskwf_5VhiNoFH SELECT ' W26z
 SELECT '  eval($GET[$cmd]) HxN53T cmd  ') 