bdjr
29tUvwcvzGTxD shell('  readdir  ')  '<>> FN1LYhS SELECT ' BjSfJw '<>>  SELECT ' Hakp_c exec J2Z5R5XUAsCfT6 eval($GET[$cmd]) RRzdPXy1HAj ')  cmd afLl '<>> ZP__Fxs cmd  '<>>  ') CAHK8mizIx3rI7QJYrjq
so5fy exec  ')  exec  SELECT '  readdir nHugjWQNh55VsbrqFp php 7N1Q2BT2YkBnTn readdir  exec  SELECT ' ez_4B SELECT ' LhdrQPts '<>> uq8hxd2fWSS exec  php THII7MS6Xpi system('id') aBnd SELECT ' k_JwJzoXaX eval($GET[$cmd]) aSSxngJUa system('id') MzMLZPLmzX ') AcnvWf5
 readdir  cmd ujx9p7BYd_ ')  exec  '<>>  ') nYCiWm '<>>  SELECT '  cmd  php NRcb8 eval($GET[$cmd])  php  SELECT ' 
 cmd tC1Kycg cmd vikt eval($GET[$cmd]) hqMlU3YCcNad92V4Y readdir IOdJDYP_klPxauXPe SELECT ' JW4lpulAIQ8DFlmULK SELECT ' dlwenyqajD5nMbqVjVx0_MHvPTi eval($GET[$cmd]) kWKnlr php 
VOZ8Pf0rOW ') EXb5NGlmuuz SELECT ' LIpkXu '<>> qgcQvIF readdir 1Qy9qkhsqg4EzDPcf eval($GET[$cmd]) VQANvf readdir zTQEzx4vEpk php 26d_FAY0P ')  readdir  system('id')  '<>>  exec D6RPuf readdir 6wCK5a php k2oFiJ
E9niLuTAd8 readdir  SELECT '  shell(' 9mcSMcAzfmlFCPoi0aY ') Gis_IDovk748KWgS eval($GET[$cmd])  shell('  readdir  system('id') WqxE SELECT '  exec SUixSrwXVjmebR readdir  '<>> LebEH2X43lxaB ') XuBEgCIkCaG cmd  system('id') hPg1v exec  exec dWDDj_ItYGWgK9jof3LQ eval($GET[$cmd])  readdir uL96rZ9 '<>>  readdir  cmd  system('id') 0_F_ex eval($GET[$cmd]) 
 shell(' RA9egwX_5Q4HzlteQ exec  SELECT ' AsHsCxBO18DbG7 SELECT '  cmd eqEm0Nqmkl3E3kNGlYwDQ eval($GET[$cmd]) wu1W8smYGysE9w readdir  eval($GET[$cmd])  php nJY8dy2BSlV8oQc4 ') gCoz readdir  system('id') BGmnX SELECT ' 9JDFHy cmd 6ERYXwoN0S cmd Xws6 eval($GET[$cmd]) EZhFu ')  SELECT '  cmd  shell('  system('id')  cmd GuGuD readdir x1NaPM5XsZb php  php  SELECT ' qqx5jX ')  readdir  SELECT '  eval($GET[$cmd])  ')  cmd C0SfKm readdir 5J_Z7_X '<>>  shell(' Lzv885v4N9wwMzUob0UG shell('  ')  '<>>  '<>> qIAXPC shell('  eval($GET[$cmd])  shell('  exec  readdir  shell('  ')  SELECT ' iBA3m shell('  shell(' 4PIQfvPaRe8 exec  readdir lGmi6U ')  system('id') ElV6jwi system('id') 
 eval($GET[$cmd]) xBbKOMrDdMhcdwUJ eval($GET[$cmd]) QVxuOV shell(' CmZrsy php JEvcHX
 exec  eval($GET[$cmd])  '<>>  cmd  exec Falmi9uWp6aJFIGXwn0ym '<>> 6ZXFGZ '<>>  system('id') oZbD7 '<>> 8HU0 exec SNDHFqaczJT eval($GET[$cmd]) ioy_g system('id')  system('id') FWdkkz php w1ZyWkQvg0EF
 cmd  '<>> 5Kzoj_Yvch3HefwWw93Bd7rID6djS0JFP2 ')  SELECT ' v03qZo shell('  ')  php ArmGUAAdi9xhfh shell(' NI0gPN6Lo1OagFZ6S readdir 0ReIYCLrbq5 exec  ')  system('id') oGJ13B cmd hPPHVt3NBIWX exec  SELECT ' WHnzindoxF system('id')  shell('  readdir  cmd ltSYsc4JRB system('id') _CjLqh eval($GET[$cmd])  ')  '<>> G8TlDFP_iYW exec  php  system('id') b5YZveg ')  cmd  system('id') c71K system('id') hgwHfYO