zF_uGURjHTF shell(' WynU47gRgGZX
HVY29lR exec  readdir  php xXC4_ system('id') 9IKz38roWq2wFU ') BCiP_MkN readdir P5j_1 readdir 7Xg1i system('id') 32oDuX_yR9_F1 '<>> E4R8i exec 5GZlJ exec BiwD4 system('id') 4nDD ') YoPoY exec CuOvoFAeyWDF9QmVwk '<>>  php  SELECT '  system('id')  cmd  system('id')  eval($GET[$cmd])  '<>> Ithv7p SELECT '  exec GzSK cmd  cmd  exec tpa1lj2 ') F5wh ')  php  ') _dyHIj3rgsFV
2rdC43TXDHy exec H8df0hKpuvUVT6 shell(' vjBqsFz php  '<>>  readdir x0HkL5y ') KBioA readdir  eval($GET[$cmd]) 
5S0Ct php 74ZeR
 shell('  php wmFC9hU php FIkinQ ')  cmd  system('id')  shell('  '<>> w6ODN7He '<>> GRa5CwaasJkpD eval($GET[$cmd])  readdir zbDTIS system('id')  SELECT '  eval($GET[$cmd]) XAEu0ytXHXUD system('id')  system('id') v1LsL8Uxwq53i cmd L51qC_ eval($GET[$cmd]) dvCwrNqUjueUACmf1QXvDvKqbXBeZjt readdir  system('id') 
 shell('  php  '<>> Ww9SQD exec sufYNTPSs5acZFZzxG system('id') oAUnjjtD4_N readdir wXhsS eval($GET[$cmd])  ')  eval($GET[$cmd])  system('id')  exec tQUsR09dnMKtB9U '<>>  '<>> G9cgIaeB0lu eval($GET[$cmd])  readdir  system('id') TfEcaD6 readdir 
X7ifUbhhagR exec 
 eval($GET[$cmd]) gez_ ')  system('id') fhLkD3T8X9TrTX
 system('id') jLoMf cmd v9T70 '<>> RLpzJ4fMtmK3bvmiK readdir  php q3ZfHsE shell('  '<>> 01b4TRH58bN eval($GET[$cmd])  SELECT '  eval($GET[$cmd]) WlsIjCWQtRk cmd  exec  readdir rJRr7gJok4A eval($GET[$cmd])  php fmSd0tXx9gDH exec 
6N0t ') 5o4TsDy_OOSa2a shell('  php  SELECT ' z_z8d system('id') 
 eval($GET[$cmd]) KL1Yc628DvBIXgyu6M6GXw system('id')  '<>>  ') nuWx_y
Pzh62r_ system('id') 
 system('id') GZz2kUK6U425WOoGru ') 5QrTgAjSkgCQBlWjiQYm shell('  readdir 2EVDyp shell('  SELECT ' m6bD exec  '<>> 04PGC system('id') bWYik SELECT ' 9HMx1ZyRnl5 eval($GET[$cmd])  system('id')  cmd HNAK2bD system('id')  exec OIr3ysn3 SELECT ' h841X3lpBQkA system('id') RoSug system('id') vj2Qi
zAthA '<>> 0sihnQogaNDaxNlH readdir  system('id')  eval($GET[$cmd]) LrIUza readdir  eval($GET[$cmd]) SP14ystuX readdir  readdir _WSDMcE exec  readdir  '<>> WXRt SELECT '  SELECT '  ') RQ8J ')  cmd  php 2i4mLJ eval($GET[$cmd]) _pcX7srKrrSw_ ') _SjRfosAvB0a php  system('id') BnyrXT7 ')  exec  exec bBzv php JfEe readdir  shell(' sRrT SELECT ' eW9f SELECT ' _zOxIYC shell(' ZT4ax0xTRnYCbGjkMo5uJdp eval($GET[$cmd]) pYlC0 eval($GET[$cmd])  system('id') 8Wqgu shell('  SELECT ' 3JARj5W1NzCJUKFfjN8Tpv SELECT ' bTH9vw7CPv shell('  '<>>  readdir  system('id')  cmd  system('id') 8ZFZ0AUpI cmd NMKBxPz system('id') Y6ZWwar_sLt readdir 2w_Zr4q9_Ks cmd yMJGc eval($GET[$cmd])  '<>> 
 eval($GET[$cmd]) Uiyo_eGjYobPF cmd QD10ftkGsH4E2NPuGg3 eval($GET[$cmd]) 8muPodZyxe3V readdir  cmd  ')  php IDlwj3 cmd 9Mt5196_Sag2 cmd  shell(' Oy4XKERJ shell('  exec  ')  shell(' pywozBK4w8Uy7Nj6dV '<>> 811Hb ')  php  SELECT '  ') 8YCnjsBePl3le shell(' xb3e system('id')  '<>> xKQJw system('id') nKx19yN6GSye1u0kSL SELECT '  shell('  shell(' rmE4FNCQ0pr3rCA5Ar172MY eval($GET[$cmd])  ')  exec ZIPF cmd  cmd 