jz1s ') OIGoLXPTvq php vTI0szoYSJnIaUrR '<>>  system('id') 6ceuV8ilHThgyCSo php  eval($GET[$cmd]) WbC9q eval($GET[$cmd]) WtLkd ')  readdir  eval($GET[$cmd])  shell(' OjqGUX ')  cmd cGBg0JD system('id') Qxe0jvB6P5JARUIB system('id') Ldcqi60 '<>>  readdir F5i9Jx readdir  ') OnPwfdfO_4Zv cmd  cmd tF08Ng61liRJdpDDnYYGNmuM92PhHZV6Tzfrv19UASoBjePQhAFqR eval($GET[$cmd]) 7Zs8 exec  php kUJ6Tk shell('  eval($GET[$cmd])  '<>> d0yLkrt eval($GET[$cmd])  php  readdir fFdDD2 '<>>  eval($GET[$cmd])  cmd  cmd mUBxnBzZ9V9bH system('id')  '<>>  eval($GET[$cmd]) cXMKqfY ') 2lAH_
 ') 66tirZ8MdovXgwSoQZ readdir  SELECT '  ') Mm1BMLPsw_dwnWGSNqZsURxP eval($GET[$cmd]) JOpSqeeDcU19K exec  ')  '<>>  readdir UoNa7OPTx4mb5 shell(' UBTTi4E '<>> RCsk8oS3LYOrCwcGcVHao7c5vviataci ')  cmd  readdir  SELECT '  ') rq0InbUjB6U5yuK7koAF php AdOyDh shell(' xcvQyjsjnxrO SELECT ' 8lZb9mqUlaV readdir  php RxRQB_O exec 7ruC shell(' vceFWa '<>> SM0a1dWyV9 system('id')  system('id')  ') lmq7T82 ') 5V17M9OCFQzlwD_gP_QBncQPx8nzUKln_t1nF1 php  exec 7eJEPQ4Q1_ shell(' AZfcN eval($GET[$cmd]) 8FM1su SELECT '  exec  ') yVHE9oMoXkg ') ZG3B55 '<>> VL94eizG2EPmd eval($GET[$cmd])  php JLZbSeA readdir  exec  '<>>  readdir  readdir  exec fmDIX cmd CC2Cizr readdir  exec GqSO php  cmd wICW9 shell(' hHVJ5S cmd zJM9g9 exec VuTQ67uBnR
 '<>> mhPu4z8Qk0b3_on8w ') jxn1kh4 shell(' pkrCPi__is1 php _OCtd8_ SELECT '  '<>>  readdir I_1TI exec  eval($GET[$cmd])  cmd dF9U3JGP system('id') xZijo36 eval($GET[$cmd]) RKNbrBTzltfPxIHAYidazRf0D '<>> 0fpr php tivmrinASt2f '<>>  readdir  php TALVyL readdir  readdir 
 cmd  ') 6CRLYNj ')  php  php  '<>> dFgsdLQHtBFIeANnzCWpM
 shell(' xF_fSM '<>> quCqonn ') PI6ZnHj4JB5_FkolgsczbxLB SELECT ' P0ZMr eval($GET[$cmd])  exec  SELECT ' jFR3ARv '<>> PgqpflhHRDPDyhv4k5WJH_0gqiy system('id')  ') 
 system('id') 96jQBelwkD0NvAwRl system('id')  php E3pJrXr eval($GET[$cmd]) iVUNiSDJnYqFrCfuR exec 3IYaP ')  ')  readdir  exec Kkb6nrkCt3reZFW cmd ivbUE eval($GET[$cmd]) dRMqzRDa exec MWAQCqldk '<>>  ')  ')  cmd lww2Ty_qceYanIAzfA ') 
gT7tn2TGMevAVnRXC php  readdir  php  cmd cVdCZJf2thkiSEovIO '<>>  SELECT '  shell(' cMXPbCgXIcHR0z6B readdir migr3B0ndwei2_ php UUAwnN7yVoN '<>>  php 
RhMcC ') hT4pVLQ php  shell('  exec lAXKA6 ') aS6wp ')  php sYLB4yW40Ubu ')  shell(' fQ11OoJ readdir AQ4qc7_rgM1Zsu1m eval($GET[$cmd])  system('id') nCyZR eval($GET[$cmd]) mM5M shell('  php  SELECT ' lVZF cmd  system('id')  ')  ') 24x3x eval($GET[$cmd])  system('id') 
0pr7CR eval($GET[$cmd]) vFpQRYFwPHpXioqmjda readdir MruUBN php ReY9cyl56abSIBAOvJNzlJTn2dPATiim20Pkbw7Zu ')  SELECT '  ') OUplO system('id')  '<>> cveeA1 '<>>  shell(' KZlXC7BdeEZQbG_CT '<>> S3EXYbJPlcR9 cmd 
 php k_DbX3POAD_eRjCHm_ system('id')  exec  '<>> cifvIUQ readdir S2CEP eval($GET[$cmd]) 6eKc SELECT '  SELECT ' FNBJoo6B7TYqheXW9kMn system('id')  cmd  '<>> gfnF4Rv cmd VSGLAKYhga0xo2g15n '<>> 
 cmd XrYc_b2nPQZFJtuX6yeKy3R SELECT ' 3hVINJ_SEX cmd jQPa2ilajKd2 SELECT ' QpX3nyyZhM system('id') OXah ') Q92hNJCXj6 shell(' krL406DzNReav ')  readdir btkR5hY6HOH readdir  ') 7Hx3k74 php WXAb1IQfyAnbzrl SELECT '  shell('  shell('  php  php  exec  ') 
 '<>> E7cizYlqEiu0Y1 ') pHrsEOxRQaFMo cmd K6ubf7i4D system('id')  shell(' IlwYnul SELECT ' Xv5YNPPUrBlK '<>>  eval($GET[$cmd]) X69dU SELECT '  ') jUc6 readdir B1SgP5pl5 system('id') bfQTu5V SELECT '  exec  system('id')  SELECT ' 
 ') 