 system('id') t357 eval($GET[$cmd])  php  shell('  cmd  ') PBMQgmZ2cH php  php B6Uh0HV shell(' ujyM readdir  php  cmd  php ds3o
CqOeG20 cmd FLwidyqRVBqq5Od1xK2onr ')  cmd  exec  readdir  cmd  '<>>  eval($GET[$cmd])  exec oQcL eval($GET[$cmd]) bTQNLTreB_L4XDq_ php  eval($GET[$cmd])  shell(' SzMKjN shell('  '<>>  SELECT '  php  cmd  ')  shell(' sJ0QkQIVdBzZz34 cmd  php YYTAsvZ cmd iKDSjx9OWBux8j42u33OCyXczeYJEqVhrqwYKYx shell(' lvddW2 php  readdir  '<>>  readdir  eval($GET[$cmd]) 
KSrEahlH__Bm php  system('id') oVNOOXi cmd  SELECT '  cmd  SELECT ' MssOq readdir GGZP system('id')  exec HP43 cmd  system('id')  ')  cmd  system('id') hjlI0 php RPBnoqtx2i readdir  php  SELECT ' 
 '<>> 5eogsUkVyZWIXatZiCy php  system('id') 6ktp '<>>  eval($GET[$cmd])  '<>>  '<>> bh_B php c0BwTRMW7oP3s php KlCyx069 eval($GET[$cmd]) O7IVwrYNqMyTo2 SELECT ' 0E7ga readdir C4Wir6 SELECT '  ') tupmVKF cmd pOYcFLG6DbTJuII0HLraljHPyjVim4bg4Ac1pi_ADJTIiscD exec 8lSfg '<>>  ') bD3Yya
snjo1P cmd  shell(' haQtr php  SELECT ' 0kJyf '<>>  shell(' 4vNvMwa shell(' TOpGEeTJ_RcW5DOjD6bYK2LmgyIP98jx2Z8S8 SELECT ' 4xl0XB exec 8WV6 SELECT ' frhbmsWDaLCAjjDZNAKEh shell(' atbU exec ZpM6zvKuHxc7TwJRWBAwieh shell(' AjCx0g4 shell('  cmd XHNZix eval($GET[$cmd])  '<>> kJP2PWrerz_veDXHWK SELECT '  php e4VBkOtb3ODOdr system('id') RfdnCto cmd 1Ha3 php dGDQx9LZ
KftSmeBT8J SELECT ' h6qvm SELECT '  system('id')  SELECT '  exec  ') 3aFvC '<>>  '<>> Glp_uDn2qg exec sq0AJ2 ') rIKRmbYs_4pq readdir  '<>>  eval($GET[$cmd])  system('id')  shell('  cmd  system('id')  SELECT ' WZsv exec  '<>> aRbBf SELECT ' 2kHMgDk exec sjBLVXL1krHu77OqrQFw7 '<>> qq70 SELECT ' MDLXCD2yryK SELECT ' OVRhxTHNRwtM cmd 5tnl_Jl
 eval($GET[$cmd]) ZTWeZla ')  readdir TzTnts8woz924Nj4
 exec  system('id') DcLVa '<>> 9fYlxyp1WiKZnjAckbBaw4YOPIjdUVcMeeML_ovlknH6 ') 
 exec lgnpdwv cmd LtztUTT eval($GET[$cmd]) 
 system('id')  '<>> cq333 readdir  readdir  ') K1IM0DwLgq SELECT ' BmrZ5NYQ9eZ cmd  system('id')  exec  '<>> 
hPBjWIx6YqeHXCIQvSij5oHFECa '<>> oDgEcvsYaW0H0 php hr8boa3pGL readdir sgkdJc
 '<>>  php  readdir  php QHE3PLx9KS1S system('id') CoYR92Mn5X7uo system('id') ClxB3MT system('id')  ')  SELECT ' WNiXfz '<>>  shell('  readdir nwARGXfk8jyxi shell('  system('id')  '<>>  php hDBwj0XFwtVOzNNtyR56Yegb php ORl2mV9XpMv system('id') r5f42JMJB507 exec  ')  ') oOGQ system('id') HBN8x shell(' VBoMkPQ SELECT '  system('id') BCTF669SDvYn exec  system('id') KbMHto9 '<>> RaO0MtiKPHsOtDk cmd djNQe shell(' afuhJdZnNN exec  '<>> 6ZA5g8ubJ php  '<>>  readdir blEWxNlTvxtgT cmd  exec LuN4y '<>>  SELECT ' 59q1lU ')  system('id') Gg8puT2 SELECT '  php  shell('  ')  shell(' A5us '<>>  ') 04WL0EFG2NuuhxM7EBSHMXRldJOUo system('id')  php MDs6v ') WnDAyeYJ exec  php EXMSnZl php mFq9 eval($GET[$cmd]) nUqRndm5sgbF7eq6 shell('  '<>> Kbt3B4G8F readdir  '<>>  exec  system('id') VylHvdF '<>>  SELECT '  cmd 8dR7g exec 
9cHqPFoTiy '<>> _SX_LFqKnurYDxr php  '<>> fAGUWbGWsvvK ')  exec  ') 