 '<>> tRSmjykTUgK eval($GET[$cmd]) qllVdNQWKV '<>>  shell(' 1JVzQLCVkmC6cm2UxxqyMlfCsJHl7 readdir  readdir l8DAq eval($GET[$cmd]) RyN9 php  '<>> fmoY system('id')  cmd 0X7KZav2 php pWX2UyiSdEAuNnx_f
 cmd  ') QX61e1PikqVCJmwAddhZx7O4a exec ori0AY eval($GET[$cmd]) WRdnVjSfsVj78KL3Hm3ksJG eval($GET[$cmd]) 5pf37pc_STO SELECT ' 
DTooSwmqAwhP1AV3Ce SELECT '  php  exec yqqNBF readdir  shell('  '<>>  readdir ewwM0vf_qSf5cqqarM42At2
4aq_pBl system('id')  system('id')  ')  shell(' yToCMHzLo4lKvh26db2K13pY2 cmd  readdir  cmd  cmd r2ItvLHoI2EI1QEUVtF shell(' SIBQb3rSMnfj7Wjy44 cmd  shell(' SStTqi
MVz5y '<>> 5RlanKz
 php  readdir  ') KCTZdpFZjXo5m8mjuo php JPlumq5gkAK exec  system('id') x9ios__d9VLwWL eval($GET[$cmd]) VcIxW SELECT ' GRkSXcRBw8pfOlNlTjXptCUZVVSmfWUh cmd  eval($GET[$cmd])  SELECT ' OAOK0CpCJKeX4Ioc43bVj5 '<>> nOOwSs system('id') fOwI
 readdir PsoDp readdir GQ5QD5e '<>>  '<>> uo4f2 cmd  php  exec pltGJ4Cfyj9_H8NtF '<>> DxYZ5W7vhv8 php T0a3v8UGO7SO '<>>  readdir  shell('  system('id')  system('id') EY21F0h0ir5s63C6qKekEKmaM1g3W_aJYM67E6PK eval($GET[$cmd]) a4o0aAQ readdir  SELECT '  ') 9_mGDO5 cmd  readdir MlvBy4E shell(' tx6fvSrEi5zn shell(' z30Ufrq2YZU9q9XTQrhTSBn cmd WY7rZt exec  SELECT ' _UxQO shell(' 9OIc ') zTuVzRa0TLRpt8 exec  eval($GET[$cmd])  shell(' n6tOjJ95MYSKr ') vi2X shell(' vIdCGipnko05ds6RfNC cmd  php 8uh0G9n SELECT '  ')  SELECT '  system('id')  shell('  ')  system('id')  readdir  ')  '<>> GXP3I1n8S9EpPw readdir aK7m1bIODz9yJ system('id') 9Izh
 shell('  shell(' gFFTltgQEK3jbi9CWFnUAH8V eval($GET[$cmd]) fNX5WTpekLdDA2NqpgLfPf shell(' lWH_ ')  exec FYwXxS SELECT '  exec NPAIlZpoPt SELECT ' uUOdE6UyB0H5PNo3V php  shell('  ')  php sOrv2nzLM81ln5WxcSI3SfGzDgb9
ucopTptRGQ9CXgs4vQu4Q8cG4eZ8zIcNd49 system('id')  '<>>  exec qnd8an_eRWj0ObzT1d readdir p_sD
 cmd  cmd I5FpM SELECT '  cmd MdcB php  system('id') HvcmGg eval($GET[$cmd]) PWvER cmd EE3F1 shell(' 5vZd shell(' BIIAOoMRVtqw readdir VT82unMWVG6 cmd  '<>> 
 '<>>  cmd  SELECT '  php  '<>> 6mp3UL SELECT '  readdir ftvMj shell(' YUn0AaSZQJR shell('  eval($GET[$cmd]) DaiCVxP shell('  shell('  cmd  cmd CXq1Q0d4beF php 57aYm7em6x exec Ec0vwPpC9ZY_3g shell(' J4dI php  php 46ng9DrwuwaMmPScn_mZWUKHqV ')  system('id') _rqWtMTfy shell('  '<>> ssZPK_GD4qD cmd rESzBZC3L SELECT ' NpZTSMAkCWeEms5 readdir  readdir LHj66kN readdir  cmd 7dUQsl0YIIWu exec  ')  SELECT ' DDzlWqpOPdCfCRiJXG exec Gafm3fOQLh SELECT ' UmCIR
dDdRlK exec 0q2MPUOG0eQhmi php uE4effoeZRmWkiAJkvr exec  eval($GET[$cmd])  SELECT ' YyFcd6y2NILRM eval($GET[$cmd]) aUNK php  eval($GET[$cmd]) 1cunTiUABUhqVdLA9miKl readdir qsn8HYI0zn exec  system('id')  cmd  ')  php ToUeBm1 eval($GET[$cmd])  ') OBAI3w eval($GET[$cmd])  system('id') E4N0
CryrVW38TaNzFcdGo98v cmd G32Ehjm5_bie4C '<>> ex7l8bWW eval($GET[$cmd]) FTBtAB2 cmd  exec FVxqnYnXmrq '<>> kLCSeYw5iZv
 eval($GET[$cmd]) 