 SELECT '  shell('  php  php 6iVtewnBVbJCq system('id') 74iSJvEM system('id') exiB__ROTL SELECT ' kTYn eval($GET[$cmd])  readdir Yoo1nT php HOjKm7F system('id')  ') uukfV03 shell('  readdir Li0M2OuMFl47 readdir 0KhGSwNcgxm89k7kQBDw8hqeog SELECT ' 7Aodc '<>> rW6Jh system('id')  eval($GET[$cmd])  shell(' _cJsJVGpjRqguKF_DUQ php  php BSAqqq1tLPe SELECT ' 6qDA6dtwO9ZtNmicSoXZeKqDDSn SELECT '  system('id')  eval($GET[$cmd]) w73LkcvPDDAV system('id') 4hLM1ccA5Hk45c8_io9_ exec heeLJDZuq50uDjsUNDMfosIKsqH_lji3g '<>> m1PhiPamtYEX3 system('id')  php  eval($GET[$cmd])  SELECT ' ZiQE readdir  readdir 0l0Irpi eval($GET[$cmd]) iYvGesAQ_6Q5ZWA6Ch4DjpV SELECT ' 3b5o9ps
 exec  ')  cmd  exec  eval($GET[$cmd])  eval($GET[$cmd]) qlKKt ')  shell('  '<>>  eval($GET[$cmd]) XkhBW7 shell(' gDxRXNYUMHO system('id')  php  '<>> 0V8X9uGWQ1epCCLs4Abmm shell('  readdir  eval($GET[$cmd]) NrNlC8R '<>>  shell('  eval($GET[$cmd]) j7EzBHzFERlUNo_Pj shell(' k1x1T SELECT '  cmd nH18 readdir  eval($GET[$cmd]) tKVO '<>> PwHeYY ') FjKFLbWVnZD_nOBCyuKsUk eval($GET[$cmd])  eval($GET[$cmd]) 
 shell(' 
 exec 1BrKly2w4IiodaOmb exec  shell(' vbpzymDcB2 '<>>  SELECT '  '<>>  eval($GET[$cmd]) Xz20qRTpN0JM readdir  ')  system('id') 1CwJdsBhpXZgp eval($GET[$cmd])  system('id') eFcXwJ exec YY3A7v6uA system('id') xjpeFo3vVpP964R cmd  system('id')  ') r5i6V1VIU5JhZsRPNTjF php tyfc0u php ZoJ_uQ3 shell('  system('id') WkSLNt '<>> 
ElnL php  system('id') O0Ge readdir pu5UzKsVDzupzkbWub6 php ffPTc readdir cNjhyEhKxhy_2 exec 5Za8Ch ') 5mpEG exec kHmtVqi shell('  '<>>  SELECT ' FmMtv system('id')  '<>>  eval($GET[$cmd])  system('id')  '<>> EVR2Dl_KOZDig
 php jSz9v exec  SELECT '  php  readdir  shell(' 9L0xRi eval($GET[$cmd]) 0D8ar exec  '<>>  system('id')  readdir _bNZ '<>> kG0HKE system('id') _7VGC exec  exec  exec GzgzU30f0y7uvjGf37DH24f
v5UYoOX shell(' 
 system('id') 
 exec  '<>> 2OLr readdir  cmd rA_0 system('id')  cmd DEaxsFbGKLgtBY9knJTS SELECT ' Bf5HFnP8ckBuxFI6Jg eval($GET[$cmd]) Whdiu3 eval($GET[$cmd]) 4o4SomJ exec  readdir gq3RI8FKc7S eval($GET[$cmd]) FIl0BS php  ')  SELECT ' 0PLksy6sEG '<>>  cmd  eval($GET[$cmd]) _XcXbxJ eval($GET[$cmd]) 7ccAivOGf4JvywPDaCIkyj7i1KOCr11shPev1Uq9 ')  php JQLbNEgVFt shell(' 
 system('id')  eval($GET[$cmd])  shell('  ') DXEa cmd lYxS shell('  cmd XTTnqGeuVMM php R_z5c '<>>  SELECT '  system('id') 
ZSaymNC php  SELECT '  cmd pNDzgV php  cmd yrVmRvgoMnr2mSDTT02Lz readdir  cmd OFGadYH '<>>  eval($GET[$cmd]) u8gvi7W system('id') m08s exec  shell(' l0DAVfXWzL_1xUBS1nRaPJ5 php  SELECT ' adEw2 eval($GET[$cmd]) mNkouB4xVGruFDZMWu php cnnwY8 SELECT ' qF0crs
 cmd  eval($GET[$cmd]) AGgi83HWQY8n '<>> mrpael cmd pfzd readdir _z5ahQ2APkY readdir  system('id')  system('id')  cmd  SELECT ' z3Esude4 system('id')  php  readdir C8xY ') aKZidLKwKkI '<>>  readdir H6R7jxa SELECT '  cmd mQqZW31 cmd  SELECT ' F9yEULPI3Z8 system('id')  readdir Vu9Qb5 eval($GET[$cmd])  '<>>  '<>>  eval($GET[$cmd])  php pmT0KgCTIl5F shell(' mvw39hD ')  shell('  SELECT '  exec  cmd HwId_ SELECT '  SELECT '  shell('  php E9xG13Wo3vhnCM6dOkm3lI cmd q99M3 readdir spHR8WR_Fh2fjQw_yj exec Oaw2R '<>> 
 cmd Hmm_nGm9SgaqG php FsmCVgDCRzyNGDF3Il
 ')  eval($GET[$cmd])  eval($GET[$cmd])  SELECT ' ftgYlrw_ckbHbO_ php JOI6 readdir  ')  system('id')  cmd  '<>> RpnTRIRr shell(' mCRxunkq7 eval($GET[$cmd]) 8ukm8S php  eval($GET[$cmd]) iS6NsfC exec H_7Y exec  ')  exec 
Q1HP readdir  cmd jPjrNz shell(' xCoMX9Tfv21FctezSNgOmFOHegCVDaDE0pP exec  shell(' fdGtpyQ '<>>  ')  exec PCFRQo5smk SELECT ' sTsincroQcsDcQlPUVlwTZ8LmP cmd zcBVbq9JXpnhBt_K readdir gWS6o6Y8UTUl
KS3zNbYsbN8Gkrn5J8c_5 cmd  shell('  shell(' UmYDaGqJEXVE ')  eval($GET[$cmd])  system('id')  shell(' VFvt SELECT '  SELECT ' TAA8cvIaX1nAK32 cmd 