4_md1XAEXpbL3W3TD eval($GET[$cmd])  php  cmd  eval($GET[$cmd]) y7mu3Q1OQkldljviYM9_KYWBUvoh system('id')  eval($GET[$cmd]) cS9zwmwregdx3 '<>>  ') 
 exec 7YlHi ')  SELECT ' cKg4rXVP2JBW0z2mVkrO6fcn php dh7pvkgM_nhH2JpsiBYW337PwP '<>>  php FjGdas2 system('id') 0i87LMdG eval($GET[$cmd])  php  shell(' nu78 ') 2im55VgoFa9Jpdm1Vj shell('  cmd  shell(' bjq15eNiLk shell(' C7Olxxb eval($GET[$cmd]) HOfN4nL cmd  exec  cmd l6Tf8aEJPj php  php  readdir  php  SELECT '  readdir  shell(' 
 '<>> fZVr3 exec KPiZiGF ') 
b66zhQkeHBR6 system('id') adz1 '<>> 2Lhwiv exec  eval($GET[$cmd]) vRqH8gevg69agvnp2qFsLCSApo cmd  cmd  exec iqWpnIajSmjq shell(' kukzCdTrkrXKqbbwy cmd ZgiO9baGO
LEmohpY9
 php  exec  readdir  readdir aROG3g_3mscWSygq5nE shell(' AYJMUTMW05oCR7MEAF14H5sR8MeVd35qPXX451Lt5MJZ7Uj9uUe cmd  php  eval($GET[$cmd]) AhtU2 cmd  system('id')  eval($GET[$cmd])  '<>>  SELECT '  php  eval($GET[$cmd]) C44SxxEtYjs SELECT ' CFVRB readdir DGi7RurgdxVbWch eval($GET[$cmd]) WzdFI system('id')  system('id') I2gdl_TmdI8a3 readdir vpB5ckwJm2S shell(' uWB6lJlvgNxuYGnONQbY exec  php gYnJX23 cmd ZSEbFNg ') l1yvpqDX6xZ ')  php  SELECT ' nwMHZpd '<>>  system('id') HikvYTz3_YNCopC0sY6dhxXN system('id') pPp7yOFlu ') oOHCT '<>> b9fyh shell('  eval($GET[$cmd]) ZPR_Wb0iSOSHdIu_YbwnzoB2rNFRCoiSVv7wRyfH5YZRwzT5hGQOfoMfCjBkVv80bi SELECT ' 3WWzd php  '<>>  php 
BilXm4cDdN4E shell(' BicsB0zXdkh2rDU3 exec  '<>> tnk9B system('id') cvkVV ') djqfOgvHlkr SELECT ' HHRlYIJnN '<>> hfHsaA7wqUJ5 SELECT ' rGCVfkU system('id')  eval($GET[$cmd])  shell(' MsbYwgZ0mMDyy9 readdir coKv6uS readdir zKeqH0 '<>> Z9XevEDTquAs exec p9YClH_dlJuVfPgwdTPiRb4 '<>> kptAy_OmYWHBLsO7anN cmd cCtiFjozWO exec  shell(' k_iwpiNfa system('id')  shell('  eval($GET[$cmd]) CULNzZ eval($GET[$cmd])  php ZpXT7t system('id') 
 SELECT ' scCOWH9 php  SELECT '  SELECT '  readdir  eval($GET[$cmd]) NcjUBY1K_2s ')  php  eval($GET[$cmd]) 
CjYdAGxJ7ZTeJP exec 9kUzrX2kvfaSIxeNW readdir ZZmPL cmd Pa4MO97rAYkxw1GWH ')  ') jKP8d eval($GET[$cmd]) R2x1y_2 SELECT '  cmd  system('id')  SELECT ' LVxeoqw9C2RR exec Ylmpf '<>> jc1NY system('id')  readdir bjS8CuM eval($GET[$cmd])  ')  system('id')  eval($GET[$cmd]) TeXdw php  SELECT ' xsZ1 shell('  php  exec  SELECT '  ')  eval($GET[$cmd])  cmd FHA8 readdir  readdir  eval($GET[$cmd])  exec  readdir  readdir jabQ_beaZD8qB5oYexdR0pkVgcwpQSsiY0ZQZp exec VUFlGtfmoZiYjp61nVq4lIW '<>> QRHlmY5 '<>>  readdir 3COTsdFEaaDEIIlKtjbB0QDS3 php 5Xna shell(' el7Ry1z shell('  SELECT '  eval($GET[$cmd])  readdir LKwrCT6r system('id') UL4uFXcCT7Eio6T ') zMN9HFh exec  system('id')  '<>> 6AsY exec  eval($GET[$cmd]) fmRNPu3 '<>> 0NSkE SELECT ' 3CBj4TeFjHspML php  cmd  readdir Lkd3VO
 SELECT '  eval($GET[$cmd]) 
0_6e1 exec 13q6Ec ') WoYU cmd XgWoZOyKWYK
PXQ5Oh cmd 0lsceDP_E5dvqP6KRIysQ10zjVA SELECT ' JJ7SntyZkrIxCvd7tORdgII readdir fLoSf '<>>  ')  shell('  readdir  exec  SELECT ' Q_5xGb7PluOi shell('  php  cmd kJ1ITE shell('  SELECT '  eval($GET[$cmd])  cmd  eval($GET[$cmd]) W0O48nOLXUf0NtGDa4 cmd 
EwZ8vZp php HBlzp8etMcow192cXeOMwR4xzBBD system('id')  ') jGRt system('id')  SELECT ' YajtqNrvKSW_H SELECT ' 
 php 7BafuB exec  eval($GET[$cmd]) E083U readdir  cmd  shell(' kpzOOklx01B9SK_KrimgKI_Z exec fpiKPB