 cmd  exec yXIb php  SELECT '  php  ')  exec 6EDuSympx4wBtBchRkE6Z php  '<>> 
 ')  exec  cmd  php  cmd  eval($GET[$cmd])  shell(' aXwsvpYHN7gY_E5b0fhxwQ0m7Z php  readdir  ') v2V23J3VVmxMdVtkMd cmd RwfQbQq_BOwZTr00aYJ system('id')  shell('  exec iWN0qrti2xnkGogJOowpWgmOq3aBh9VV cmd OnZHooecFc ')  exec  '<>> 39MqNHK5sIcwMfpsi9ZzfBDN34tj readdir  readdir  cmd  '<>>  cmd bi85 readdir  SELECT '  exec  ')  readdir z8ey eval($GET[$cmd])  '<>>  shell(' T3f7c '<>>  SELECT ' _bTU3Uma2DDkWVSu eval($GET[$cmd]) LJug59O eval($GET[$cmd]) 9zxQkVZEyVuOVK3ci2BW1IJ2h544t0Qjkigo '<>>  '<>>  SELECT '  cmd  shell(' 8aDgpRVP24E '<>> f2qYueB6Ksi2P5S '<>> LRBg4kMowi2 system('id')  eval($GET[$cmd])  php ZAMcSPR3nKSCdRB35rCP7IOHaE06 php  SELECT '  php RNwW '<>> 0HcTvG0xlJykVWfqaWbKpEYJN eval($GET[$cmd]) a9bWf2Q0C1i1w system('id') 
JhJhy_Ji_I3
YqlK5 system('id')  system('id') iRYUfiQHW php ANAGs
3OkUBlY3DtL4TK system('id') KF9T8cC php  php yu7nELm8ZS_l0W system('id')  '<>> IQ5k8 system('id')  ') 54k5PwN shell(' 
 ') EWjDkT readdir  exec  system('id')  '<>>  php  cmd o0blEB '<>>  '<>> sRZmN3aCJnLE php M_bc8q readdir Y_Jo
 ')  php _tFUb exec  system('id') KssqivGQAUAwNz0Zti ') _jnRQtuNSEPM SELECT ' 
 exec  system('id') mB_DfMGEeseWfFJZWbu eval($GET[$cmd]) u6NZeAsV54QL3QPBtzKZobmXg6yR
ySHmbnj28g system('id') wo6F readdir 4kTu784dL3z0CBF SELECT ' 0A16aYreywLJjxLuxIjcME4YBwU ')  ')  exec 7WAusj6 readdir  system('id') 4MISp053icCoeZIKA6bo SELECT ' hRUX01Ai9_5FcOvkVKmVOx60 SELECT '  '<>> BLumhThXPu shell('  php  exec  system('id') fO0T2PkjPLaus1zbUu7nd5zG7o0nf2HX6 system('id')  exec mjRL71V ')  shell('  shell(' VQCtgKmmzL8PkcH1nDl1 SELECT ' g0nV exec pMbTWl system('id') okLK0g7JZUqA system('id')  php  php  SELECT '  php  readdir  ')  SELECT '  ') 
u8PqxX php w9iYui6trM shell('  cmd  system('id') JKPeq readdir  php zahh SELECT '  exec EiQkrvYkmPo '<>>  cmd  readdir 7hls exec  ')  cmd 0Ndxxx exec hlAWU6YWiPZP3sswaJ cmd  eval($GET[$cmd])  '<>> QbQ2p eval($GET[$cmd]) hCx6I87VDZSjyBmVxp SELECT ' zn77cJkdphJw cmd  php 0tug SELECT '  '<>>  readdir  shell('  system('id')  exec oDGi shell('  exec MXTFIMzMjh