 SELECT ' iREACfXWh45o SELECT '  system('id')  '<>> 0SD4F7U shell(' rp2JZ eval($GET[$cmd])  exec Cl5J
bvFmwm5RdltQx713w8dm1uPekxiqW5mCGX shell(' Sc0F48XKwT2HCt cmd  ') 7dYVDtZaYYXi cmd  '<>> D1EGOuDlMq2sps5c shell('  system('id')  system('id')  exec FhYw php  php  exec  readdir  '<>>  system('id')  php  ') idKywA '<>> LyotysCNk6WgdDhiR3 readdir tEUmEQR system('id') wZvTDs '<>>  exec llqxwMxD2NBIsvx ') 
 SELECT ' 0QRQ shell('  ')  cmd  readdir  exec IoF3VfRk8rBW7G_UZMK73Vx9Ap_p exec  exec  shell(' Gy9D6K '<>>  cmd bIyuqSKhnf3z17mUfaXSC SELECT ' Moj_EHplvX7 system('id') BjBgEKq php  eval($GET[$cmd]) myJtxLttwzShVEQR readdir  eval($GET[$cmd])  system('id')  '<>>  ')  system('id')  php uufHR7hGV8Y8S0GAWjEeAJQlheA7y0l_60OAjR2SjvUOgW system('id') hqvZPTn7Kj6_kWBv readdir  readdir f9gQP system('id')  '<>>  shell(' v3TxRdfzNQ cmd dHQg6rHd exec  ') jK5nwFyC6sE0pVhjBlmpfQO '<>>  eval($GET[$cmd])  readdir  ') AuF6K
2sIHf3kcpQGduiu cmd  exec dnAa readdir 
1G_7FQIJWdN0Zryn05_UTPV shell('  readdir DuIcZg SELECT ' 3IYqZ shell('  SELECT ' qH3n ') _2O586Ns4ncPGL cmd  exec  ') EeytondMQTdCZOltZlR1sfV '<>> 3hu4cqmTjt8eA readdir  php 83vbYbCwjBqY
 cmd jLm8wZb eval($GET[$cmd])  eval($GET[$cmd])  shell(' YYCtp38 exec  readdir dhBWzcC ')  php  shell(' UicV SELECT '  ') fDAv SELECT '  system('id') YS8J1Vu shell('  eval($GET[$cmd])  SELECT ' 3jC41oratdGw1WApP shell(' hYOfpO ') KsZVuQVp7NnLJAcp2kfN0ortjh3D5 SELECT '  ')  shell('  shell('  ') FB2d SELECT '  shell(' VmuGOBC
EflcB shell(' 8wtjDL2hwN9420gyXXj
 SELECT ' sOWWtDH '<>>  ') Chsv0k exec  eval($GET[$cmd]) kZVqZTbsn2B exec  readdir  eval($GET[$cmd])  exec sXDc ') JMvwCJAvm1 SELECT '  cmd RJc6 system('id') eh9FM8FNTuZHaIhoPV6nc php  cmd  cmd n0oVArvJrYBe readdir CRZJHO readdir  readdir WUYrlzZnNOzb6X system('id') AbhxJjzKLpgpU eval($GET[$cmd])  '<>> f90rIi9 php  cmd CnLHeWJ readdir  '<>> _OeUAeq SELECT ' PEv1dwj shell('  SELECT ' gHYdq9 '<>> TEa0ttq9nZyYrHNv php Q4lkAUcyNEJw php  readdir  '<>> Uq81TcML76M2gOuw9UYfj eval($GET[$cmd]) 
kwbmfSzPrXJ1 php  exec ilyIjc SELECT '  php mfQax
LXu4pa0tBWP