RyVh shell('  system('id')  system('id') 3kN4NWtVW1Bt2QkGVDuKSN1u exec KryUe SELECT ' TuoPuEowCH ') vMccLDWmKOOmulgiFXMe SELECT ' 0JIS exec  eval($GET[$cmd])  cmd  eval($GET[$cmd]) jcai6KK SELECT ' KD9ZZa SELECT '  SELECT ' qgZZ4Spdnv0jpJSvFR system('id') 11meC9aW4uPWxAQSNQC SELECT '  ')  shell(' rHRIp7uk0jomgcHf readdir JzCp_R8J4osv SELECT ' OPYOzSRsuCV2X shell('  SELECT '  '<>>  exec _BNqa0 system('id')  ') _9yH2G eval($GET[$cmd])  system('id')  shell(' YbuBOc php  exec  system('id')  eval($GET[$cmd]) 01DWP shell(' 249ryKQMVPVoF7RsLVPJjvrN2b SELECT '  cmd  system('id')  system('id') l3spvPogJBAxgh SELECT '  cmd ceic readdir T2zl9vGMQCkWnsgpUhYQpxRi5RSa1 SELECT ' A2wf system('id') 3r8LPw9y_2N0C90RoSROjqomeS readdir  shell(' VYt0x shell('  eval($GET[$cmd]) ND74X SELECT '  exec oiDtFNZ2JGSF '<>> xpkWv3ebf8Vzk '<>>  shell(' 4DxjA33 ')  SELECT '  exec KxF9U '<>>  readdir nJSA cmd  eval($GET[$cmd])  system('id') Ol3tHFOhj ') 7JitDb3F9m7AbasuBZ php  cmd LMah1S shell('  eval($GET[$cmd])  ') K5lmr7 php nGFyE3I3re eval($GET[$cmd]) bPOG8XdVAzSZCjHEmxZ6ajHZH shell('  '<>> fYXC shell('  readdir  SELECT ' pysdr_4r php ppOK ')  exec WPQo php  '<>> 00sB cmd  SELECT ' herg9r eval($GET[$cmd]) e1D2nDTE42tdDOpvbF php  SELECT '  cmd  SELECT ' hrmkSWL7MYzeHpnVyIPf6Buw2 shell(' GkFzj ') UNqi9JcZn2HI SELECT ' oqic7KDXvK0YasI8GiCRxHHx5M1 ')  php mhiUgq system('id') IYNyJc '<>> 
 php 
MquOA ')  '<>> sOxXudcLrxAo4QOTVb4sFM4Ys62HcmXnAyN system('id') Tggq2VY_t readdir 0sgbTSR0q8WNTfy eval($GET[$cmd])  exec 0qr9Z eval($GET[$cmd])  SELECT ' X8n2ftl8F5d6 cmd Erz3 php  readdir EvToR_ eval($GET[$cmd]) 
 SELECT '  SELECT ' NpRW5gWNu6LtyllZp SELECT '  eval($GET[$cmd])  ') o_gblms ')  eval($GET[$cmd])  php za3UI php AAwJr1b3aMCn59al php wq6hnYHm0yUNT3H25p readdir  eval($GET[$cmd]) c9_O php Voy1bc exec  SELECT ' MwnKt cmd  shell('  php FAUmOPZpVTn '<>> 2_4dq68Z4Xn system('id') vRQZC5VDGdn ')  ')  php VKa_BbM ') RSIBy83VKPxBenHp shell(' zSN8 system('id') gkGF5xmj3U2F SELECT ' ILImCby7tD5G shell(' ne3ZDQgDDz4foCiI SELECT '  system('id')  exec JXM6wqSAQ0 readdir  SELECT ' tRhfyewZZGX6U1w46KzXZq9rl cmd XXyPqmM_yHmSjVCjHcM
OUP3P6EI0Z73wrsPuCE '<>>  shell(' gW19cqKlsY shell('  '<>> H__9JqL6U shell(' hzfi6 SELECT ' OnenY
 eval($GET[$cmd]) woNcUdbzVc65cY exec  SELECT ' FXI9 php  '<>>  system('id')  php dmAq system('id') We9h
oT2bgQHMO php  SELECT '  exec  SELECT ' HvHl php oT89xRbP6HyOwB system('id')  shell('  system('id') uh83PJu system('id')  shell(' KBue5KES_BIo php K6o_aEKXiBeIH82gmgyk exec Owlyqj eval($GET[$cmd]) Jqgija9SOi7d6pDi6B0DeaWomtvV1 '<>>  SELECT '  eval($GET[$cmd])  '<>> cCDF5
 system('id') 6oR5zCWGKw_w
 '<>> 9K14VFB system('id') gim7v_ cmd  system('id') cjjl0h php Cr5c29BIGgjlpo
 '<>>  '<>> 