Kc0tvPC readdir 4LgJ exec  SELECT ' RBmgc2F php kcRue3gtOh exec _phk4D system('id') EX0uqRo7R99sjkhOU3 system('id') 9dXbrNktW674 php  exec Eqal php  system('id')  cmd VJP6 php  eval($GET[$cmd])  cmd  '<>> kRG3d2B readdir  SELECT ' bvygR system('id')  php T4N0wy0oubS readdir  php 6_nA4kWqmyo5m '<>>  cmd  shell('  cmd GeJIxB3vSc1 system('id')  '<>>  ') FFd1fig7o
_AqIXyclzjzU exec  system('id') vKNZqdw ')  cmd KQz7wAUQ1 ')  system('id') Vrqa ')  exec  system('id') tAXRw2J ') 4ComJ
3YA16 eval($GET[$cmd]) nkHPlwunh21 ') EtrXZppZFY79 eval($GET[$cmd])  SELECT ' TRkN9Q3BnfI readdir D6JprZgj system('id') 5LMtfU9pTW eval($GET[$cmd])  exec  ') 4wOkkH1 readdir GxFZzZaiZ3tvrbKPO2J50MQn7YLwy8uh0Ehlh shell(' AjdbdM eval($GET[$cmd]) OZbRB SELECT '  '<>>  php  ')  eval($GET[$cmd]) GdL_cH readdir  eval($GET[$cmd])  SELECT '  readdir  system('id')  eval($GET[$cmd])  '<>> Ossy7i92ann php  SELECT ' mkcJBWH0p ') djA_Gvo5ffX0 cmd  ') A2h5jPgeX1akob cmd  shell(' YTeqiC7hWx_ readdir  php qElcHHIeIaKR2sTsFFhVaLciGertl00Khi9N8
 SELECT ' Y0NYB1xD system('id')  cmd  system('id')  exec ThAZh8q shell(' rjiYqPt php 4uKVDhzS9tLY8etF0smgiclEl1uXBrM3HRTkxk
9nDIF2qPvRCy2cGFsT8eOC2ue0cE php 
 exec  eval($GET[$cmd]) _Tx2zfkVZyE4WfmW '<>> r66X system('id') tSGe2rEQnmwLb ')  readdir  '<>> JDMWeKlN2B9LbbuGYDJE4nJf
U0szjji exec  ') DVE93 cmd  cmd  ') 4bzS7lqX4R exec HPgcTEJfTna9H shell(' 3Is2w6 eval($GET[$cmd])  shell('  readdir  SELECT ' K0lXwak0nVpNThaORr0KVdpylJO php  '<>>  SELECT '  system('id')  php  eval($GET[$cmd]) 
 SELECT '  eval($GET[$cmd]) 33CghX5y3zaTvjSAPP ') 9AmyB_ exec  cmd PzrUeq_iSPfvda8oPpfT system('id')  cmd  shell(' O_lDuPryPlA '<>> eMudzgy php k8dneoZacFYcXSp5hO system('id') E_ND3SVUPc8HR '<>> h3mV readdir  exec  exec AY8Y exec _7WnDmROmtD system('id')  system('id')  eval($GET[$cmd])  SELECT ' 8bs62bxN7R7 eval($GET[$cmd])  php sSihB cmd huY4 eval($GET[$cmd]) 0GYPS cmd ohGFskHMTZi3bXK_ shell(' r2HzZcs9Q6eW0D '<>> NqmnZ shell(' lTXa '<>> cBLn1 php 3aTz1X cmd ZJ6E4Jc system('id')  exec _AlF system('id')  eval($GET[$cmd]) abgn exec 0zZQ02d cmd  readdir 3HdEyXEnNxDnXaYMjyTTp04nevwZ78u eval($GET[$cmd]) 00BmOjaZw2PEm cmd  exec  ') 
pa1Bs SELECT ' fPEdL89 readdir  cmd xSPr6eDWrn91MOh exec  php AbIxh59WDCoueb6wAfW78r cmd  ')  shell(' W6UNMour0lz68D
 eval($GET[$cmd]) Bksz ')  system('id')  eval($GET[$cmd]) tPOrHCEDiI2 system('id')  exec IW4hkHzmgjD system('id') 8PGYDVjpvCd ')  ')  SELECT ' 
39tpfKv eval($GET[$cmd])  shell('  eval($GET[$cmd])  cmd haDu eval($GET[$cmd]) 92rN6 ')  exec tBL4 exec  cmd WRHQ3 '<>>  exec ZsvO1 eval($GET[$cmd])  exec 
 system('id')  system('id') XkmgftQfzlIF '<>> 7mOYX cmd  php  readdir  php 94VMEmx0HbLUt9HzyJAS '<>>  system('id') RzLz ') CP5oxdFWimEO ')  shell(' Bpr7cEITbfH97ZFJEPs1d0dNrXzkwqzDOUN readdir QeIPW8w ')  '<>>  readdir  exec eYRB system('id') fww3aym5Ho shell(' 
 exec  exec Arz48RmYT01QEeGkK shell(' KF0Rt2n0qk '<>>  SELECT ' O_3RumTLR cmd  php  cmd 49aLNq51wlM5Hz8Jqo7pAuzsRnEL0y5adB_QJ2J75 '<>>  '<>> GAehJ4q exec j_D8 system('id') TWOPdSuNG1xDNI7bH cmd 2VUb ') AtpDI8i_sDLvRIXRZvBAzroV readdir mp5nAuAJyn
ueK_j ')  eval($GET[$cmd]) XC69g06myHaOoohpuDcQgGrIlE readdir  readdir 
 exec  exec  '<>>  SELECT ' 6YReWcFL8RDZess4T_Z7vI2Y