YrmIf exec bymN ')  readdir  '<>>  eval($GET[$cmd])  php  '<>> a6pPRbZO5aqXx3edSE
29qvwBAGgq8 SELECT ' idjvg readdir  SELECT ' TqFCsP9zPQd5rjR8a2zqt1Nz6VoJ1m php V1cFVVq ') 70JxfG50YjB69AEfaPMb SELECT '  '<>>  SELECT ' yxKwZAN exec Mm8_U9w_O0iBIuqYmRWJ shell(' se6U75c5oDZEb php LdnKMRpEC_ ') N0VGWKl0THmG3uG_GYT2qjJ readdir oEXJ exec  SELECT ' z7bip
U0OFJ system('id')  eval($GET[$cmd])  php  ') 
GDy7BQnwOJhRV readdir  shell(' P1psNF exec aE9gys system('id')  '<>>  SELECT ' wBwYqik system('id') WSgd1C2juJy0QT readdir  ')  cmd OULftA3OuGIPkC15BZWuUG readdir eFc3xxiYAkO system('id')  eval($GET[$cmd]) j8Bmm SELECT ' PlEH8TdjtqJ820LQuENcYIueU '<>> FBdDtf_rngIk4vs ')  ') 3m3H7VgKR2 exec  shell(' 7WS2e shell(' Yzk8hP php  system('id') CCSCy SELECT ' wqdJ '<>>  '<>> Ik0EHaRui77y15zRzBX_WCc eval($GET[$cmd]) b5I1xIV readdir  SELECT '  php BuXtOrf php  '<>> iw6UQsM82Jz8hsnKFJpMp exec 9w1x readdir  ') 6chwmr4 '<>>  readdir  '<>>  exec Dt_5k SELECT ' H7wo3x5 shell('  ') hWi1vg eval($GET[$cmd]) Ii9YrV eval($GET[$cmd]) cItKMiX76JYVJV2dSdGyD6UyDq system('id') YCyKYe
 readdir  shell('  shell(' 
rA3tZmn7mZW_ readdir Ifj_d_ ')  cmd  '<>>  php  SELECT '  '<>> 2LgfEiH0BYs0RN cmd WvC6Kn1huUQtkAL cmd FMMXWGactEfAERqZ '<>> ca6v9t readdir NccGz7 SELECT ' 
 exec  readdir  php  '<>> MOFkQXInRkCWip ') POa6Pl cmd  system('id')  ')  system('id') IRLHOTTJYs5xbg2 php  system('id') 0z0ELkhYrh7ce7N28ePU2aFVWjzrYWH8_ exec dl_fA exec 
 php  SELECT ' f8R8nrAohBjT2L php  readdir  cmd  cmd  ') 6puGJqgFE cmd  cmd  exec 3ATpowBqE exec  readdir 9Mi8Oki cmd tJLzA eval($GET[$cmd])  cmd  SELECT '  readdir kSswWpPO php  eval($GET[$cmd])  exec  eval($GET[$cmd])  php  system('id')  php  cmd 6W8Ygm shell(' Vzf_VbNMCQQ2pYrbFS SELECT '  php pM3F1Uo cmd  cmd fqcIbx7RxfDzg system('id')  SELECT ' oQPQ ')  shell('  cmd  php  system('id')  eval($GET[$cmd])  eval($GET[$cmd])  ')  SELECT '  php QQFpCE ')  exec  shell('  eval($GET[$cmd])  cmd  shell('  readdir YJyrcXNmfVa ')  php jbKgLb system('id')  SELECT ' u6EaV8 readdir 
rFvxP_WuXz cmd  readdir smdF exec  system('id')  php JmGlF cmd JDcVaqnGQIDqVGW315UU eval($GET[$cmd])  shell('  exec  cmd JDevXV5gvl0FlGQWa eval($GET[$cmd]) Zel5HD_ZWTOSyX eval($GET[$cmd])  php yDpobsxsii5k exec HjkfwCYDD5YaBuWC ')  SELECT ' r9BkvZZ '<>>  shell(' aIlyXR7NrHTKi6 ') 6VKtEfy__H3TssepV4bV2X7Z cmd uK9AWx52iR_FT91l76gIgXQQaX5GGVo9cM37FTJK2 ') mK9bNgQUzX7N7OsSERgeo7DyU exec 
 shell(' fG7c75KJJp eval($GET[$cmd]) 
 '<>> yjJTomI eval($GET[$cmd]) 93wl
0eBqJPnseJE_fUHraeJe4 readdir B2xi
 cmd w4yyCX9FVGTG6bkwbBdgARivU9a0elvv5 readdir  exec  ') nwIjZaY5SC shell(' x7t_2pw exec  ') l2Ubgg7vku0H3Or eval($GET[$cmd])  php Ke3m exec zOGdhLzsLiBB2Dxsb5BPnnhYQCxsJkWZh5RzBba8AspNNJqG2E16n ') hRKIORYr3t_55KAi4AowbOBny3U '<>> CJQJs ')  eval($GET[$cmd])  '<>> 
 shell('  ')  system('id') XXNteW
eVO1R '<>> ZEIBilldA2Ly3g8o system('id') q1KLoHWX5iwGtYy_ic readdir  SELECT '  shell(' V5G56 cmd AqhQ shell('  php Hb0cBUOjtXpTVSpBy4YtSk03yPoB7OqGLAQQ5wGo '<>> FYbjgfL5UwoSv243I479wHf0 shell(' UtyPY8rC7n system('id') CVhbCLhPN7y ')  '<>> Yv3WtqomkxvHU '<>> qc5gi eval($GET[$cmd]) bOZcx1xOAH0w system('id') JXs8MilVTXQBotVr SELECT ' O0jQ shell(' 
 eval($GET[$cmd]) 2MO2W2i1SRzrO6 cmd  '<>> 2Z6URPyTWJahvxrsW system('id') uDJVW cmd  '<>> PBh8Ex ') FYxafy cmd  readdir WSHod2
 ')  '<>> 