 shell(' TlhUXUX system('id') 
 cmd  readdir Pk0EcgnQ6 '<>> Et8H_THqXKQLoiqPgi exec AEhX3X exec  shell('  '<>>  readdir  shell(' HI9JUA8asSc readdir r3TtFm8iGRxDqqRWjDOl ') ZUOY7RSlD8cOACZz1C '<>>  cmd VRF2KNulsDz5M exec 6XO1juAPkGOPy readdir avKONu SELECT ' 0QbSkjFDCaN8N6inbQ ')  ') __fZK '<>>  system('id')  shell(' KnC3M readdir  php vZP9M_hF0DJPNG6zpDjTNzru cmd iguBxNPYC8Mb
R89Cqg '<>>  php  eval($GET[$cmd])  exec  eval($GET[$cmd]) 3zN6c '<>>  exec 7pi1R0RdKyxEsuwG8hZkUcc shell('  cmd zCfbyc SELECT '  '<>>  system('id')  SELECT ' ubOgy readdir xHsf cmd ZKuq6_7BfBD0I exec WIRjdFNkPyuxzra cmd 6s2tJ eval($GET[$cmd]) DxL43A ')  cmd 
 shell('  system('id') F0Sok0BUxrghEm system('id') xjOLHo2IBZW php Gvo6f5eWF1RnR ') 2Q5n
 readdir JRD71IqrRR3nXt system('id')  php  eval($GET[$cmd]) qKHHg readdir  cmd  exec  system('id')  php 3P7RPWG4NPs ') EwtLNgTBZAd2bp0JvvFNTkzFg
v5HQwc6 SELECT ' t6zmNK4
05MMn0F7eZpyt1o0ICodEPKE php 8E8MX ')  SELECT '  shell(' bvcvr2 cmd ExVTkO5GTAxC0hfDqw cmd LneIz cmd  '<>> ec_0IGR system('id') OCCNHh system('id') 9rU9gzjPhxlcSbRIQlD3BU_am
Jp1WNgLtR0u9DX2DvodAGMYmJ4DQ system('id')  exec  '<>> QYw1ycqbwN_Op
 ')  readdir BEWVi8jraGxgH9fiUG eval($GET[$cmd])  eval($GET[$cmd])  readdir  cmd EFkZdu7d system('id') kmLwva_7K0SBVae9oGwD system('id') JIgvJ59z5EnOTB8ZYc SELECT '  php  SELECT ' doC9Al0 ')  php c4XFmFiwIAQmJoECPg exec  exec Jzcg php zSfFKCSAZr4 system('id') U8TVrj5Qn36
 php 7ZTViLPjHsK cmd  system('id') _J4KJOP0U3gt06zKObl6OC '<>>  ') v3JnRF9ZS eval($GET[$cmd]) Z5f5TzwmWJ SELECT ' 38s4a2 eval($GET[$cmd]) ckzbX5WuZB shell('  '<>> Edpqy3mTXD system('id')  cmd 6P10w ') r1YcvlKSNYTF9oTp0Gk4B '<>>  ')  SELECT '  eval($GET[$cmd]) 
bX1C35 system('id')  shell(' 6_5BzA2ONlwUqQJ1 shell(' Ua6JCk1pa ')  system('id') hwQIJ eval($GET[$cmd])  exec 7t4KU system('id')  php CPS0Asksjco exec wjE5bVPkdj5e5UAFWFoub79z4i3kWVCP8UY system('id')  exec ZUSFZSQ SELECT ' NMiGjQdaicY shell(' OzzZBRMDRorXmJ '<>> C9ZSbmeYccVeUih08kuVZC20lF SELECT '  '<>> MM05JNxbTW7qZmNrjA shell(' 5_fDnd '<>> eRztkytooyc9 ')  ')  system('id') QYDl system('id')  readdir Yf02LkWurKk '<>> 8nkMyL '<>> QCHNgPn ') Vk8BMVNxa2XDpaJxNsIhXLO cmd  eval($GET[$cmd])  '<>> RZKWYMZRboDBYhfviTUU4 exec ZjpUbkLRoxldBZ3k2 cmd _cyg exec _1xmJ7JOJ0g system('id') 