Gt5qN '<>>  readdir  cmd  php  eval($GET[$cmd]) skVEtHttrh readdir uNfP3 system('id') ASunnZd1hcDRO58RY7Aw system('id') aRWt8NzcJ eval($GET[$cmd]) yXXEftjJwU8hntaHm2hScRz4f '<>> 9mCKvx php  system('id')  '<>>  eval($GET[$cmd])  readdir a3r5wptIv6a readdir g_qTiZ9nXndgC '<>>  shell('  cmd FXrpRbuTzYQgF0pDN7EKcg7sAbC php  SELECT '  eval($GET[$cmd]) B1wy6Q0gKJ2fz1bNII8Ja74gKsyzUgR readdir CzT5uy5PHxMfJ9iMKzb_tTCk2gq exec 5d34EkZuUTeVpvGnvG6sTAaLDPvTVPAFriJ6_ '<>> 2jP2Sgvj9R0XLX7z exec  php svYXoSyzW0hWWmcKz shell('  eval($GET[$cmd]) g39j3h6dwGtKrJckJg67fFE14Ev0DIOPtWu_aY0 '<>>  readdir  cmd  ') hiSnXD_mz48lHtyxMYE '<>>  eval($GET[$cmd])  SELECT ' H73DsjL_tBsmtGmmew eval($GET[$cmd])  ')  '<>> SpJm1ipp8WvuY '<>> v9dLNH php  ') QKlPEE readdir kIND exec  readdir iNk4iwQ system('id') dVo3o0LpJlFg06t5VkW3yHg1d6lpvPLt1XZgYyQF9 shell('  '<>> v6fJ6bKBfDj2zL52C4D readdir 3Z0oK cmd mf6YW php  eval($GET[$cmd]) M6Z5_9 shell('  php w3pbiq_jQrrshgTTOEI system('id') _2lOcrDTP9 system('id') 4t2T readdir 
 cmd y1hmg4fQvSA readdir  cmd  readdir 
 ') 053_7E '<>>  cmd t_g8Ol readdir  shell(' R53GLj eval($GET[$cmd])  shell(' w15c1qBOr0Y38pz8A system('id') jtvC SELECT ' 6zEf57 SELECT ' t5RZG shell('  shell('  '<>> QTJA6DyTC1xwDPdUwV php pNIyjgbnK2NB eval($GET[$cmd]) 044vU5dUNXbmC readdir tcJO eval($GET[$cmd])  shell(' ogHU7z7Odbre system('id')  cmd 6MEGMYQvK4Bg php  readdir eayQj6FZosK_ ')  readdir QkHefHO3cYlwZ9ZgN3Ho1jor7FwAgK9W8aD7UpJzKJC cmd  SELECT ' 3dmk8I7rWDybO ')  cmd  '<>> lPY1 exec  exec  php m2OcTG cmd RQUMf0_NP eval($GET[$cmd]) tIaCqV4MowLl4I0Hwylmuip system('id')  ')  shell(' jHREX shell(' CmKulS_Zd9stev php  shell('  php m746U9WGf9Lcvuzck7MJax6TdQop8Q2h4
 cmd 
F2Z95t SELECT '  ') olfi0V5nEo8wZd SELECT ' dT8T9afYyNkgP0 system('id') r9_EQ php YZXO '<>> iuXN6es_WlPs2LGsE readdir 
 readdir  cmd  cmd WvugST system('id')  eval($GET[$cmd]) IEiPuR4 readdir lws5wSlS php yH8K ') 23Uw readdir p1TtBK0rcaxGJ0L exec kY7WBdc php N5Ydb2A
Uvwum readdir  eval($GET[$cmd])  system('id') moK8_IT SELECT ' nqkfkRK4BUg6bRPBp8 exec GijQ shell(' r9bH1d SELECT '  '<>>  SELECT ' uvQ4sl
 system('id')  readdir hFhVYa_AA8H cmd  SELECT ' xOqkBAw5wO8QyHC7 exec  eval($GET[$cmd])  eval($GET[$cmd]) SaGBY3I cmd B5pi eval($GET[$cmd])  readdir H_23y6dQRMpgN4xHk2_1e2 ') Jp_clm SELECT ' t2dph1CiNOtg readdir dI3Urt7u90mhP1qaAyTkMznkGkRKnm5pMUHWo4nMIXDsL_fwpQMUXRgb9G24Zm2 ') PMfNIH5oWgsNBCAOSWhADt cmd  ')  ') 
 readdir  exec o2cF shell('  exec  php zkVXoCNKL1 '<>>  '<>>  exec oCJq SELECT ' DqoUX2 eval($GET[$cmd])  readdir 7Y84GmoKqF eval($GET[$cmd])  SELECT '  cmd  readdir upHUAJaSWg3Cmvp '<>>  eval($GET[$cmd])  shell(' 
y005z system('id')  SELECT '  SELECT '  readdir G_r37Xt eval($GET[$cmd])  SELECT '  cmd 4TPsg8tROMKUleoZNZPAg cmd  shell(' gGP_PZ readdir  exec UrPg php  SELECT '  SELECT '  readdir n6M8Ip system('id')  exec  SELECT ' CAzL exec  eval($GET[$cmd]) j4azDF SELECT ' r8lhw SELECT '  cmd  SELECT ' hosTP29DtAOUh exec JTspV cmd  SELECT '  exec  system('id')  cmd 5eY2AB exec  readdir  php  php  SELECT ' i6JISuGNFXSjQGLXaSeLPElnoTIo6NW_ cmd rlPDS5anpT5jAi ')  php  cmd  cmd  cmd  readdir 2dpL6