 SELECT ' Gpi7IOMO1j eval($GET[$cmd])  exec fS6uJok system('id') HPw2X3iwp2 system('id')  eval($GET[$cmd])  exec 
3riK eval($GET[$cmd]) dMWKTMp3pL3hK9B8mI system('id') bmpSew '<>> XHezLta system('id') GSxd6X php TtHLI8h '<>> 
 exec  cmd  cmd bOPPuGJ9IjMpj6nNxRcXKuK4OYRtrHNg SELECT ' _hEGst shell('  shell('  shell('  system('id')  system('id') myRc_PoTX4BMjYvrQeFzGT7 system('id')  eval($GET[$cmd]) TEInF shell('  ')  ') _AkJ6IV cmd  exec BoRuIqK exec  php WRltp readdir heo6Vbw ') 6JRh SELECT '  system('id')  eval($GET[$cmd]) YJcqzcHNt php 5ZGF_vp exec rnz6aPk php  ')  '<>> NOCZ0ylIcYQ2vWx2Vi1L '<>> m03Fyt1wIwqIF readdir  shell(' QM7rrn3uEXaxmo system('id') ChS0srg6rFtJpV2v8u php  system('id') Kab4RhkQk cmd  cmd ZsxW8Pkda cmd 2MmrsJDqruERBpPdnA5EQIi9uDMqlvwA php M8zRnP4Q0gyCxXWda2qCn8CK system('id')  eval($GET[$cmd])  eval($GET[$cmd]) DelorMI ')  shell('  '<>> 
 eval($GET[$cmd]) 
TqT9
 '<>> FfTDIs readdir  ')  exec EfYqZjTyL exec  exec  php SDg3 readdir uNcs
 cmd  php rRpqzp php VPACi '<>> VeVXp612hC1 php 4JUY '<>> _sSaWur eval($GET[$cmd])  system('id') f0LeiAt_mMj exec  '<>> PtpT exec  system('id')  exec  shell(' SHcmyAjGMIE88qfakZUsHaRcNOsVjFdagfgBybiCmP0IM8xBi1GwVQsTNChZpP5N php OGb_RE_gulSHs '<>> ISg0R7wPaya SELECT '  SELECT ' v3Rg3O exec  ') vgl9l readdir  shell('  '<>>  eval($GET[$cmd]) F94EBh6fZkBLIcvLdysWwVbo cmd  php  eval($GET[$cmd]) 2xVEDT7qQPk5UG18 ')  eval($GET[$cmd])  '<>>  php UY5t readdir  cmd MF2SHMQTwdUPmT system('id')  eval($GET[$cmd])  readdir Nv__tqcKWDm system('id') RBiw63pG7Q8WsW5OS shell(' Ar0KjMJZ8MC9t php  ')  exec  php  exec  readdir  '<>>  eval($GET[$cmd]) GaZ9tCO cmd cSptxt system('id') 80wNmoEdmvo4zrjgXN9w exec  php RmkgJIxMIxr php ohSPIU exec 2yS4U eval($GET[$cmd]) zjlbQjyMA php kQWLWjIw5fP0iG cmd 
bIlH1 readdir h_rkf readdir wGM0DM SELECT ' bBiZBkzv_ php  shell(' xfBjABbCrH cmd THG1vM SELECT ' KLI60Miy7euG0aVWJM6ve6iu readdir  exec  ')  exec gN4XniKdJoMOeEUb8CUKEyiV8tLm_Q '<>>  php  cmd 1GTiAMl9xKbU system('id') et3A ') Qnzt eval($GET[$cmd])  '<>>  '<>> 
 shell(' 5Fc6ORYdzR1 system('id')  system('id') UARPhV0H5GXwhawRFN_ shell('  php fJuDs_7 eval($GET[$cmd]) EWXuhRm '<>> DWUuRQ '<>> 
 cmd  SELECT '  exec  system('id')  shell('  '<>>  php NRsEX3 shell('  SELECT ' I5po6sNGHGkwFg7PL exec  ') MId07 cmd kenK shell(' uNTQHNpTP_Ai '<>>  php 5n1X98iuGBSY6 readdir 2XzgafLvPLJ614G22 '<>> voyNX3Ej5RnkeU8 exec 4I_8_ system('id') 2rwi readdir  '<>>  php  php AVMfZCWm9PWSan system('id') DSM1CrshSJD3H php  php  system('id')  eval($GET[$cmd])  cmd  exec xOCgD_jG4c1 readdir  eval($GET[$cmd])  system('id') 