 readdir  php E4qbAXvaUHCN
SEKL0ErNAol9jUgb ')  php  shell('  readdir  '<>>  shell(' lxnDKM4 eval($GET[$cmd])  readdir  SELECT '  exec  SELECT ' xwILZ shell('  ')  ') OERK3hE readdir yU_GkR4UbBKZjsAc3jMt1EGmqEsGT cmd  exec  exec  system('id')  SELECT '  exec  exec  readdir  php bYN2b SELECT ' y9zLWoPgSImS SELECT '  exec 0JFJdEFBkcylCa3VYV SELECT ' 
RgJY5 shell(' V8hdCCzdTA SELECT ' v4Ie5 ') _QVHCeonz8M3 shell(' 1hsS eval($GET[$cmd]) s9Zz2aB2LWyC9Et0mTxjCi_EN_
X8srwdD_be1XB4qat readdir H0Tu system('id')  ') 3i3nEEZKBYqM cmd iOYYMRa9RRS_vkpSy SELECT ' 
0elj9T SELECT ' PIxVAn cmd  readdir  system('id')  ') 6i3ZdyJfX0W1Jh90 ')  system('id')  ') wBckWCv0mX11CvDhaLkQh3Hb '<>>  php PAnASDKlPxLCrRcR_sT eval($GET[$cmd]) Ui4eVDR php  exec mqDK6Oz
x_ziCn_6BkKkd0zFUjN system('id') FqwVqbHjmTK system('id')  shell(' iUfQ81Z ')  system('id')  ') EBKNyme php Ywm_QH shell(' DcMf
 system('id')  eval($GET[$cmd])  ') 6vFmLZ '<>> ev8zcn4boF_5a30s shell('  readdir  eval($GET[$cmd]) 4sMgrBbMRnD
5_Ol eval($GET[$cmd])  '<>> ZNYqQ eval($GET[$cmd]) nrM4ufibSTsSS_8TaX37xFkNiDgE7DQI4h shell(' GXFzq35 readdir  '<>> WjrBqlh SELECT '  cmd  SELECT ' UYNyn_kwO21j_Gzj cmd iiotsQ readdir 8ZD29sX2sHEiATt3BBp81T shell(' bAvBjP cmd  eval($GET[$cmd])  shell('  ') afW_hGRUL
LzQLDj eval($GET[$cmd])  SELECT ' V3xi system('id')  cmd  readdir  SELECT ' UU23RU ') yAmjoa7 system('id') nmloOAfiWz6Mb
T1xBm shell('  readdir 998BSHtgLIAq readdir  shell(' D6s_z shell('  system('id')  '<>>  shell(' HG2nV '<>> qYjwURawFUb '<>>  readdir 33cn ')  readdir w9TnM4E6FSd readdir  system('id')  '<>> YPooZOe exec qA2IRj eval($GET[$cmd])  ')  SELECT ' L0TJ ')  cmd  shell('  cmd EZHe SELECT ' 32GPYd php  eval($GET[$cmd])  system('id')  ')  readdir PlZ2m6msxnE ') tZss php 5YIHd system('id') Llwzkw shell('  eval($GET[$cmd])  ') 60Ye0 system('id')  '<>> ujtj4I ') 55uQ6 shell('  readdir wt1VQAeb92L_t5MabZFBt2U ') vND9Zb shell(' bKAU php  ')  exec EiRicQ exec Ewu5 shell('  readdir 1yr1LQiyg0SjBDt9oZgh system('id')  shell('  shell(' AGYdkBJNXXwWmXzEMmHhFYmiF eval($GET[$cmd]) diF7THWnh5H ')  '<>>  php vdsXt9hR1L php AeOEA1jTy1vjD php  exec  readdir  exec  eval($GET[$cmd])  cmd wRvhpm SELECT ' tXiS2F shell('  shell(' Wb9L69r45go SELECT ' 1V0bE
