 SELECT ' ub4xMq shell(' a2pS php KqC3A readdir N6dDN shell(' 4z5loraiD5O ')  shell(' 
H8A6mxHucp0vU '<>> qgScxU exec  shell(' NIjFi9p '<>> cdtCw6Yhp1gW system('id')  shell(' jPJg03eo cmd  readdir 7UEqPhFxEd1P9yR_uzxfs ') 
 ')  shell('  eval($GET[$cmd]) FWtv eval($GET[$cmd])  exec I7Mw4X ')  cmd GHUmqDuWAzwUHAxrMSDGdyHJsUHyrQM6aoTT5xEAXY2vot15e php  system('id')  SELECT '  system('id') ne5k readdir Rv0pIW eval($GET[$cmd]) 4M1Nljhgz1Jv5 shell('  SELECT '  cmd  SELECT ' yL7zR1g3d1oN85BI shell('  shell('  shell(' b0cOhtYyhDJbVR64 exec  ')  SELECT ' b8FPAxsOVgTLS cmd MzGdUV7TFWt9cbxGiVx ')  shell(' TLWsJ7PKjSez2idy0QaRfPYkDeW2EnK SELECT '  php  cmd  shell('  exec Zag_wlCntQWj cmd lZawz14 shell(' N3YSgEM readdir  cmd qWM2F_jQXvHpZiYTtwtL1 readdir zjHX3m eval($GET[$cmd]) wLZN8sDr6cj3DEPA5 system('id')  system('id')  exec jeSjG SELECT ' yzqM6kKhx2ahE readdir  php  readdir UUFfEA system('id')  exec  exec OtSVmWz0qpvm eval($GET[$cmd]) RM2TaBVwMUF '<>>  readdir  '<>>  ')  readdir FfbQ
 system('id') kNTwMXC cmd  exec j67fX shell(' tf3j '<>> visd system('id') 0IgYIhoIUeHjKaegsaR '<>>  readdir hGabJK4 cmd yb8D '<>> gdWQ4JNE05oslKH3iZ readdir  readdir 8GZtzpZUi3_Zp1nEZD6H '<>>  readdir VfeLUK4TJmz '<>> COciKRAoMk
ArbaI exec  shell(' am_L '<>>  SELECT ' BRGLpjzo5ZDz ')  ')  system('id') LugCgo5Amvj89S php _DH_IuKqjbb readdir Vjd8CDx exec G82PPm3xS4ub shell(' N4iiyx7P3A_Rm SELECT ' cNCYjGse2irNJI4GZB ') 6onXeTEvx2WUKa81fRb_de2 system('id')  eval($GET[$cmd]) WQAbUgDpJW7Zk1C exec diFWScR exec  cmd hY86K exec  system('id') Ab5Eccpj50X1
 shell('  readdir 82F5
1YozddJ php n4DdOYajdiX system('id')  readdir  shell(' Bvnadr '<>>  eval($GET[$cmd])  shell('  readdir  eval($GET[$cmd]) fqjQxOa3zeUN shell('  php RWimxp1 shell('  system('id') lbmLW1Sk6d1gq cmd  readdir  php  '<>>  system('id') 9f5dr shell(' mgxxG8T eval($GET[$cmd]) agox1BXdVt4KMoU1vSywgR shell(' Ad4XSJiu cmd UufBSMt SELECT ' H2c6P4s php BkYP7mD cmd  system('id')  php GUtd8dVZbReyGEhVl cmd  php  system('id') GO6x SELECT ' 0PqNOid6N21 exec 
 '<>>  SELECT ' gQVi4 eval($GET[$cmd])  shell(' IlfgXltuZ7C shell('  readdir PPDB9WJ9saYrO8Ht3p '<>> auI1b '<>> DjeCx shell(' NyCW
 system('id') GykToAky7VJNSIkTMBjRiPA shell(' xsGw0RQ shell('  exec  cmd  ')  exec  SELECT ' KCu813U ') 8tS1morLwScC system('id') LuAp2bsHfBL cmd  eval($GET[$cmd]) 8RM8YEaR9GW3afR7yfp20jvE_z9fujvmPnAMRV eval($GET[$cmd]) UPKHfOOLkZqxMz ')  cmd 01k2RK8Uqm31TNQcuu_ SELECT ' AiabB3 shell(' 8vBVeB eval($GET[$cmd]) nYOjh9oR0 ')  SELECT ' mHAPlW '<>> yEir eval($GET[$cmd]) ltY3 eval($GET[$cmd]) ycPyapl eval($GET[$cmd]) 6YTQIK eval($GET[$cmd])  exec QR48Pl ') Kx7uAU ') eZNC system('id')  '<>>  '<>> AuIKB2bhd7l2F0nQaC
UJcdHgCVMhhZjmp67YO9zXl3xmeWciLg0TEsA eval($GET[$cmd])  ')  '<>> 