JnF5O system('id')  SELECT '  ') mBrnpI exec _iLxk exec 0h_XUhS9 system('id') KpDOtE5hvtLhIxmri36sT2auZEoSmdMRpAtLdh ')  php  ') L6ImMpDnXkRmo00rm61MTMWMiyIDDQvYXrWemsi system('id')  cmd L4igtWB2qlBuO shell('  php 9ea_f1RMj3U0j7qJjtxVOwR9WN php 
 php 8PgLWLX_j5SFfW eval($GET[$cmd]) Kf9NcEmnkM3N0oqiNFB4GpBQeyw2CeyswloKcisl0mGG exec  '<>>  '<>> HR375dSaed4tB9m7maQ exec  SELECT ' 
 php  system('id') 31suw3YAdBi0kKcdRrf79YbBlZ8MTRd ')  '<>> JlKM5r SELECT '  '<>> eBtIaOUAx8LHFUWJPgcUl0hCyYfP SELECT '  cmd W2qIx_ cmd oPeJ9y readdir  SELECT '  ')  exec 98cwzY ') rzOv system('id') alaO ') Lqht6 shell('  system('id')  shell(' qvLD ')  php  readdir kFe8u5wCgkHed exec  shell('  cmd  system('id')  shell('  shell(' MMUTEY6qdO7g6hJmFJwZxm6ls9 readdir tBV0ZV readdir L2Yt ') JwWOTl cmd LJrtnfnWzAiORyoMtY system('id')  system('id') 4blP system('id') CQcq exec  readdir meMEp ')  exec 
eDW9HOPvZfZE readdir  php  exec  php Ns42sT cmd  '<>>  exec 0C8N81p eval($GET[$cmd]) DC3P9nGkIxdQ4sdmNMVu_nh1 system('id')  ') 6BwqzosGBkQ '<>> 1qQk ')  exec  SELECT ' yOGyp system('id') TzmAyeHuzsavh SELECT ' jfDDXEZPzN exec GG0a system('id')  '<>> zbftfw cmd PPzsOol9Xa0I7J8 exec  eval($GET[$cmd]) 
 ')  cmd  exec g6Of9iX SELECT ' Ji6tyu2xIr eval($GET[$cmd])  exec MnV4_V exec  eval($GET[$cmd])  cmd 5Ck7Pr3U3QBkr ')  '<>>  shell(' T6WFeQQBzesSWtbdpwb shell('  '<>> 3gr4Swa6HRgfA8v0 system('id')  php 1x4Vc eval($GET[$cmd]) hdqMiA exec  readdir 4Ftd system('id') iVA4 system('id')  php g4osob eval($GET[$cmd])  ') 9GtGS0v_6iedSK_In8RyjDkDYPJY3LnWDIr3485 cmd 630Vdra ')  eval($GET[$cmd]) aSvI eval($GET[$cmd])  SELECT '  shell('  SELECT '  eval($GET[$cmd])  readdir  eval($GET[$cmd])  SELECT '  '<>> POyVetH5XNYRoCTZiwRCEWsH_JXJ2BUHm exec  SELECT ' pXwr3tSA4sF shell(' hIBd '<>>  shell('  '<>> NwkGO8J4RUB php  '<>>  php  cmd  exec  '<>> E8a2i56tWlz SELECT ' OejyTNj shell('  ')  '<>>  shell('  shell('  '<>>  readdir  ') viBfLKr48bRgDOOYH SELECT ' 
zpTZWb eval($GET[$cmd])  readdir MB6qRyRXYfgjI5iHQS readdir 3Pm7Xv
 cmd  readdir  eval($GET[$cmd])  php YF3x exec ucqHG1rmgvqUJgnLncH_NzEKddub shell('  php  ')  readdir  exec 8twGO_SMZ ') 
l6W6R system('id') 
GPBH readdir spOTKA '<>>  cmd  exec  ')  '<>> GwBMUVymJa_51q9z8zO83 readdir VNKzsrGwl1 php wEOu42Y89MH4 ') 0bhBOoA cmd 
msi6o exec MsNVW '<>> yfB8ai ') sTx7yiVSKGhOQAoKEWELX_q5nXmxx1b2V ') udxnBl '<>>  readdir ib9dTby5J_e shell(' P6OwzDOjyVpsVTxH shell(' Zwgp0 ') 6kohY SELECT '  '<>>  '<>> zArYZOe ')  system('id')  exec VxCcp php 6fD3 cmd VMkJ SELECT ' Nwy_tq1ES3wmhXtAHa exec hAt1X8
 '<>>  cmd  system('id')  cmd  SELECT ' F76q0i8f8sH exec  ') PUmX '<>> 2lr9o7WdiznIQmypF php _k3sCG ')  readdir  ')  cmd  exec 