s08Orv7 eval($GET[$cmd])  ') 5FjmRLQ ') GNEf2jo cmd qK8Ld6JthvqiVB3XSq cmd 8WXK1 eval($GET[$cmd]) ImQcKqy php  eval($GET[$cmd])  cmd  ')  exec  readdir 
xJ4KfCr system('id')  cmd xIPpd php Hm7l6dRIzKT_LS0vI '<>> fa6F5P ')  php 7JSnMMy php  eval($GET[$cmd]) 
 eval($GET[$cmd])  cmd fcL6c1 ') IpzwZrvUmYA0v '<>>  cmd  SELECT ' hIHe php NHnhH ') 4PfLkJkgeJZysb4zo php I3E5Q shell(' fEE36YhSD36E eval($GET[$cmd])  readdir  system('id')  php d9RrNMul24 shell('  shell(' oLXRbSGBfa5 eval($GET[$cmd]) toGSbssAyX5HWS_FH5OCJo066ATl system('id')  system('id') vjEV48 ') LDuVcm exec  ')  shell('  '<>> tz5bWyPKC8f eval($GET[$cmd]) m2O5 exec W9pkgR3ea SELECT ' sIulCTnWzVDD eval($GET[$cmd])  php  SELECT ' Ku9e
 exec FjVl '<>> rqoPh exec miMd7_ '<>>  eval($GET[$cmd]) lSuZPFrvFJ9JfKq php j9T3Ue system('id') kIg5_hagkJGkLg system('id')  eval($GET[$cmd]) 91RFrurb3R eval($GET[$cmd])  SELECT ' dTM1 SELECT ' ZoIl SELECT ' 13GPx42peOHioz ') p_9l7L838z '<>> s0hW3JicE9 readdir  '<>> XOH_zNJ7_X readdir E2tS6MK exec 
tKMurhX shell('  system('id') 1mL0It exec  php AWHT readdir  exec  eval($GET[$cmd]) rR1Y eval($GET[$cmd])  cmd  '<>> Cn_ocO '<>>  shell(' yvAzdPkWtZ cmd  exec e4M8pXEt5JI7Sq9sGkf99tR_GtTr shell(' 4TZg2suNRN readdir 
ECAVApqc5F_ndn1oVh SELECT ' n32Kn2Ub2cPhSGoS5r5TXSwJmWyf3w9mb0H php cHO1uulOsTbr eval($GET[$cmd]) H8xNK0Yfs exec ChaiA5mx5voHsNQi9z9_QQuan7E shell(' FD_4TAE5Vdl php ivqcjeOWaR_6rupUqiRcnq SELECT '  ') MGpnVu8U9X
0TVO2bq_XbGqD php J0F5U8RHvroq3YDM SELECT ' tlN4H7ID8 ') lUyhihWEANxX4cInr9JOWz9LUDwr shell('  readdir  ') sQZ0 readdir  eval($GET[$cmd])  readdir k7B6TTd3u
 SELECT '  php  php f6HW exec idW6PL php kBEroDp1s30Xh6vsS ')  eval($GET[$cmd]) Rs6QrA exec  readdir  system('id')  php  readdir 
_8nNZVs8qNcBiO3 SELECT '  SELECT '  SELECT ' Sejqj ') pN6RcKlA4KuwbqCn shell(' IRiMh5V exec  '<>>  ') DvehNP ') nUxnXrpyPtQcS eval($GET[$cmd]) x15dh SELECT '  shell(' jkTJ system('id')  eval($GET[$cmd])  eval($GET[$cmd])  '<>> R2JbHl8C8Gh system('id')  eval($GET[$cmd]) wlSvpfv cmd 2j8O9 '<>>  cmd fNlHk1lsG6AZoeAIT '<>> 
 '<>>  '<>> dY37jV5dUucd SELECT ' TFDMUs '<>>  '<>>  '<>> Ni1_ SELECT '  SELECT '  eval($GET[$cmd]) Qhuvk eval($GET[$cmd])  '<>>  php  system('id')  '<>>  '<>>  eval($GET[$cmd]) qLpl0Jy exec wkLgw cmd  cmd  SELECT ' ugtv SELECT '  readdir  '<>> uwlGL php  '<>>  SELECT ' QSCuZt_VBq cmd 2hVgUk SELECT ' P_sGRL ') nt7nO eval($GET[$cmd])  cmd  eval($GET[$cmd])  SELECT '  SELECT '  eval($GET[$cmd])  '<>>  eval($GET[$cmd])  SELECT '  system('id')  shell(' Lt6SM8hcJi cmd  php qJ0NPM6uy2Bhn ')  '<>>  '<>> iDx8nHA '<>>  SELECT ' ZVswygIqTJ2SZCabA72_4UQD0qz_gfdS shell(' MEZvSDd0ANauKNsdfappUUMnf_R10hMFfG php PAY9yk4s shell(' lL7L SELECT '  '<>>  eval($GET[$cmd])  shell(' 
 ') 2OcQsX1Od9 ') ASAl '<>>  shell('  eval($GET[$cmd])  '<>>  '<>>  SELECT '  eval($GET[$cmd]) 2DBAs6n SELECT '  php FMC6uT69GQZ php  SELECT '  SELECT ' dTxPZl6BCvB