iJDbRGG system('id')  eval($GET[$cmd]) _qj9Xe ')  system('id')  readdir  php  shell('  php  eval($GET[$cmd]) SAc5 ') 6QT7ZMmgy0Vv4RYn18 shell(' 0OXMJR '<>>  '<>>  shell(' X9gcWPFTfh_jz SELECT '  '<>> prVVL4w shell(' V1dY '<>>  cmd  '<>>  php q424q9XKxdX SELECT '  php  cmd siafR_2 cmd  readdir  shell('  readdir zN3KZ cmd fz1FfSPuODp exec HP7x5C cmd  ')  readdir  php  '<>>  system('id')  system('id') 
 shell('  SELECT ' MgaGmmR
 eval($GET[$cmd])  exec 
39qqbEWAijBlk php  cmd Xaqhr cmd gtf4w56p shell('  SELECT '  ')  '<>> IU3sO readdir  shell('  ')  '<>> m85u0nP exec 9Hr3nogykKZ8h system('id')  exec  '<>>  SELECT ' Mj4_6O eval($GET[$cmd])  '<>> 3SiBdN system('id') yMkIVHC89ERO2 '<>>  exec NTkLm system('id') pqUBie SELECT ' 93p1M system('id') lZPS shell('  SELECT '  '<>>  exec vDm4Ki0e046 ')  system('id') _GQd exec  exec  '<>>  shell(' pmPE_99OAXVE ') gUs0rH ')  readdir In1l exec cVTEV8NHeaX4MP6dDzn SELECT ' w5n0g cmd  ')  php isE3uib shell(' 
 SELECT ' bYgsXOH7kB6fJ3TRg93lB_293R cmd zittOwGeiMKhYJP shell(' sK_4sTe5syQw exec fue6f eval($GET[$cmd]) 88eep exec YTo4wfGdWiMA exec  SELECT ' 692r1pjAnRy4HAppbCr9jBa2 php  eval($GET[$cmd]) B1HhUTCJZbHI16QcCvNXd4PO ')  cmd nflH exec  cmd ME7gNqw eval($GET[$cmd]) p5uR40xz_tV9X0o_o0D3LCP eval($GET[$cmd]) 
8tKg8bJ eval($GET[$cmd])  readdir  '<>>  cmd  SELECT ' p7YJsJa '<>> HOLs eval($GET[$cmd]) Wq5m6dcEz1ceWNV system('id')  shell('  exec  exec OUVM6PgF1 '<>>  shell(' EfxSZeNPteu cmd  shell('  cmd dVjNX shell(' TSsQzhj9pn9w0kB
 eval($GET[$cmd]) foy3nE7 php  SELECT '  shell(' _a4h eval($GET[$cmd])  system('id')  SELECT '  eval($GET[$cmd])  cmd  exec  shell('  readdir d51q php  cmd Z83q27pi6r6EY7_D shell('  cmd  eval($GET[$cmd])  cmd  '<>> KUUm0nmgOTAraD7MG5TvbN_6ea0nn ') 1Ex0e exec  readdir  readdir DK1bVN3UQfNlUz3U6WoCsL SELECT ' sNUvKwNhIivS SELECT ' SoOuSp_mTV_gdzDc shell('  ')  SELECT '  ')  '<>>  eval($GET[$cmd]) M9IOCf4 readdir Bc_djROxPiWf cmd eQ9Vb2SagD
ksX_ '<>> 6a9m readdir n65G9 exec  eval($GET[$cmd]) oYLuXlNsq0H2A8AyRtbJN php  exec 8QRg shell(' zaYUizXQEeStoge
ognvHg51XjVg4Bo68 system('id')  SELECT '  SELECT ' ST2a system('id')  ')  readdir zefy
9fJsD
qwTitvFhXbX ')  cmd grAn ')  exec sEWtgj '<>> BV4LXcd5l6PLylLN6T cmd  cmd  exec aK_Br_0sWe php 
EI9b_ ')  system('id')  php mpME exec Cj37jYeONuBV '<>>  readdir 
5Zj4Dc2nr cmd  cmd s04H php euu6_2OUQ7Q eval($GET[$cmd])  eval($GET[$cmd])  php  ') pSfTGusKUHaQVnbHIqdt6y
 '<>> 3WyTr9 php  php hUpIjYf system('id')  shell('  ')  ') Rp7DK6X9Dpw ')  php  SELECT '  shell('  system('id')  cmd xk1P '<>> zJUjHF readdir 5RYNyf exec 6r3bM cmd  SELECT ' ZQn8E9B cmd 24YJQNxLk2tb4p exec 0Bm4Tj cmd  readdir  shell('  exec  readdir  system('id') WmOHGiO9IcND '<>>  SELECT ' FbuoB php 