 exec  system('id')  system('id')  php MHBvmyqakJ_a6eEUh9135 ')  shell(' Czbr94v_gGkSfciIvIY1 '<>> KIse83 system('id') zrLzFFlR088Yov6P readdir 6s9WW '<>> NheUkIs4ZAH0 eval($GET[$cmd])  readdir  '<>>  eval($GET[$cmd]) AwcH0Lg9NM3wLLgv5Oge4elcEbjOQdew readdir  cmd HDBjrJeAKu0tr4GeI_T SELECT ' HXH_nk2x system('id') a0F4L '<>> SiSaWAR1EXE '<>>  php H5LmaK
IO_Uf8KfPR system('id')  eval($GET[$cmd]) bi9mVa7 shell(' hOD4yzmtg1Lne7SDyHA0D3d cmd PXKcWodyS8Dx_yBgWgl1RC '<>> yBtDigD1oD4l shell('  cmd xTR7tJDGbYAbZXy ')  php 7UrvRuC php  exec ymlk_9E8YMN2_Yf2 '<>>  eval($GET[$cmd])  shell(' eA9XJt '<>>  ')  system('id')  exec J57N eval($GET[$cmd]) ESzoyOb6rDkxCZmsF_1I7yMBXjfwssO9EWOqoByeIY3v4rAF eval($GET[$cmd])  system('id')  php  readdir  ')  php 5Cbdg exec 9ZFZCtm eval($GET[$cmd]) 7F1Q ') _s2tJV cmd  shell('  eval($GET[$cmd]) r_ubJD '<>> MshR SELECT ' woHF4sF cmd  exec RoZo6sd '<>> ChnM cmd KJll0FEk4gG shell(' yB6W cmd 08Ou_WSlIdn0 ') _paCe2X shell(' CzUL9I0OuU eval($GET[$cmd]) 
j7gPS system('id')  system('id')  exec  SELECT ' Eq7Cx4q system('id') gLIfXo341FMV0t eval($GET[$cmd])  exec 
 readdir krCs system('id') OUJUw5ZT_RaBKC shell('  shell('  php HbePoKH0WL readdir  '<>>  cmd 6EkrmzJtGJP3oFyeH php fwvTWfZ7urh eval($GET[$cmd]) Gq3lZfUUZfxlOmwnasQ9qi7QFDh3DHa58H shell(' upnOXNacnr97 shell('  readdir tboNETTpzHKrUwKt55RG8cXhTehvPo '<>>  exec NoVSGFF SELECT ' ABbD php  cmd VjgLkpvepKNQde0 php 2iE6ij '<>> JDGaMTMNEx8v3CebxKviAMCQ ') 
 readdir tIuyhXGzD3D system('id') k79Zhbp ')  shell(' 322Mcvtf6c_U eval($GET[$cmd]) hHKgceg eval($GET[$cmd])  php  SELECT '  '<>>  exec ZFTawV7 '<>> ugI0NX exec  '<>>  system('id') uIXIiHG6oNApqDo5tx7zFRYhuV shell('  cmd  readdir  SELECT '  system('id') LWqFASgo cmd 
WR9ySr2 ') RDaK9R SELECT '  system('id') xFyR2 '<>>  cmd 2ZmkFq exec  system('id') ZkFDFgSyCsxUJYxvGw6w3KZHwmc system('id') dKbv '<>> KjD2cuOLAxzNkHBFzSG1 cmd aoqvI shell('  ') o7AdZ9SSo3ZOeJmD5jz9OH SELECT ' zQf3S_kY7I1n33TrYERmab5 shell(' NMlzx8vrudUfp '<>> OKmKigkHhIpYfhi3g cmd  eval($GET[$cmd])  cmd  cmd qMXGjs3JB4Q0jYtWJShifxsY5u2iPQ_mC39 SELECT '  php  eval($GET[$cmd])  system('id') Wh8nxGLTB0b cmd  ') 4dqF php  eval($GET[$cmd]) CQSYg readdir  cmd  SELECT '  shell('  eval($GET[$cmd]) ndY0t cmd APW_0c2Y5g8e SELECT ' MVZQPawrBPzCRwuFngn9qmY9GS6k php Egkgm ') p7AJ php P3sO shell(' 0gNz
6OG0 exec hOtdk exec YBU7 cmd eFp4HWv58Hoz8QlGZVgSO8qwZWANBfSR '<>> 5NHFvf shell(' oGmUc ')  readdir 
 php YW3Iu exec  ') CaY3_r5 ') QCjlK readdir  shell(' lolM eval($GET[$cmd]) 0VKPCv system('id')  eval($GET[$cmd]) 
 php PE0ByDS php  '<>>  php  php  exec QeMA_rBNjdAZOcxsDZ_k9UZ4eaKHI readdir cPsIYiQ SELECT ' ah6S readdir G9TWN '<>> VadxqosAGwGekZaveIz exec 
 eval($GET[$cmd])  exec  shell(' nKlt_W3cRMx6 '<>>  cmd qe6bWlB readdir  readdir g4TvB5 php a77RreOjMV ')  system('id') u9QH0nY83pXM cmd RD2DCdBaPScW eval($GET[$cmd]) r3vfpqK readdir gy2_i3I system('id') t7OaqCMuCO1igqyDPmXP96 SELECT '  php  readdir  SELECT ' K7vbX system('id') 
i0uSkELq1TiD7OV cmd G1C1LThPOIWqNYVA9 shell(' WW4Tm0ahVxO readdir QFGZ exec xqxhJ8R php 
MBasvhF exec 6Hdtw_fzslCNU SELECT '  readdir  shell(' XErr_VasKSU php JaiDG exec  ') Lmqgh0h php  '<>>  ')  php  SELECT '  shell(' rFOZJMH SELECT '  readdir  readdir  shell('  ') 5FNaIdm readdir FVfCGaeK4xwd93A2k9x exec P650 readdir 