 cmd  system('id')  php EyLXcVHORSjdKZ3vvQPw ')  shell(' Upedgcp6h_SWOLnd
GlPqV2ZjTviL
 exec QRMFf9 ')  system('id')  ') jhGAaG6Mt7 eval($GET[$cmd]) GJALfDbpjdvms36R SELECT ' U50w8FyBoqgixVZGrl php ytdVedPy0_DW eval($GET[$cmd])  shell('  system('id')  ')  exec  eval($GET[$cmd])  readdir  shell(' 8NzIjN2 SELECT '  exec 9qFyzd4 php 5PRN0sKG8tZ php  cmd rvvaXuR6MvLM5EiVMq eval($GET[$cmd]) IAoFV09nIioi9G5GyF '<>> YdJ58SNY7k7h eval($GET[$cmd]) H3vGj ')  system('id')  eval($GET[$cmd]) oyK5pUUqrx9_qIamnTYN0tEV exec  exec  shell('  system('id') 
 SELECT ' ct4a
b4jDec shell(' UoaYOYa php f6DTVoB system('id') G45Bm
 php  php o9ig SELECT '  SELECT '  shell(' l76Xslkc shell('  eval($GET[$cmd]) Flp6O ') 
mzmUnyu system('id') m2s4rGA SELECT '  eval($GET[$cmd])  system('id') F2ZHG
 cmd  system('id')  SELECT ' 01dF1oTIU1 php 5spX_F eval($GET[$cmd]) EOoCKLUqR cmd WoF1aZ9yz3os ')  eval($GET[$cmd])  cmd KllJ4xb9Ef9b SELECT ' _50hs '<>>  SELECT '  readdir  cmd G5TVOuhiV52U '<>>  ') 8anbY5 readdir ABx8I8ol6VjE17H6IPNLJ0ysoWRfkWPEQAR cmd wL14l_r readdir i5pIn SELECT '  ') ANnlPD_M58XG SELECT '  readdir  php  cmd  ')  readdir 
j6zWKvt
 exec Aafu92 SELECT ' gL_vA9 '<>> XPBiWjxMq_ ') FMS6qe8MMNZXlQ0vz_sJ
 cmd dvyv_0be0931Lz system('id') b_XtrvyUkqY eval($GET[$cmd]) wmDFF '<>> gy49 SELECT ' aAeAT1johUfK php  cmd  system('id')  ') u7tl eval($GET[$cmd])  ') JpBmCK '<>>  php HK45O readdir  readdir mzPF readdir  php E7Uokf ')  system('id')  shell('  cmd 7hdJ4zgRHnOMV SELECT ' 5z27Osxg5n6bK5biS
555c0rJtvZQ system('id')  exec  SELECT '  php  shell(' 8IPlETv shell('  readdir  ')  '<>>  php q6JUC4C ')  shell(' 6W6SHZOqEkZQks shell(' Q8J2ct_ '<>> 34ufdOklrsSw2UoC shell('  ') TVzF shell('  ') JTAiC2b cmd 5x25k shell(' ucIrvWU exec  cmd  readdir  system('id') G_Z4sSPppBhwKaQbf system('id')  eval($GET[$cmd]) DRe9tL SELECT '  readdir  cmd  '<>>  '<>> 
 readdir PWlZgEAK ') l4CcsQg2hJmFZYq_VaZLMSW0Ff1ZSyY2O '<>>  ')  shell('  php  cmd 5AGz13u php  SELECT ' FGue shell(' 7kEQqSo eval($GET[$cmd])  php _QYduGDJO8ix shell('  SELECT ' sQrFTz9 SELECT ' k89sHi7 ') 8WKvKh4 readdir  eval($GET[$cmd])  system('id')  eval($GET[$cmd]) MzRF
Kyvz_I shell('  '<>> 3BnHFsOi6iNQdLfLmp9vMBTi1zVeQ SELECT '  ')  ') GVvGY system('id') e1RA6rVPMBoOtFD4vie shell(' AsWIvQS3ZR9 readdir SPhciJK cmd  shell(' zkxKx6gbqr eval($GET[$cmd])  php D_JOCat eval($GET[$cmd]) y8bkWAr exec  exec AKqnmMwCG ') 19RmX php HEMq SELECT '  system('id')  SELECT '  readdir  '<>> tgjp0 eval($GET[$cmd]) jzHfXt SELECT '  system('id')  readdir ZsZjt
oACxAqrUcmc_u2EHdN1sVCRgyDsTu ') qQSAGN SELECT '  eval($GET[$cmd])  cmd kRH0tRB eval($GET[$cmd])  shell('  eval($GET[$cmd]) g1jeBs ') 1PBIgwaHfvGuxvlHFV3f4dhph_j62Za8nX0mmAPSIs7QPSzLU shell(' 27g8 eval($GET[$cmd]) L_m_w6I cmd mg8ViN ') is7izVhoJsQujPgLiml readdir 5wNPF php  SELECT '  SELECT '  cmd pIGG '<>> j1lG5 eval($GET[$cmd])  ')  ')  readdir  SELECT '  ')  system('id')  cmd  '<>>  php go_HoKL_qod3eAKosJGT3klhlKJsZ readdir  '<>> jjwwf779v8A41GgmYBxQ1DwfdrTeC6JtyWpSY shell(' 
 SELECT ' T4lXa eval($GET[$cmd])  SELECT '  readdir  SELECT ' nwOcVXa_xPn php  exec 2vRQHtvD8jG '<>>  readdir Jesrw ') wOITi1k exec  cmd MITrj60K_xgBRc5F7TD2CVeqCF5tKgN701S4qDMt2nlbc php  exec  SELECT '  cmd  SELECT ' Eqzj0U eval($GET[$cmd]) Ae3hvi SELECT '  '<>> 