 cmd  cmd UDCqWykOh system('id') 5iD4n SELECT '  exec  eval($GET[$cmd]) Ji7lbp0PJ9EEkM php  system('id') yyzT system('id') BOI3bo8Md3hihiEjgW2kAL1 eval($GET[$cmd])  eval($GET[$cmd]) 1XyW3 cmd 5qNuTKtivoh46Nfrq3 readdir  system('id') iAApCwVNiD_ cmd  readdir 6qT4mV SELECT ' 94ZmyASJV0Ti shell(' 
 readdir  system('id') 4cmPZhC readdir  shell('  readdir CKTn cmd  '<>> h5WCXA
PMqCld exec  eval($GET[$cmd])  php  eval($GET[$cmd])  php RvdYF3 exec OPlcg readdir  exec zsTivtOUVkbp SELECT ' M4gnTBmnhqCyiY7AUHw
 SELECT '  exec jp2JjIl_Yv exec  eval($GET[$cmd])  '<>>  ') pq0s5n readdir  readdir 
 ')  readdir  shell('  exec  readdir  system('id') 4h6J
 eval($GET[$cmd])  readdir 3Pg099DkmtlWh8DYD SELECT ' vS8dZZ0V6EzcHZSqvVLo8G8hP6whe exec WfTigpn9nSnFXJnbqvQ eval($GET[$cmd]) T5IMrs36_5aVNJ_A '<>> leBQkDOj39jJN20K cmd  system('id')  shell('  '<>> 6cCpXX shell('  cmd  system('id')  ')  shell(' Lgvr system('id') _FPb57J system('id')  '<>> KAWfFKKsmd php rEtLqPVYqnL6xBIxqgOicvTLZy exec 3E4Ae shell(' 0xb484 cmd vH1NjQMEDONqBYO '<>> 
hX71t shell('  php GT_Slh '<>>  php  ')  SELECT '  eval($GET[$cmd])  exec  exec  system('id')  system('id')  shell(' _GMvr cmd  ')  php  SELECT ' 6jKhk ')  ')  system('id')  shell('  cmd  system('id') WAh0v system('id') 59zJ8A readdir Y6inNtFG8YTSYUt9ER31xde9aZZr91 eval($GET[$cmd])  ')  php WfNYwAq6_k2sslUp7 cmd  shell(' gvvzwGN php  exec  shell(' 
PCT3 exec 8CH1TF eval($GET[$cmd]) CQlbbsusZ12ryqZ4o php QCGxXw5 readdir xW5RSqV readdir fRIf6U4yDuZcLO3t30TQrD0HZbNVtnFv74qVUG readdir dzrd system('id') sOp7q system('id') xrLL exec dImJ3treS eval($GET[$cmd]) x9I_UXG
7D5h7CQ2TOAhSS4Kq13 system('id')  exec KflRe7DXmp '<>>  php Nshw '<>> xsFvsuuE eval($GET[$cmd]) isTH
 php  system('id') GKn6oudWgFe3 cmd  shell('  ')  eval($GET[$cmd])  readdir qZKbTQH2tZUzUpPI0 cmd bACnXRC2th shell('  cmd xvys system('id') 1aTTSzeBtVn_4 shell(' oFBjDghn shell(' tOgnBo '<>> dflEe7biyrpKdD0d SELECT ' ZeSQO_n eval($GET[$cmd])  cmd  eval($GET[$cmd]) QUyfRTfGJ9X php  readdir  shell(' 0EA1 readdir  php 3a6FIq_ctS8eZHA ') xOVsYx eval($GET[$cmd]) 1FBXn readdir OsER4WUf6X9 cmd 2rIaW php hRb3efXscd readdir  eval($GET[$cmd]) DxjIc0WEpU ') Qolw
 SELECT '  cmd 5qRtWT cmd  ') vW_XO ')  '<>>  eval($GET[$cmd])  '<>> YyqIqzmeBGA1lL SELECT '  '<>> CEWR shell('  shell('  system('id')  ')  system('id')  php epb3EFlriJYVKvba3a4 exec  readdir z4h0L shell(' vXQ8Gn_HlJr_Y