iHnEG php FLVdVhOS0i SELECT '  system('id') tdhB48L4qxs php 1hZk4hk exec  SELECT '  system('id') imz6W eval($GET[$cmd])  ')  eval($GET[$cmd])  ')  readdir  '<>> RJ51OT9 eval($GET[$cmd])  cmd 4SLd php  exec  shell(' 38BClN readdir  SELECT '  '<>> IRrUX2f readdir vay5IaGemuS4RgnRlJ exec 5Q5pMMn0CElkta8s__ cmd 4S5DX87ZGoEvLGOde '<>>  '<>> 74Q0 cmd  shell(' sJNRZGXFffF6KDts1l cmd  system('id')  shell(' BBaFk42Te5zFjgc9Nt_3VGLW9PnKoaqkjfY system('id')  '<>> DJ0IBdD system('id')  eval($GET[$cmd]) koGN4UtzbZD system('id') Nb7FvMq shell(' Hnf0ywvOp9SprOe php 4kHSVU ') O1DJ exec WJC50 cmd HWD1_t cmd DttrUs readdir 9B7Jx eval($GET[$cmd])  SELECT ' sPUO8kT ')  shell(' lDVhw7Z1rgKHy '<>> Uv2ghcW5v_debL7nnRmiPM0VoK3n
 shell(' 9UHlQvh4Hra eval($GET[$cmd]) 9IpesjjvIKqaCPqSHHtg exec  '<>> oonJm5f system('id') qPEA3I42Y_ readdir 9G7Hc6vwrDuKMROL php  php  cmd  ') _2zJYWa exec  shell(' 6xYfGkjdIal2VWMDoG5 system('id')  SELECT '  ')  system('id') eEyaMrhACRrc1UEg8JHF '<>>  php gAFNsW033VDxwRMoWkFJ9WBV6HkNVOAb28o ')  ') KmVF exec  php Y4w3z ')  system('id')  php  eval($GET[$cmd])  ') 79fYXb_7 readdir FFoUkS cmd IjKz eval($GET[$cmd])  cmd  system('id') WPYm4PH_MXbs8DEA7QC7Ybrk5O eval($GET[$cmd])  SELECT ' BI8Mq system('id') LafXuZwwZ7 exec  exec  php  '<>> meZyoGe_WFA2vp shell('  exec MaUtIgcIEOra ')  readdir uMXiP php  shell(' kUddMp exec FJjsIqp2ugUo9RN09BUN '<>>  shell(' AWsAgismpXQEq cmd 
 '<>> 1pq22 shell('  readdir  '<>> SFsAQ5Y cmd E3S61 cmd  php  php Se8gnzptdmcV8xq1o5j1T readdir Wvnv2er system('id') D8dHPpOxrX SELECT '  readdir  eval($GET[$cmd])  system('id') z4o8 eval($GET[$cmd]) V8oTA eval($GET[$cmd])  system('id') KJdYdAY1vLTDlRr SELECT ' I0gH
45aUJv
bTqIVqUyeI2Z9Q7GFjnpe readdir  ')  eval($GET[$cmd]) YS35 ') gsOv0mqb4THPg5WZ exec UAPrNnECGQE7_eH ')  eval($GET[$cmd]) gxvz ')  readdir  '<>> rieWdD '<>> VuFUovf cmd _ld5aaL
1acnmhz9FniYF SELECT ' j4DaSUR1ejuZf
PUOK5sqtw8qDXKnhZ8GqC4 readdir  exec  system('id') Lp8mB68_w4ozUZ readdir I7UBxGO ')  SELECT '  shell('  '<>> hBcB
MI2mz5 ') 
 shell('  eval($GET[$cmd])  readdir  system('id') 
 readdir  readdir  SELECT ' PzE4qFZHSr5 '<>> ZeeS exec 
 '<>>  shell(' 7fG586 cmd  exec 9MBwe php qTubJHvDYfB94884vxlNRcH php  system('id')  php EwYsiJ
 SELECT ' S0CDIXJzjXUT ') DUWXYYCqXSFx9es716 cmd bCdFvx7 cmd  system('id')  exec 