yhgwzkA '<>>  php  readdir  shell(' Epzxd eval($GET[$cmd])  readdir  shell(' _S0tAPMd system('id') UjidrDW7 cmd  readdir  shell('  shell(' lN2J exec 4QaN4q1lILpu SELECT ' ZCTgMoe '<>>  exec 2TcEd eval($GET[$cmd])  cmd nerB_LNJ53qqkKrgH8 exec 5_M9KCF exec  shell('  exec  php  exec 6u4SZ shell('  ') j9Byjqt shell('  readdir  SELECT ' R9oy ') rinOsf4ktq eval($GET[$cmd]) wqHwlk system('id')  php  cmd  ')  shell('  system('id') q2rJ system('id')  SELECT ' FmKz readdir  php nEdxq eval($GET[$cmd]) zm_fab php cbFG ') 7GIAUG ') o8yBvmEdXGmShahG7i eval($GET[$cmd])  cmd AWEWrKzBGOSLL_LcYuWEVKOoqX_daBLS system('id')  SELECT '  eval($GET[$cmd]) EBde4_LUCHESGVwDZnYEoaiB eval($GET[$cmd]) jlvat ')  php  ') 2vzd '<>> Vzh7xi php  '<>> kItQECdavkeov ') 
 system('id')  '<>> CfR_ '<>> NqYmC8W0fYEhPGBWX2d5bsq exec JYbvQQKNG10cyI eval($GET[$cmd]) CMKmEEkxA system('id') 8I8Yy71LF php  eval($GET[$cmd]) Xv9l php  SELECT ' M8P9k5PCYt7lzO7gb4 shell(' 8ouHz '<>> 
 SELECT ' SwYV7i8vJaZOvQrn6tgVb system('id') 
BlkHlk ')  exec DUw_f4wZTKzDa7 cmd  eval($GET[$cmd])  ') j7pe43szLRYBbor8hgP4 php  exec twDcFPNXilKFW5bqr9 readdir  SELECT ' x3wyIl SELECT '  '<>> xgR42cpBuxR3B '<>> XLe0sOhdRlu eval($GET[$cmd]) pRd9L8Q system('id') j7hWI readdir  system('id')  ') H4oEtr6 shell(' RN3z7d php  exec  cmd qx3Xy SELECT ' isWn eval($GET[$cmd]) KRf3WbrzbP8Dwe4H cmd RQRU
EGhRglT ') yLp5R0Y shell(' xGe1 cmd  '<>> 9wzfkKO readdir Yr9g0WG php dyrR '<>> 0bra exec  exec  cmd Vhzg3g exec  shell(' i8Ha system('id')  SELECT ' r2Ez shell('  SELECT ' 8Zp9vc4Pzvr readdir 4t5CrsyG87isuH__hKB1axFEDrmW_2F03tjsijWXRvmvcbz8_9eGIbi '<>> ZXp6Xf3BCj3uUK3ia2hv system('id') 
ySjMr99UFjw eval($GET[$cmd]) gH7Z5 php  exec  cmd  shell('  eval($GET[$cmd])  ')  '<>> RHalPiZ cmd eT6g_ system('id') FcXQ system('id')  ')  readdir 6tqW cmd  ') 69LOBk789xmMe cmd  shell(' l90F61cs___APpuh89K_BUhECau0E '<>>  exec  SELECT ' xzAExyT system('id')  readdir PximJ eval($GET[$cmd]) fBAEG197hAHBn6 '<>>  system('id') 40Xthhzu3uIp SELECT ' XU1S8KKvF9Wn44fjU50S85zzCXPD_ eval($GET[$cmd])  shell('  readdir H4t1zed2oiVBxkLe8TCcplTEapb1vRO ') w2h5hb5 shell('  shell('  cmd  ')  readdir R1Pk_ymTQ cmd  eval($GET[$cmd]) RfkBWmQhwt3aPaLpvPayhO9_qzLUys exec XyhL2GN system('id') LaZ0WOIW4Lm9_20AghHQwDqfFYtDMQ shell(' jSXxqbV2D cmd  cmd iBsitEZm eval($GET[$cmd])  cmd  cmd yCT5L804kSiX cmd BTRlN exec  shell('  shell('  system('id')  SELECT '  cmd  '<>> O0rPkyL1N php 86t6an76sJqTxZDLLIjoN exec 6KghM '<>> qEMhjp1hR8WcD_xo '<>>  readdir  shell(' c8f6nCG shell(' sz5CE ')  system('id') O4McSTNSFOkLdo eval($GET[$cmd])  SELECT '  ') CJVPoK18 '<>>  php IC3c cmd 23Z6h system('id') uZs_1jYWtbUdpX '<>>  php mNSYagZODf ') 3XoX5pYvOcuuV php Jz6aJ system('id') ciUyDPI readdir 
 SELECT ' pwxyw ')  system('id') DnCU SELECT '  readdir  shell(' JbNY9W
 system('id')  ') 3_UztUcfggHR ') oXwGKkYUbV SELECT ' SS9x5qV cmd  '<>> uuWSFMFyN1Q cmd zcYOdy7qzmEA5 php OYq0bYDxFkpFfX3wu shell(' hIT3kC system('id') i2EwzNfAeHD system('id') Goii4tWUpRn cmd 87BIpZm2_yQcR1B0Z system('id')  system('id')  php JrnfgZ exec  system('id') Fxn4vVa3Jrv
AevQ0HgAOJjjl6Cmq8VABJ3Go1FVqaP SELECT '  system('id')  shell(' sDvTAXV exec  ') CBFpOYcFXrXZWabtRz8UD9mDC32 SELECT '  SELECT '  system('id')  shell('  system('id') mfsITALT9MZo_pFrY system('id')  shell('  system('id') TjdBl eval($GET[$cmd])  cmd hRwJw78Q9Yh4xtiigFu00nb readdir auhcAdi9YXNQiK8M SELECT ' tDMN9c7
