F34JjXD78ZR_92Ay shell(' XVVs8nwbcC9X readdir 
LA1dMU shell(' AcOAqNUHcBS SELECT ' AZcmKCsvP6HWKI
 readdir Ev8dB exec  '<>> tEQqpE2 cmd  exec  ')  php  system('id') 4uOg SELECT '  system('id') 710aD shell(' aMLGgd7bcEZXg7Kljlj exec sv9Mwz71xSFe SELECT '  shell(' nlHzdiP9KriRloTt5XiQdPR7aPxSiKcY9QPY_CVDVnngZ
OPGor4aSjy_ '<>> 5WZ5D cmd pZcWF readdir _IEcna_eHX9 php Qo47qjfyEqZNEa system('id') OY_lgt php VgRMTFH9kT4GJaiF SELECT '  SELECT '  ')  exec  eval($GET[$cmd]) y43VqSUa4MNwJLQpczH php  system('id') QZoSHFv87l39VOo8R eval($GET[$cmd])  shell('  exec lMZ9mtT readdir 
yE1cYu4O exec 
JIwkF php  shell(' 2yNTQzaFYyI SELECT ' M88Py readdir YBy4ZY ') wLlioHd0DP1hwY_ system('id')  '<>> xYxFE '<>> pR59GnbuVhMqwpA4aedquBwRJqhWNU4s eval($GET[$cmd])  system('id') BlnT cmd  ')  system('id') Mnz2kFr system('id') Kon6hut0XCuGCZBfQkC_zc php SLllQ exec BgY9lIu_NkpFnTFjNT readdir  system('id') dAO7 shell('  '<>> 7e1QW1MGi2lSikaPiFDIV3CTi3B_YF eval($GET[$cmd]) AhW1ldlYwcx0qSesydET45an php bEqZI readdir  eval($GET[$cmd])  php xYq20 '<>>  '<>> a4KPT3y '<>> Cds82tb shell('  ') xzclxLG php  system('id') 42EA '<>>  '<>> 9kcrmww readdir  SELECT '  shell('  shell('  readdir  cmd  ')  ') pcQ9hk cmd  ') cBzBp php EnwIic '<>>  system('id') 5hUYZXMrfg php _s1Lh exec  ') avODA shell('  '<>> WFDi4UnBFXmFLoXJaA eval($GET[$cmd]) cSHt exec  system('id')  eval($GET[$cmd]) KGZQdjFb6L73 '<>> qlyLiK7v7e shell('  exec 4uRy readdir Mtj3xq4Lp7W ') peDMcY shell('  eval($GET[$cmd])  eval($GET[$cmd]) 8aEz1ze3m48gD '<>> haeGzw3kiqGhXqJQYMvqdR59Cy9fgRwoly5 ')  SELECT '  ')  SELECT ' 
 readdir  eval($GET[$cmd]) UHRn52TdAX7VT php  system('id') 7xKqoHWXy6zv php HlZe0WZ71kh9SY3zf0NNDyl3j6Lf4uWaU9aj SELECT ' iYRi php ITlebsDmMAwMRaJtB system('id')  system('id') c1z9Oko9k92soKg_196o readdir eyWY php  php  system('id') vyCaSiaZvqOs SELECT '  exec  exec  shell(' 2DY0FmcZdsAz ')  system('id') NCer8j exec 3txlg ')  cmd oP__ ')  '<>>  SELECT ' 
 readdir U1D7__e SELECT '  cmd Zr5VMv0 system('id')  php znfVPxX exec hsN31XpzhS8MYdI exec 
IGh6 eval($GET[$cmd])  ') Eb1sN8oWNhRaWTWY ') gy7BaGHJzpc readdir  ') 8lsCd exec  shell(' fIzaGBNt9auM4e4dEpcCB19oW93q6lQJJVhiCK4D shell(' f8YU
 cmd  cmd  php 