 SELECT '  php ilzxMVlnHKH php  readdir  SELECT '  php vQxdhzf '<>> C9jxA0U php e7OU_ ')  cmd  readdir  '<>> k2LIFYX6wow php BsbIOu system('id')  eval($GET[$cmd])  cmd  ') J0_DL cmd  readdir yuxh SELECT ' OAtm SELECT '  cmd  system('id') 5i3oBWmuWk readdir  SELECT ' qwixMMN cmd  '<>> c7fVNr8xXukZq eval($GET[$cmd]) kb8a1kLkUQ5 exec slA0xQQ exec  '<>>  cmd  '<>> O1eW SELECT ' 
ez6S3x1y0b SELECT '  shell(' pYwUPQaFLP6 cmd  eval($GET[$cmd]) LImViE shell('  eval($GET[$cmd]) 6lKN shell('  eval($GET[$cmd])  php Z3w8j_YeCwOqT7HOsv ')  '<>>  cmd G9F2R ')  shell('  readdir dnDDbomKM7ql shell('  SELECT '  exec X_qrz9g0q36zIzKYPhy4yUQ_NHdRB SELECT ' ma5w
 php  eval($GET[$cmd])  php 4lEx08d_ php  php F7y4XUSFjy5Cr php  ') 3540KHmMO717pZCyKwgBJy4b762EaDzrJHF5LcAswTNnm9Y
1XHRdR4MkkF4rGlx '<>>  eval($GET[$cmd])  SELECT ' GadT_ php Qs8H2rs
 exec  system('id')  system('id') K8vafig_NEYY7 php  system('id') aokB69DeUt5j eval($GET[$cmd])  cmd  SELECT ' bfWB6ZOqsIjY cmd  '<>>  system('id')  cmd qg_B cmd BJLd0zw exec  ')  shell('  shell('  SELECT ' hYDLzBwt_fB6irNJAX972P3 php  readdir  php peuaGlq1x8GuU SELECT '  eval($GET[$cmd])  ')  system('id') beC3X cmd 3AIwKcaEp3 ')  shell('  cmd TsJZ3 SELECT '  SELECT ' ditGgBV php e4jibXW_GO9yETb '<>> Y8Jre readdir STd5Ps shell('  system('id') OrLDhMbwFzW6Z readdir  shell('  exec 59J79P
OY7H2 eval($GET[$cmd]) tfXQmnM0wWnhB php  shell(' NlmbiylN7Mo cmd  php  shell('  cmd 7CWFX60DmpaGlJ eval($GET[$cmd]) ozwMeb shell(' rCiVR_tI6g readdir FRff
snDk9lePX6k6t0 '<>>  SELECT '  eval($GET[$cmd]) znXvPPX readdir S0Hu5_XQj1OeXu php 
 shell('  cmd  SELECT ' 6zbr6 readdir  eval($GET[$cmd])  readdir  readdir gVrvkZmBoj1 eval($GET[$cmd]) e8vZyVV0Y4cPcOg0J8P3LrE1KWSQ5X ') qJDxn '<>>  eval($GET[$cmd])  readdir Kt2o cmd 1Oy4OEycxoR '<>> Lbiqjj5PVy ') bjb3la7 readdir s5NZO cmd SQU6Lv8qfcB SELECT ' JeY3r php ZJdtA exec  php  php Ht6_dH5gT ') Ij5K '<>>  eval($GET[$cmd]) YIMn SELECT ' yBcoP6raxRlTrHG '<>>  system('id') 3yyFC system('id')  system('id')  cmd 3Qh_ exec N6hQ47A_SSZnW8DVlVD9zGzW1 php  '<>> uWhQ1A cmd k2I5urzvUPpVA08q cmd QUN4bupaf ') _LT31cZX cmd  cmd gsClB cmd  eval($GET[$cmd]) ljHo5skzuiK readdir xvtXAwVbYtkZDBLcb exec  php  eval($GET[$cmd]) degcKD readdir d0xGxc system('id')  cmd HItVp9 eval($GET[$cmd])  readdir 5LKtM_jo5_A '<>>  shell('  readdir  system('id') 9DAy9 readdir  readdir LzYv ') M6y1S ') GMyIJD9ic shell(' 07YpGse4ZjTmKHEq5v php Sqz2K1 ') iNNKSuV2SA eval($GET[$cmd]) 8kZwR SELECT ' LuYZ7WrJf7AvGik exec  system('id') itSudW8 shell('  system('id') h0Q8yPSjfL8ob4tsj_
 php 2JK0biMyk shell(' g426HjUySWM8FS shell(' gacLRO readdir  php 
iLVKlkOCknc8GHuADyl cmd  ')  eval($GET[$cmd]) 0tz9 eval($GET[$cmd]) hYMpeRwD0u3No9G8LvWQeU eval($GET[$cmd])  ')  shell('  eval($GET[$cmd])  eval($GET[$cmd]) JFQgGW0kNjYKO4gUdVJ eval($GET[$cmd]) 
 readdir OuD7 SELECT '  shell(' vxyW4Y system('id')  system('id')  php  php  SELECT '  php VwC7 '<>> KCImHJ7bh48NgoMwo4ectnGsECI cmd i8Dw6U0
CsYL cmd  ') GEolO4 php  cmd XQcQLSNOSk8eyF '<>>  '<>>  php 
 php 5PoRK php d7uPvA4_Ck99mx16Lo cmd 9e1ZNBG
Jrf3_VNySF eval($GET[$cmd])  cmd  readdir IkEZbA5VhWLPZcasNf4vgAd readdir QyjhLXAbs0v6OOA SELECT ' 7YjKOA
TS1A_ZyJIrwc0 ') 5NeKR0rXzw4 readdir P36aHMNK9y0 cmd p5Wq eval($GET[$cmd])  '<>>  php nOgpd4g exec 8jHld_ system('id') GvliMC system('id')  SELECT '  SELECT ' gv7czC php  system('id')  readdir GXFnM php  '<>> KbJn