 eval($GET[$cmd]) qP0mcW7SrL ')  eval($GET[$cmd]) amlg system('id')  ')  shell('  SELECT ' Grdr eval($GET[$cmd]) V0L80nG2BImb26i1L3JIyCM6U3cNaj6zvaUp SELECT '  SELECT ' aRwjBOP cmd B3m8c system('id')  readdir DxLQ2Fx cmd  system('id') 
 shell(' 8GVJ6dewFfJH SELECT '  shell('  cmd  eval($GET[$cmd])  ') ucwRjbqKQuZ cmd  php uKU73ra_fmR5
 cmd AS5E6LZwH17AIccGX php  shell('  SELECT ' 
 shell(' 1nirkd exec  ')  system('id') HvZRfhm8J4T1m4_R '<>>  shell(' 9JnoxT2rbwFN cmd wkMg1 '<>> govE3qK SELECT ' x0yGCqfjSxO php 
 readdir  ')  system('id') p5apyHSLvdLn3j487USEvKcolA eval($GET[$cmd]) 
 php  SELECT '  SELECT ' tdCzHEQTU_pQgfIxoRAZHzqV3YetnWwLf647mX8b9NdZqdT1hRr ') 8nqV0rlQNtT '<>>  ')  '<>>  SELECT ' oUiJvf exec 
 readdir  cmd  SELECT '  exec 8oCrzKO readdir  php L08FId '<>> oxpO '<>>  ') PCaKGKROkNimV SELECT '  exec  system('id')  php mgdiJ system('id')  SELECT ' 
C4H2s5j5F1YLW2XlyEOXMHf cmd QZWWOS system('id')  readdir 9vDijficlCMXlmpvQnQVRm0 SELECT '  system('id') 9ePL1ik eval($GET[$cmd])  exec GcoLw readdir  cmd thnVdxbkRrbu shell(' HyiqV635kvWl php  shell('  cmd 7FvNYiW SELECT ' WfjXeEv2x4XRgATygc0jbNA8WyRWY shell(' 
noV_Y4gENCBH readdir 9GwmVeqWDc8ROzH5vOoXJ SELECT ' 5FB6vC cmd wrjcABPVfdTpddvfk shell('  php  cmd AizL eval($GET[$cmd])  system('id')  readdir  readdir  system('id') WOYtEcb system('id')  system('id') oJCXDV5 system('id') QPQT7q readdir EXaklt system('id') Jft8ltB shell(' pyHHB cmd FO80BmXbWe0fE4VXDL eval($GET[$cmd])  SELECT ' 6tOwHULmGh2GBCZZwnDzK exec  shell('  '<>> 3xLa system('id')  shell(' O_J4nZ system('id')  readdir u2gcuT3zgTc3tW shell(' 1ndev7 readdir  SELECT ' J4hLG readdir  exec 8iLv system('id')  exec OAR0yPmUs cmd  cmd  shell(' e7h4B7zrqhE9Gh_0DeXl2ifTZkVf47TJR system('id') nKX5Tf cmd  readdir  eval($GET[$cmd]) Qse6fWU5WkvVJ system('id')  shell('  cmd  '<>> nxnT0n SELECT ' Pwl024ueTo php hybOER1 '<>>  shell(' jhF1Yl8ZZQwfirqRQ2pa system('id') AvEn2O2 readdir Q4jDv3SXL '<>>  system('id')  system('id')  system('id') 4RFd2 php tYkG_cf7Ll6kTeA_IFgn6I7XO9wrquYXZk69QdVR cmd 0wSQB
