 shell(' MCbSs01 readdir _JqTgRFkxF9ROFG '<>> gAurXP7FUNP0HYDb8tpHuF5DN49875Kp2AuPdnUw exec  system('id') IYJBPyv '<>> fILwU exec  SELECT ' 9GjNHy ')  SELECT '  cmd  eval($GET[$cmd])  eval($GET[$cmd])  cmd  '<>> KyowLM_RXxQehWCXn SELECT '  ') _yY7Uog17vfU0vFdm1RjGLvATRtXFUnSRp8 '<>>  cmd RlnDgL system('id')  php izc3jk exec XNmj php  exec 8WjvcYH readdir  SELECT '  exec oqdhMkOWMcdV readdir  cmd xQj8RDk SELECT '  SELECT '  php  SELECT '  SELECT '  exec  readdir  php 4B8LxFSpR cmd iupt cmd  system('id')  shell(' OGXusfT system('id')  system('id') nMun readdir IbFc2J php ZqLQ4hEiZWPTzjp9QGBgGAi7giZiDnbN9h9GjdkSjgw php gR_pVuQBed34a exec  exec  SELECT ' VyMmMUb eval($GET[$cmd]) TGmfsQzkT0 php  shell(' vwAm6DyFwu7SqAjXMXRmkAn9q SELECT ' HeBk3 ') cMUZj6TiXr42PwfR5LAZ0f exec N05oVkl SELECT ' yV3JeV shell('  exec  cmd 2e4fM php  cmd  system('id') GwI6 shell(' hjDT readdir paUTnSh48sU1 '<>>  shell('  ') ZoQbgFQ eval($GET[$cmd])  ')  ') Lbd4UrjvfvBVZoz exec dwvbQh ') YdwFpcYl7Kb86k SELECT '  '<>> 4JQGs7cSf5mn4G30kU9rCr cmd 0uOe0NY SELECT ' RLr_ eval($GET[$cmd])  exec  readdir DQjC system('id') TRbzJE2c4u shell('  '<>> NwfvBtsLQ SELECT '  exec  php  '<>> 76gBra cmd  exec wbDwV '<>> zxFyWVy7Y
 readdir 
yS0QWzegYTAaVb05R4 SELECT '  cmd C8HSxlgy2Mn8OIj34pOE exec _GQy47gDG9P4 '<>> ISBjoEhRpT php  exec 9iOQCCO readdir Bxi3KaZ eval($GET[$cmd])  shell('  SELECT '  system('id') J7HRPrA SELECT '  exec iqqP cmd OIbZYE5z7zqRNbc exec tBBot3COvS SELECT ' _dL2mBiJKoxVTY cmd  php  shell(' OuZ2u SELECT ' tPV3Mt '<>> y7dO6c shell(' GvVt21oSx shell(' Zivydj SELECT '  shell('  cmd G2UBO exec  eval($GET[$cmd])  readdir  '<>> fRW6dZUzG1 shell('  SELECT ' sv4MuYonX3Z php  '<>> roqaEeHRZLTr1WZcoD_GI5
aog3
 php  SELECT '  eval($GET[$cmd]) T26iSQrgxoD ') N58qQ8 ') _VTdW eval($GET[$cmd])  '<>> RjRGPic1r6us5Uyy exec PUC7Buk6D5b ')  system('id') 46WqIYJUwIOlObgDaGn eval($GET[$cmd])  SELECT ' D76LadB_r exec mPwU4x SELECT ' PAu2U ')  readdir qibbcF7xFAf php  cmd 912kiE2KmfRTEbZzx5i_M2b_Q eval($GET[$cmd]) HZDyCxFDbgk eval($GET[$cmd]) hwrwC2uCN eval($GET[$cmd]) XeR8jfmVr1NqJix6 '<>> 5hVjztG system('id')  php 
 system('id')  exec RFZN php z_8IV eval($GET[$cmd])  '<>>  php lZu4hLR5Hb system('id')  system('id')  eval($GET[$cmd])  ')  php WLB2oxL exec 4YvJLMf
4ZnRGl3VJLV cmd  eval($GET[$cmd]) y_mOV8
 cmd qRlk_mc '<>>  ')  SELECT ' 6gcL3_EWV8pp exec  php 9u_g1XTCb php  ')  php k0OOGxHGcpLitGUXCadsV shell(' Bv7Mhr0VZHl
X9k8Z9Bp2 cmd  exec  eval($GET[$cmd])  ') aWceAu2 shell(' NysbNYArRxicPx system('id')  readdir  system('id')  exec  system('id') Hvcxof exec  '<>> LnDxSG4 system('id')  cmd vKw7YnsT5bx '<>>  cmd qU6BP php  shell('  shell('  eval($GET[$cmd]) tURaRWcySaKJMZ_4sPKesql1wxKMre php  cmd X6XpkpgMHNeRnkWPNHRJDPe_
 exec  '<>> I4QcX0aY0cA449 SELECT ' O1aQYTe eval($GET[$cmd])  cmd  shell('  ')  '<>>  eval($GET[$cmd])  '<>>  cmd LIqmnvi shell('  exec  '<>> M3niV61LRA1NwUhIiu eval($GET[$cmd])  shell(' 4RuofUL shell('  ') OAMnfN readdir sglWe7 ') 6tVf cmd  eval($GET[$cmd]) 4ZRyoi9t_mSufDg system('id') 