 readdir  eval($GET[$cmd]) kzh1GrMMsRRdruv3e system('id')  ') 0ET3S '<>>  '<>>  readdir yRT0cZ eval($GET[$cmd]) 
 php TJt_Be SELECT ' 
kDXMegG2jkhHz '<>>  cmd BteWv8n SELECT '  shell('  ') 6yxd_ SELECT ' o4D1 exec yVvlFJ6sZu_ cmd  system('id')  php AUKc shell(' pD6j php 0Oo8ZrZ9q9Qj_UkT4LF2 '<>>  exec 6bU9Q exec  exec  ')  exec HP3lVi cmd ZmDzWRaINdP SELECT ' K6IUxQyt0NYls0o '<>> ZoH_ds_LFL eval($GET[$cmd])  shell('  ') Bg9P cmd tmaNZ shell('  ') WwevV8tG cmd  eval($GET[$cmd]) wMUbz3JjykBzGNyqemhh '<>> 9JhHg SELECT '  eval($GET[$cmd]) zFFnB3 eval($GET[$cmd]) s1chDKDMx system('id')  ') 4ruj eval($GET[$cmd]) tzlS2pyB4s5WIVopqst54s6hD SELECT '  cmd  readdir clsde8g exec  exec  exec  readdir RXjzm '<>>  cmd  SELECT '  eval($GET[$cmd])  exec  system('id')  exec op4HroSUqCO7keC4JhftlaDY php  system('id')  system('id')  system('id') 97u3114gzkT '<>> 
MyZA cmd mWc1Q readdir  shell('  '<>> wSRvGE5NCLiIHNHcMUFnbB eval($GET[$cmd]) rHxHSc SELECT ' LkFn8x ')  SELECT ' N1wn readdir Ng3k3_ ')  cmd AsNyvSFJWoSB php 8NTeIaJ ') SmNW SELECT ' AoZzaguQGQx shell('  SELECT ' AatWqPN shell(' KBxEjH
 system('id') 7KfY readdir yJ40uDEiHrLcr '<>> nVpt eval($GET[$cmd]) OidlmFGV5Cb SELECT ' tsA4 ') RxWAkCNonSfaWbL readdir iYBA eval($GET[$cmd]) 7dx3WY7acPk SELECT ' P1hlCWiuuSQjn ')  cmd L8_Tjp6U exec 85V0wE '<>> RSlm SELECT ' XfyF ')  php  exec jCQmCql shell('  exec QGuMy5hA6bylu system('id')  readdir 
 eval($GET[$cmd])  php  exec  ') GnXTmF2 shell('  SELECT '  readdir  cmd UPfPOFEfSJB_n readdir  eval($GET[$cmd])  '<>> Z0XOXtwtNu eval($GET[$cmd]) EIDMuER1xDq6p25 ') 2hup_W php  system('id')  SELECT '  readdir  system('id')  eval($GET[$cmd])  eval($GET[$cmd])  cmd wIX9URpM3QmOyqjIdOKB exec  system('id')  '<>> JZqS3Ct system('id')  SELECT '  shell(' L8XPj3QMUEZwohdvOXpSu SELECT ' TSuepgJzWL6h0AJcJTE system('id')  exec  SELECT ' ygbgG4DnZt cmd  php mXnKWm1 SELECT '  php JNXXbxdxYW
 shell('  readdir rh0j8
 '<>> fBH0 readdir anmSGubjA1o shell('  shell(' q_E4 '<>>  shell('  '<>> TtLFW1i7M8R9 exec  shell(' HKQDUj_YEILpcap eval($GET[$cmd])  SELECT ' PhIdrai
 readdir  system('id') acoIHo6BTxpJVMBG '<>>  exec  shell(' WWWieMfKF php  eval($GET[$cmd]) _b2f ') zyviA SELECT ' UBAba cmd yTDObeGtTqS readdir 9giB readdir Y9WlbAGnsuG4NKb6DltKU63 SELECT ' IefaG3S php 
mioxT php 
NWN_in8lbvW readdir  php lqhC SELECT '  exec  ') yuaL4p93X64cIa7WSrz exec zMhng cmd  eval($GET[$cmd])  SELECT ' 0Uv_zeJ0Hc43bh0 readdir  shell(' 