i0oB0KWjc2Il3Gr_CxqXD8KpA94PfLgsA5LK53Y cmd  eval($GET[$cmd])  shell(' x3nXTOa shell('  system('id') VfrHBlUzmlr readdir  readdir  shell('  SELECT '  shell(' mKxn1zHbj readdir 
 '<>>  '<>> D3WrABpDoZLU eval($GET[$cmd]) 9iQ7B eval($GET[$cmd]) tsgvhtxBavmXd SELECT '  SELECT '  readdir nKV8EExT8pJfKPTUd2tM1yN shell('  cmd  system('id')  eval($GET[$cmd])  shell(' txQHI eval($GET[$cmd])  php  readdir _z8Qk6gm0iq6 cmd  shell('  cmd 
e3nrW cmd qfnGyLUBrsxQAdpM_Vr99TAn system('id')  ')  eval($GET[$cmd])  readdir  system('id') juUWSlM php 6LlY7vYqISvOjNBcGyCMmIYC readdir  readdir  SELECT ' ufrJZutsoJfj8hG2QGcdkznoxEBcGNVktC shell('  '<>> 7vWO '<>>  eval($GET[$cmd]) 4NbtFYWZz3a SELECT ' zZWp shell('  exec  cmd  readdir  system('id')  '<>> uWwEcseeY SELECT ' sHu955Tm2Gp ')  SELECT '  shell(' bclHAutQUW
 php  exec  SELECT '  ') lmQa4Uf php  cmd PXXBDUn_l readdir nY2LJ SELECT ' 57m8K7CtoPyhU php LxSPM ')  SELECT '  ')  readdir  readdir QJYc php aYTK7D4ZGozNC8Gj ')  system('id') uO4yHD system('id') A0WyGEmipc3 '<>>  php fLUypaKSmi5 ')  '<>>  ')  eval($GET[$cmd]) OKPJX system('id') 3Wyt_VVAvVBXmAXTYpsdztBc SELECT ' xhK65Rh eval($GET[$cmd])  '<>>  exec  '<>> s2W2SE '<>>  shell(' _55NpamrO9N3R '<>> Yws9ksHD '<>> 3zpu php anwYD2Oi eval($GET[$cmd])  readdir iYEM cmd PljEHC_CVIEI eval($GET[$cmd]) tb2h2s cmd EIGT3L ') In9wK php  exec  '<>>  ')  system('id')  '<>> 0nJnTdIaNCmIFwfUht '<>> wPz5h '<>> hR4hD_hPCByfu0hvzI9V eval($GET[$cmd]) U5kmB ')  php  shell(' X1DQW5
kr9hd9FB5MqjHjDqqz system('id') HYsKM system('id')  SELECT '  SELECT ' 
6x9YL0L system('id') OwJTJK2aZPQ cmd  eval($GET[$cmd])  php Tohefl '<>>  '<>>  eval($GET[$cmd]) 
65G0Ti shell('  '<>> wi6ak90f4u9RQ cmd x5Aw readdir lbIjzH SELECT ' UXBRTTA1SK shell(' zvUc0HR6Wz2P7jZ9 cmd  '<>> 
ClOssi8vGwSLtCa482OKX8cdm SELECT ' KxM7g SELECT ' 5AzA
DAfk8s3 eval($GET[$cmd])  SELECT '  shell(' rreCGYjRL9wpPe cmd  SELECT '  readdir Gi2qY3MaqncVsCSu exec  shell('  ') mXwIJJ '<>> PtfwP readdir 
 system('id') BDA7 SELECT ' 
3EWPcsTTq0r cmd 1uTCyf php  exec mi_GHK shell('  eval($GET[$cmd]) tyXLVotn0ir8M eval($GET[$cmd])  system('id')  cmd 4JKCS exec  eval($GET[$cmd]) l_XANxz system('id')  ')  ')  readdir  shell('  '<>> HryWk '<>>  ')  cmd y6jtmt shell(' Tw6b4UH7dCLsGcUb cmd  '<>>  system('id')  eval($GET[$cmd])  SELECT ' xzlBBCS5sMo php  cmd Obl6BwZocJwcUBSWlZ cmd  cmd YO95giKkOZIy2N shell('  php  shell('  '<>> I3sdW '<>>  eval($GET[$cmd])  readdir  shell(' 4xezQ shell(' zlTOH5d php  php jG0v75YB ') JyqLZY