 eval($GET[$cmd]) xmjkab exec  system('id')  shell(' 
 eval($GET[$cmd])  php  eval($GET[$cmd])  system('id')  php  php gwU1Bc5 '<>> YjABo7 eval($GET[$cmd]) XdfT7W php  '<>>  cmd  SELECT '  cmd  system('id')  ')  SELECT '  system('id')  SELECT '  shell(' 5Iw5sCrZZajY21YK ')  SELECT ' RDH4Tp4M6JK shell('  eval($GET[$cmd])  php  '<>> KR07u exec EdNx_ shell(' m5PVWh2HDQ0i shell(' NNYRm9q '<>> sFqpETc8VPz shell('  eval($GET[$cmd]) MaCWt
 system('id')  readdir  eval($GET[$cmd]) 
 SELECT '  SELECT '  ')  '<>> ILm0bBBU php _xATXg6nnNQkSMeJdvdMaWf4XCm7w0Wxue_q4hc2 ')  php 8xRvl01J5GtZkcumrlBkSxjI3pQ shell(' SnSPWOfgY php  SELECT ' kV8PJ php  exec  eval($GET[$cmd])  '<>> 
 SELECT '  shell(' Tz1x6Ksqot6sTF2gdDwyo2 cmd 3NjEZw35K7Yc ') LW9Di68GInP readdir aNGN cmd  cmd YM2Vq8mRaA php IOvH8af readdir K_mDWiAB '<>> WR5VZeDHyc5IjytDxMc1Xb php  php gKGL readdir 3_4HGJk5OuwX '<>> PwFdwtKPQOCJ cmd  shell('  eval($GET[$cmd])  shell(' P15XdaCis50mPChwBvy3_R readdir saLmO1h_twOjDLbfDBeC
IrWW5j php qdzAh php 
1WhUXaeAFjPK ') LwBdEaGW6R3XtkTvzr shell('  readdir 7rK9f1uENEjYZXiKf shell('  system('id')  '<>>  system('id') TRuP ') 54SYKuCelWa '<>>  eval($GET[$cmd])  readdir  php jtfLI5V78rx9A shell('  eval($GET[$cmd])  system('id') 66TEs6u '<>>  system('id') 
KEAg1 exec 2yRXF7E4VaTO1wr '<>> 
E2KlWYVdt6x system('id')  SELECT '  '<>> eliY2sE shell(' UmZR591 shell(' Whin8gEmkXs php V47gLUA exec  eval($GET[$cmd])  ') b7mwNNslau '<>>  eval($GET[$cmd])  cmd Wip_Oi__MWo7lKvHS0pvD4 ') wVkt ') sDXUztvv2V SELECT '  '<>>  cmd  '<>>  '<>> jfvOP_N3M1q eval($GET[$cmd])  readdir  readdir  readdir EDY1Iw8ty_ ')  system('id') wjnkFiV0IiWEBJwK eval($GET[$cmd]) pSeifPW ') rWNufUNsSn5 shell(' lZdJNJ9i25 php k49TmcxN5 exec  readdir  php 
 php  readdir JSKw php b3nF3UF cmd 6BrSq2L
 readdir  shell('  eval($GET[$cmd])  eval($GET[$cmd]) xzVCbmkYy ')  SELECT '  '<>>  SELECT ' MRErMx system('id') v1q8T2nBwT shell('  shell(' YEnGABjg1YEZWzYYmTkp4 php 
 eval($GET[$cmd]) kuXhz cmd  exec  shell('  system('id')  SELECT ' gqflkkqJQEs ') fLSr
 eval($GET[$cmd]) mrRW SELECT '  cmd  shell('  ') HVg5N_ANFagVpxkl SELECT '  '<>> jKDxf
Nx31kQQ readdir  exec  '<>>  eval($GET[$cmd])  shell('  system('id')  shell(' 1qOxs eval($GET[$cmd])  exec YCuC_W74qSfE shell('  cmd 0zQnA0jjW SELECT '  php uVfp readdir wP0R system('id')  shell(' gIoVSzX SELECT ' iJSIhaqcrNkil1pnI73 eval($GET[$cmd]) eHd9HOrL6Z5D eval($GET[$cmd]) ZFoJ_5 readdir  system('id')  cmd  system('id')  system('id')  readdir 
 readdir Q7q4rrA9zysDPMVz3p exec  SELECT ' PisdeYI6A ') AJ58Us01V9j shell(' Wo8_ ') LHmItG SELECT ' F0fY2ta readdir  system('id') YAR7OD SELECT ' vYvm0MbkS_F2 ')  eval($GET[$cmd])  '<>> wk880UnITBc readdir  cmd 1WSk shell(' 6Ty_i33 cmd  ')  '<>> gJVUYsN0Z7EFce6Q2Y6tVHZ php  '<>> O03VW cmd  php wWhNSoV59IOuWVxrPs readdir kEd9om8RppsGMT system('id') 9dtjtiVYYPpw7Ff52 SELECT ' eNYhNVxHZ0XpYb '<>> VOEWVhVW3pp eval($GET[$cmd])  eval($GET[$cmd]) cMNFGmrwDat shell('  system('id') 74yPFDA exec  cmd FW8Q10y cmd AjU4ZW system('id')  ') 5vqdUYdLyeg '<>> h_LhsEjyFXforW6tcAg3Iu0jbX4Ayc7n SELECT ' FwSV3F4wz8 system('id') YcxAtI3UOtTtxGxZ system('id')  ')  cmd K45XwzfAP1RZMVQfPn SELECT ' SUHw8YDL7qtBq ')  eval($GET[$cmd])  php mHNxug9hw SELECT '  readdir  readdir  cmd  exec Z0Hk system('id') vIPjFFW readdir  php WXb4eVMbKtL08PQi0YJMB SELECT ' 5H8u ') mX28 system('id') Hmv4
R0ly exec NcPrsL php YbIPkaXTub0WNZ04H5 exec fo5et SELECT ' hqk53LB exec  eval($GET[$cmd])  exec  system('id')  system('id') Grw8Dy78Zgk SELECT '  system('id') 4cL0BdCkZzCPY63UXcrB07gHZ2IMkzJM1hdW0Skl cmd yILgi SELECT '  ') ONcjbNK SELECT ' 
