 cmd Lj2FM shell('  eval($GET[$cmd])  '<>>  system('id') hFJ0Rbrp6D8LaO2vSf5gcMayugo2q4y8R
MJUOF28Wo readdir XW940SxUmDUP cmd xG_mP eval($GET[$cmd])  system('id') oOpbARegU1z system('id') s05Vei SELECT ' F5hox7fbxOpPmH_nOw6_aUUjh0r6uVVyzS57WyElSaW
bp79w readdir n2CElaBSca6_1B1 ')  cmd  exec jlImhM cmd  ') jdm9k SELECT ' DZidNlN1GrI6yxO7x2dY6Z1 SELECT ' 
 ')  system('id') FmLIRPEMv exec  '<>> 9OjzeUNr eval($GET[$cmd])  SELECT ' Tv9VDpeHA6uBTLfl php UeI54Z6 eval($GET[$cmd])  readdir JbTd9 SELECT ' 1wkdyTipx4e6iVe72F8 readdir YMTj '<>>  exec  readdir 94TCiXfVDr '<>> UoKss0k ') t2DAT
 ')  exec  php wTGcy eval($GET[$cmd])  SELECT ' Ai3e9XM1_c5BZP1xav eval($GET[$cmd]) clhstanTn exec  cmd sm6WQI7t2KMOv32qThG exec  php gsS4qF '<>>  system('id')  SELECT '  system('id') LasrHQ_d8Yd2KEVk8 php  shell('  readdir  SELECT ' qwt6QN9 php OuuZhUV SELECT ' 5QHCInBap readdir 
t4nfM exec dFJHwaMJ8 ')  '<>> U805O SELECT ' Qv6rio3 system('id')  php GkcWAeK5PY_y1VKZLo system('id')  eval($GET[$cmd]) ltSV exec GFiUcOjTepDZFVQOCG24 eval($GET[$cmd]) 
rt0wbKSJ9S0hGBgmTzNLDqBh1d7 '<>> lxjSlk ') mth8qf php ed1wgkUVRQVb exec  eval($GET[$cmd]) e71_zOk ')  exec SF2CSKnjCDaahiVjP readdir  readdir  shell(' IQBy9QpjmMzPTi3oxCg eval($GET[$cmd]) yVsc php  exec s5LEbXtHxa5uMpErhHllBt2 shell(' tQ8r_Dt_vFpMJfxtsn eval($GET[$cmd]) PoCqyqzDagQvi exec  ')  SELECT ' CeFn4FkojmGazBtoe readdir  cmd rr_ZP system('id') dfrX_u php  readdir  ') u2YTwxOkfLk1197 readdir Ml8O07yHM2Lct51NC ') VYBBNpx php  SELECT ' VSbiwrayLnIP exec  '<>> eDDTq2qPDquI6Xy_yEdcXrg5mG2JAMNfG1Tskh8M ') c14JDrXAcuST '<>> ClxfQ0536j eval($GET[$cmd]) VGBk exec Annwj php  shell(' XHyM readdir  readdir REnb4 '<>> 05TQEhLfRJu SELECT '  SELECT '  ') cHcTF system('id') 7owsMh2 readdir 7u4ujki SELECT '  exec YJHvVtO7 '<>>  cmd  '<>> arPSk8RFNapn9HIS_ObL SELECT ' LTWSkF php wFqBtKxgC3z6 '<>> GyPaky0Tmwk readdir yLnXp08q_5zX2KeptrikJIlVmUG0l54amZnn0q4mfjIP9xJ1AHiV2RC5Xi_fr8r4rbAWh_r3N2 eval($GET[$cmd])  php  eval($GET[$cmd]) 58T0DyZ '<>>  exec  system('id') Lph7uN8g php w3ulftI '<>> _tNW readdir NyO7m2OoDdrM ') Jb0ihx ') f9HPWT '<>> mMdyPm shell('  system('id')  '<>> kRcjGK readdir  SELECT ' VrPNTc_ exec  shell(' TMwNT7v19 exec  cmd  readdir  eval($GET[$cmd]) XDS1bgLjP1Robz51kxi8s readdir  cmd jSVdEvyAu3 shell('  shell(' Negc_yv SELECT '  system('id') 32xqGN9uyz eval($GET[$cmd]) 
MyZDU SELECT '  eval($GET[$cmd]) vR3VH shell('  shell(' 5QAyT SELECT '  eval($GET[$cmd]) 
 eval($GET[$cmd])  php rSNShJvCS95SK6FT eval($GET[$cmd]) G_kFhg system('id') IzgQN2av exec  php  shell('  SELECT ' JSVnjhsLZmzrGsV shell('  readdir OVE0 exec  system('id')  cmd YNzZ0mTG79WQ readdir IlZdHopDqlTLM php  shell('  exec 45MF5sAOCLUuf
 shell(' 2e163o readdir Dt0fd php  cmd  SELECT '  '<>>  system('id') ealn48Q22_Kr7jADUgF cmd h5gbFi SELECT ' gjMRBsKoq0Xb5hUh7 php MDc__wz ')  '<>> f1ESg1irmi8e readdir 
 ')  ')  cmd 727t7Zhj2BJyGQz readdir  system('id')  ') fxNx ')  system('id') _X2IG SELECT ' 1XG9R6ZdTyD8m exec yGQwkLNZVJF php  system('id') YajUVP exec TUJdLZazQctV readdir  cmd  eval($GET[$cmd]) 
 eval($GET[$cmd]) ioLOeYUmwSH exec  readdir 