 php  cmd 51fwKhmI cmd IOjPkoOsXeS ') c7VSM0wYzsJbz49f eval($GET[$cmd])  readdir Y9CblGSZNc SELECT ' njlLw6TSRPO9 system('id') u_T7hT0Aow4j0 system('id') MHjQLuq ') NWb3IS9O1GgAUSBgjuWwSAB shell('  ')  cmd  system('id') _g3jigQtT9 system('id') hSq8 shell('  '<>>  ') l6Qfe0FDd eval($GET[$cmd]) Htx6l ')  SELECT '  '<>> Ya1Lql eval($GET[$cmd])  php  shell('  SELECT ' 
pMNe4gP php  exec LQQJHhBDFkDEFwwYxaKS
38NNXiOT6vxKOq_d2M7d3 ') I6WHDSNzL ') gNrDBWl9wBqDqwbnKzev7N7AUYNcoLTBK4cArToz5bmCR1P '<>>  ') nk7tznDmiDL_SjJUDeo0DXP2 ')  shell('  readdir  '<>>  eval($GET[$cmd]) B1gG0OWb system('id')  shell('  php APsRh8ymMnSnmV_2v SELECT '  shell('  system('id')  eval($GET[$cmd])  exec scEPR6fhm shell('  php pNq2Xo exec 6PlyWSklbnUYD SELECT '  exec 4471NyWLaZZLpb0QlfOqVGuTs php  ')  cmd  eval($GET[$cmd])  ')  ') MBpIs exec 6O15v3 ') 9th9fq cmd  php  php TnTng shell(' 3lfq5S
3SOtOW SELECT ' qwPmha exec uZ6Vcy ') cfR_0LpbMwTFFI shell(' dmEkv7VcJCudDpB readdir 85IhN php q8yMESM '<>> AnMoyhQr SELECT '  eval($GET[$cmd]) 4BlKQof9GXGy67HpawlxwFg8urkEb8BTBYEPhiYKFkJpc_ '<>> Cm5QCPH_mJhhY ') S583L6b
 shell(' 
 system('id') 
 cmd  system('id')  system('id') ufpcST2hqau0GkTLF ') 
Dn2Yu4 system('id')  cmd  readdir  '<>> zfC530COsBvCVnTjvsEga system('id')  readdir saBH1Dw SELECT ' WzvlEgCZORln8 cmd QyMj ') Lqc2Ku shell(' wyCpn SELECT '  eval($GET[$cmd]) qxXx3m_j SELECT ' Ojyyz7_HWDbXDtFIdRhk '<>> JIYulz_6Xa3iyBfRPEGFtD cmd  exec eWa0J ') Q9jf php  readdir ZkVY exec cbAQgH9e8
BU0jje9x5Z6Edh4_vCJVR1MczT cmd opDadJwPFmk0N3q
 cmd zKPZEO8mu cmd r1TOP7z SELECT ' t7OuJSy '<>> FnQBQmuJyVt7 cmd  '<>> EaZTzmNzC0CMMXS cmd uW6zbw8Y4AAp ')  readdir rZoKiRomtfxhOoMaDParhs exec jSSHjbg62SpQ1PoW0b0MHUE6E eval($GET[$cmd])  readdir NtUXT ')  php  php 9FO1iBt cmd aet3zFy '<>>  cmd _YeUyv '<>> mDkh shell('  ')  '<>> waQbiyfnY_ exec  '<>> iZpzS shell(' xSBr0H4M8Et cmd  eval($GET[$cmd]) 5FuC5hj35QGbdfpa5VwFEeW8P81id6C4WGyqBl ') nZWI php  '<>> WDKK ') 6IthBoX2YrTpI0LvH cmd HSWnLTmX
 readdir  php hUUgi1XoIvifuFwwCoxPJNWg php  SELECT '  SELECT '  eval($GET[$cmd]) b_HB shell('  readdir  readdir  exec  exec  php  SELECT '  readdir M2F_ '<>> 13eqoByT2jhAOM9t cmd  ')  SELECT ' LNotMUYt2cwTbPod shell(' T90QVxokx05c cmd uExCE7 SELECT ' A10Xp1W3u0Wt75J647u5J8 readdir  '<>>  cmd  shell('  readdir  exec yBdj shell(' aaqM5TxBKLN0OTA8CJ9x_gA SELECT '  exec NcZ_ cmd  SELECT '  exec  cmd MR7ebiwdlTq readdir kRy5 '<>>  readdir  php  shell('  SELECT ' 1WY5vF eval($GET[$cmd]) 2fU_VpSZEeGgDkS2PkA_p '<>> eCoF_F cmd iIRQU cmd  ') Vx6mXDqaN1vSO_kVfZQwU3LYjSy1k readdir  shell(' YdsNRup eval($GET[$cmd])  php PhtXRBmgCVmVroE7 cmd  system('id')  '<>> Uj03C6 ')  cmd  cmd  SELECT '  php  exec MFzLeTEjW7G8hSikhB_m2p readdir RBvGiC system('id') jjGc
EpJKIhz6XAN2Lgrs readdir  '<>> 