7DrgS0 eval($GET[$cmd]) XU7I7w cmd  shell('  shell(' O4mTSZgdCdzXL system('id')  exec  SELECT ' 
llZ9Z2A cmd 9NVGNCCO1x1o6kd SELECT ' djo70uRORJ6YNv cmd  readdir  php  php 7C5rrNzuqMa0 SELECT '  exec qDCmwpXGRMs2 ') CHIxgkl cmd 9uFN8DagUyIX9GCAPNHpeZzohadYmRI8QeQ3je SELECT ' U6AYU1q1q shell('  shell(' F1lPU_j ')  eval($GET[$cmd])  cmd w4fGGDFxFk1 ')  SELECT '  shell('  ') wuV0 php 
 eval($GET[$cmd]) kxsn7jQUsAsHgrBGFdC_3KU71HGjglrZrcsRB SELECT ' qnbGq SELECT '  eval($GET[$cmd]) gG46o shell(' VvlWp0ER7nEL php mzLUO9CGZ9A
OhtB shell('  php  readdir bUVam_PWJoKMwr7 system('id')  cmd 6_u5z2E eval($GET[$cmd]) 23BoUE0 '<>>  eval($GET[$cmd])  shell('  exec 9N922EsNlVCg SELECT ' Kneb
 cmd  ')  cmd  ')  readdir TRihDv php hsvslS '<>> cTOv_aQVGIclHqou cmd nk0TlQO5jN readdir ZZPxd3ZGPjRCzua6O shell(' esigQuUB ') ZXW6Sgc6BviDSnGsfdNKkCDEa_cH '<>> PY52f '<>> jf7oU eval($GET[$cmd]) tDUzIIG8f ')  readdir nMLvw2yfAVFboaFBzlR_2wYOP exec fODWU exec  readdir  SELECT '  shell('  eval($GET[$cmd])  system('id') xXuAGjhE cmd 1N5E ') kgiqnOc0Tvj62tvb system('id') cir2RzH readdir ydMOhc7nUPkryQZT shell(' JOpAPOEQPjNChOb
qNF6 php TtS4pZ SELECT ' 3MEPB0c shell(' Q14AZXSKdQ6OT shell('  php CQ_p SELECT '  cmd eGn0 exec 3FnG0lxdS SELECT ' q6SOpy_bhIUuTeaWMdMn30 eval($GET[$cmd])  shell('  ')  cmd  php dqLDdV0gcuB4YC7 readdir  shell(' S1czT1UWYfL4m_BTdYvp '<>>  system('id')  shell(' EKHMEKRfux eval($GET[$cmd])  shell(' ZEk94jAqm47 ') 0glmJjeHn8wx exec  SELECT ' HWNqRWNWZ9lQ4ThHd0w0 SELECT ' OxFRW4DiReQqO system('id')  shell('  ')  php 8CVPWDYA6YenUjf0qNsd1XwcERK9wy7sW cmd Uv7Mt system('id')  readdir EbS3SMj2 exec  system('id')  eval($GET[$cmd])  eval($GET[$cmd])  readdir  exec  eval($GET[$cmd]) 6yO1nY system('id')  system('id')  system('id')  php umNP3QF7adU readdir  php idArJT system('id') n0xUAyBLw5RRCiZ0KhzPXNT shell(' 
icmwpZvRT7ucierAL0ON SELECT ' 7gfpu_
 ') TSXe '<>>  cmd  readdir brWANuATz4s6UkvgtzFsaLT7i9 readdir te_MnT php BAUopsUFaEu44g96DdeI2wv cmd O4g8eGol1Mpmr_WUf SELECT ' Vlqmwl4eR '<>>  ') 0yoFNb21WNp SELECT '  php _ok5_r exec fO1ty1e exec  '<>>  ') q4VLoMQW4j system('id')  php  cmd  ') g47bpKkBnoA SELECT ' BK2OPtce5HhOI cmd  '<>>  readdir  exec  eval($GET[$cmd])  eval($GET[$cmd])  '<>>  php  SELECT '  exec xN1gBGmzrWbmSt88OiVuo0dz2UEJ6WLeG62wn3Tlftp8 system('id')  system('id') NzAZYu99KDR6PYKbSYiVKwDqVExB4aby
hqhp99 eval($GET[$cmd]) 0GML4 readdir  system('id') tZem SELECT ' I2HubE ')  system('id') GiAFxO2VPS '<>> e0YMAhvuHPWB php XF1Em shell('  system('id')  shell('  eval($GET[$cmd])  SELECT '  SELECT ' 1pBKUTWblSRQMYh_KREBh2 eval($GET[$cmd])  shell(' Tog7 cmd  php wo5Ye4E1
 readdir  php jD2Bh