 eval($GET[$cmd]) EpwwdQ9jNA2Cn exec 98vyOaU php  exec e2UBCE php  readdir  SELECT ' eGnnj44uhaMN php  eval($GET[$cmd]) fVsIGm ') uVyzNw6deS SELECT ' HKwfbLW
Po_J8BIpS0Uk cmd 5Cx0HC0ZYmJ1K0NRXpg system('id') BOe2mfsrsyIi1ne exec  ') _BeOcHv php XqJre1G system('id')  SELECT ' 
_l5S77t9ZK6nf cmd Zy3_ktm53ZIwpkahn4eOj6M SELECT ' tqJzp1a4P_9DxgCDIkEW '<>>  cmd bCadxyWrfP '<>>  ') Ljkf5x cmd  '<>> 7gWL php  SELECT ' NZ9XMGL5LmiTwbyvAU php LnGeeESnYIVa eval($GET[$cmd])  shell(' eYinNYNBm1oAdq5h69T5j_8d1O98j0 readdir gBm1 '<>> uGzAt_ '<>>  readdir vxldOvcjFZml5EQ6uD php 
UX4Mud readdir  readdir FyLq9sq1a2sUB5SP eval($GET[$cmd])  ') 5GfM8B SELECT '  cmd aTQE exec _yXh58Xcw shell(' Imig eval($GET[$cmd])  eval($GET[$cmd])  readdir PJgVD6O eval($GET[$cmd])  php Xfct readdir FQBynxLh7WE php  exec  '<>> CpdCIDv cmd X_w1M4b3o5nlfdz1Isu readdir sI7x system('id') 
 eval($GET[$cmd]) i4_H6c6BFb '<>> 
UqQB exec  readdir  ')  shell(' kRyEl6ZVW cmd  cmd ucLLhPKR1T shell('  system('id')  readdir U3XyEYTdctPeTBt SELECT ' pkWvfhG20bHKxsc8pp php eMcZ0 cmd  php  php  shell(' V7vv SELECT '  ') Fpqgw ')  system('id')  shell('  cmd GECUmEcjiKYQaK7 exec TpOtKboZIhYuTyFZ87bfVqF8GxN SELECT ' kIQOUjXbLA3DSoyt4R eval($GET[$cmd])  SELECT ' qrQVizw exec  SELECT '  SELECT ' iF31wXgIb85BGD readdir  eval($GET[$cmd])  php j4Qw2SE1ZS3UwR7zNjpLmvKaOWlfDi3hbpJBy7WDnu15_
Jxz6 system('id') ym1c9R3k_0AW0evL exec pBHT0W shell(' xP8T9wqHBT SELECT '  cmd  SELECT ' n1GYd eval($GET[$cmd])  exec  readdir TFAP92Xn_8oyzXLbUgeYBngcDyvCSRutdDAS5d shell(' zasIM2Bp9LJ readdir  '<>> 
 '<>> qePK0G_5uY readdir  readdir  exec  eval($GET[$cmd]) L7UHY9 exec  exec dFnrwST php  shell(' Pt4MCVyQnQ3gnhdT shell('  cmd  '<>> aN918c system('id')  ') Vlss readdir  cmd  SELECT ' lTTggN ') 824f
 shell(' xFCZvxA cmd mYJM exec 39BNo8T system('id')  ')  '<>> RY790etWrHOVlhgqYotk SELECT ' 2D_8ybbAsg8PjqnL4 shell(' omd4HXgOhhGBN9n3bRuG exec 6iF7l exec RZNTQ6 system('id')  cmd x03wk1dbOwRkdBhPek7pXaE readdir  '<>> 
OFuVw2lpdm1 system('id') KuCNN exec f58hcMK '<>>  '<>> JYmDWcL shell(' YOja system('id') jfs6kUs SELECT ' z8Ku3kl2PIvS5LqQX ') O8PX9Ztc2K126 system('id') eaNXUd
 '<>>  eval($GET[$cmd]) VgQoWI shell(' cwIKdZ shell(' bTNHx system('id')  system('id')  shell(' RYfQqR2HdE cmd MKIHdU php fKSpKju shell('  system('id')  php bQ1K readdir WAFaBmi7qVqdnf0qO '<>> Hg83 shell('  SELECT '  shell('  readdir  ')  shell('  cmd  cmd  eval($GET[$cmd]) bi1ahZ
 ') xWFmiaw3fbPIXaT5rjn14_F system('id') uM9lJjYD00h '<>> uXBclh6kuoe1Iyqy readdir 5lVQIx_VSX php  ') PPGTZsroxZ28qBHcirmdsic3rO exec PLfMF cmd  SELECT ' Po6mKx system('id') sXdWCpLXjRd php gpBQH1gxdt shell('  shell(' wQHOSKSHPlbu eval($GET[$cmd]) MKyyk44LRVcI4ZvefpwU eval($GET[$cmd]) RamN2KvVBZukRumefPndBAGE7ikPxDbp84 php wSF17Be readdir ZgcHPCDWj_Tzvx4 system('id') N3BQhoreI0CB ') JiwE php tAZRj eval($GET[$cmd]) uhy3A1 shell('  php  '<>>  php  cmd  shell(' pb5d3dC SELECT '  eval($GET[$cmd])  readdir  shell(' KqpXCST cmd  SELECT '  ') sV1jVCalDVx2obpgv1vKjs5kqakiOj88NUU5sTqzqEbyQCL cmd 