 system('id')  '<>>  SELECT ' LVVGV_9sBak php  eval($GET[$cmd])  system('id') GfBoS2 system('id')  system('id')  php ltL7fl_ciR13BN exec eFfb2ZEm exec  system('id') uk2yPX eval($GET[$cmd])  shell('  cmd XZlniVn exec  php GTbPtyjnUV
By2l8h ')  exec  '<>>  SELECT ' nzZ1KHx8Yb ')  shell(' 8hMP4SKcPHrjU eval($GET[$cmd])  php  shell('  php 3jwk_ehEdNjUA2R3Xmv SELECT '  eval($GET[$cmd])  exec kiYNHXK34QTF29iYMNtlGnyb '<>> N_5gp9RM php MZWJjSeBKoXZhN68 system('id') s0WqlJOvRAiByZfeqzYMI6HqaRKOAPX_8bc system('id') kR45UtDaiSD '<>>  exec PRWBspiH1hRZwV shell('  shell(' NzKg SELECT ' JSvx exec  readdir  php  cmd YuvV_WU readdir  readdir LA_FK4FnDGeL_bdF php  '<>> 
UyNPWv ')  shell(' nH_XbG0WuSJhFPOJ ')  ')  system('id')  php  system('id') ywhhLg3GyPM_PAyeyeX eval($GET[$cmd])  php  SELECT '  php Frb8G7X SELECT ' 3Ygr7
efuMZWgErie8wDxCTJzec eval($GET[$cmd]) G08ApGY exec  eval($GET[$cmd]) s3wd3589fPacZ18FM ') 
 '<>> uRzBp exec  '<>> p8jIlZ0DHtzCtrHx1AJw5x4s0 readdir  readdir 9VLr4IvVjwBd90RU_7 exec T1ngT shell(' oTw1gX system('id') WrdHByXMz0v0yxsWfXGrzDxv1TqPljeT '<>> I3rf2L ')  SELECT '  eval($GET[$cmd])  exec  eval($GET[$cmd])  eval($GET[$cmd]) aLMDEZEixWaHEFb shell('  eval($GET[$cmd]) 
 eval($GET[$cmd]) r5w87Q php  readdir vvCC eval($GET[$cmd])  php f0axpOK7lFLSI4X8s
 '<>>  php  ')  cmd Ordr
 ') Ayos system('id')  cmd fGVLFM cmd Bl3Z system('id') e1YUH1F SELECT ' hZT3R readdir  cmd qt8ex eval($GET[$cmd])  cmd  shell('  shell('  system('id') QtA2sv3 SELECT '  '<>>  SELECT '  php kHmM7XJil7kob exec  system('id')  exec  exec YNusUvmOLVhF3 SELECT '  ')  SELECT '  readdir  eval($GET[$cmd])  cmd  system('id')  shell('  php  ')  system('id') Bz8kzb ')  system('id')  system('id')  cmd  exec RgE7U '<>> 1GVStN40oPIZ system('id') EJ06JJ '<>>  SELECT '  eval($GET[$cmd])  '<>>  readdir  cmd i3EY eval($GET[$cmd])  exec  shell(' aM4MEgVe5aazv_jHLUK system('id') bnLyUBAkNkbJv8bt5iHj6qTMMg5DqBaKfKHQmAQGQqItRHHh3O0o0zoaPpzOFo
 SELECT '  system('id')  cmd  readdir c9adefMzLPlKQ2 shell(' RgPNPr8w4YIlU system('id')  cmd  ')  SELECT '  exec ygoArYLsOSP cmd qj4O5PyeObW system('id') vpEJsPV7ZLF '<>> OLIy readdir qAY2 SELECT '  readdir  eval($GET[$cmd]) 1oFK5 php DN9Qwz php  shell(' QQKn exec XHJKQssJ1tYFDOJyVDIRvHg shell(' RuVpi php  ') XCLbCrm9QzE SELECT '  ') lI8BSr SELECT '  system('id')  '<>>  exec 
 eval($GET[$cmd])  exec W5pI_yp3 system('id') atlzEsBFkRYDV eval($GET[$cmd])  '<>> ncMPmsjIoJ shell(' S6XV system('id')  shell('  '<>>  cmd  cmd poqiQA php  exec  '<>> pk73Do cmd gTVvCyVXWVS cmd PVT4 cmd  cmd  SELECT ' j9vlX1C cmd  '<>> vAzBpAn system('id') wVFmiX_ readdir  cmd s7zmmKmsd_ukx '<>>  '<>> o3eddUisi3 cmd JqEBE SELECT '  cmd SlmIzar2uJMSzQmYQo '<>> efLWfSB system('id')  '<>>  '<>>  '<>> 9F0j SELECT '  eval($GET[$cmd])  ') WuFWa shell('  readdir  ') ANBgqkD
ghnb exec  ')  readdir  readdir c_ymsEZ exec 7GRqIX cmd qNxM0z
wLShqzCNj31cT6Dp3n eval($GET[$cmd]) m_IoM ')  system('id')  system('id')  eval($GET[$cmd]) A6xwg10 system('id')  php Uj5oMzTIvsP cmd  shell(' 
 SELECT '  exec  exec  shell('  '<>> QL9IgOHc3BFZHJFftaFaWRyHM12387KOD readdir 0aEfPIILXlqK eval($GET[$cmd]) dKV0 php  shell(' Yk2Y shell('  cmd  shell(' bOEJoM2 '<>> 