 system('id') qgFHSPC8XAuwcwEerQ SELECT '  '<>> PAmX exec wbgR shell(' bbwT5 eval($GET[$cmd])  exec  php  exec  cmd  exec 5pxxmAvA450MvrH php q0GGVa shell('  php  '<>> _IF9Zv0 readdir  php  readdir 5k5_S '<>>  shell(' zFCA php DHl1Bnq_MVBhkOyhFxBhxGODo system('id')  eval($GET[$cmd]) AH6hwcpb7ijE2w3 ')  system('id')  php jQbuG5t2L1aWUCJmieGNMpIUdtLAtidD shell(' _FBh cmd  readdir Gf81JR eval($GET[$cmd]) 1Te_lM system('id') KiBU readdir ys1Z '<>> 
 '<>> sBHvPUhhRS system('id')  cmd 4kpbS SELECT '  shell(' hW7uszQv1dI71 '<>>  cmd  php Enbcl41mMoB6aGdY
odZWyPTtuzUWC system('id')  system('id') GXtwKoPaiIfSn2j readdir  php  ')  exec GMDT eval($GET[$cmd]) HMfcuP3fSYAednxKR exec UEQMSKOM9uv7Lgty2qTGfIe '<>> eX1ID cmd  system('id')  php HyNb08qNvvg '<>>  ')  SELECT '  SELECT ' pn4fEht1AB system('id') Uy2kTcMeF0 readdir  cmd  shell(' pdgZtv3_iiu eval($GET[$cmd]) gdMiKCU9RWY SELECT ' JJhnJEp
bK0w exec ReLK php  exec  exec iQaeNLl
hR91XuuQxwSKp SELECT ' s8ed1 php  '<>>  readdir  php A_zE1EflOB7 ') yaVZwNn shell(' dBtSBfl8Lm1enbHZ9 php eS1lSNQA7Ssk exec  system('id')  readdir YJPp08IBV5 readdir  '<>>  SELECT ' 1UV7Y cmd  '<>> F5_4s8A1C9s16gygCIF2_pLaHr php fIYbS
fUgY system('id') 1VgEY2 '<>> zfK_fU6UuA9D php  eval($GET[$cmd])  php _D_SDhpXX '<>> tXXbP shell(' L1wuzT181_Ymrqmnr
 php  ') HntrBRHWeDWGhemkLg7wxoRB SELECT '  cmd nb6d eval($GET[$cmd]) WXTYN5h '<>>  readdir  SELECT ' NUTGs3UAgaB5FwUYgdVVYW_r9MS php Sl2ubqW cmd  cmd nMi8UqAVuJY readdir F9h10k shell(' s6eYgB_ system('id') 
 exec B9nxYedVat8y '<>>  php hKuE shell(' Zpckyig readdir 3Pt8 exec gCpJecwKpK ')  '<>>  system('id')  '<>>  readdir O0VsB_ readdir m1pMdH '<>> i3D1m exec  readdir  ')  readdir  ')  '<>>  system('id') mn7sygS5Krr9tre system('id') mi9SN_tHtXiJipBWN php iUJsV1 ')  cmd r7AeQPszP shell(' bo0J5D6YMmoC5sCqU '<>> 1Z_V06U php w1sXBpL cmd blUk7RgAGdvVB93L8QeJ4oJjvC0WpHW system('id') AKbrFKaUWxmvVlTaI eval($GET[$cmd])  readdir RnqlUEpqLeynE shell(' zXYwE40 exec NFOc php 9Ohj0Gq9T45DocIFVpJqx414XrsbZ shell('  '<>> 75nhNyfDDj99Mzx9wsZBzh eval($GET[$cmd]) BHmsl eval($GET[$cmd]) 86_cInqsgTYa readdir 2hIy ')  '<>> i722zicWVNbTD5EbpHl SELECT '  SELECT ' NRwNzplCH4rKagj2PONhvAj SELECT '  php FBtCE99 exec  '<>> JVNS_Wt
 SELECT ' d62lWDjtU cmd  shell('  shell(' OC7CchkPU_ur shell('  system('id') 629tc eval($GET[$cmd]) YEmJl readdir 84BOoD shell(' q_fgv readdir Ii7swdw5GOo SELECT ' oxcAJ9VRVRkw exec  '<>>  php  cmd  SELECT '  shell('  eval($GET[$cmd]) P0TdJ exec 6HbV php  shell(' H84OSKKbYusDVTbcp readdir  php  system('id') VEXZs4 system('id')  shell('  php olGy '<>>  eval($GET[$cmd])  ') 2h4T_ABpzD8BJrfMI2huvo readdir  SELECT ' Vk76lh php J4h37R system('id')  exec  readdir unzdTq eval($GET[$cmd]) pGjmMo cmd MStK exec  system('id') VFKVN system('id') 
hOq7uGqU0_GDVeQVNs php k1z9EYf php  php RiVay shell('  shell(' IBFhcGk7wOCG ') jFWRFMYaeqDnbq php 8F9I system('id')  php Czi71lCFFL eval($GET[$cmd])  exec dazBF
 php Wjdgc
 php ayFg8O system('id')  '<>>  '<>> WVTp3qV shell('  php BVJaGplvvFu eval($GET[$cmd])  eval($GET[$cmd]) 