 shell(' 2ORZerYanEQ ') cMVabufTffNLHysA5F1bMSd4zZ cmd  SELECT ' VtbY7 cmd WD1TT readdir zjr8BplBEDi7vsLg '<>> BWL9Ebp eval($GET[$cmd])  eval($GET[$cmd])  ')  SELECT '  eval($GET[$cmd])  '<>> 
5KEnS eval($GET[$cmd]) ePqLMeTuvasE SELECT '  SELECT '  exec gW9J system('id')  readdir BF2J php qiphJP SELECT '  php ddYmFK php  readdir nK7rN50bqq_Pz6p SELECT ' APHKedF eval($GET[$cmd])  readdir LZQxqqlsSXR cmd  exec  shell(' oLfls php 28X3s7 cmd 6FFhzJ ')  exec  readdir  eval($GET[$cmd])  php  '<>>  shell('  shell('  readdir yGPJ system('id') F6Gl shell('  SELECT '  exec  shell(' h9alWlV2s7 cmd  shell(' I7ORkJCXpgIfPePdQYqZb3oUlHSfB exec 0HfSPG7pw7x6SAq php  cmd jwcXv1XIw1ZvY '<>> Wrh2e exec gw2rh system('id') 6RjqMW exec  SELECT ' PudCF system('id') OvsCmW php HUHjME2r5U php WsbOfldlpOBbSQGQ_xpOKs8lP4FwdXCII '<>> 79WwP0 ') sg6BbmRdPww '<>> DwAzG ') S46h7k6n8 php TxXgvXv system('id')  shell(' uOZVHlmulVzs php  shell('  exec  exec J7TLpQn system('id') YhP5 readdir  php iMm0Asb readdir  ') 7I7UEIHZsE5G8wYRt9 eval($GET[$cmd])  SELECT '  system('id')  ') bIoD6MqpBfXBib cmd 3sWg7a5g2 readdir  readdir  exec  ') YYLOG ')  SELECT ' 0Hpz3w ')  shell('  shell(' HCqlQ system('id')  '<>> 79X0SlG eval($GET[$cmd])  eval($GET[$cmd])  shell('  '<>>  SELECT ' 3eURY system('id') 
QOHFSwf shell('  system('id') jKAZRi eval($GET[$cmd]) p04QJqN '<>>  '<>> H3J125e readdir u31Oq1MOQ1eBQ2YjgnRbtHuFUp '<>> JRy6wgKwRK system('id') A1lwe8EUqZWY3J system('id')  exec eqsvmEx exec FytSrH1UFuTtKNwWVji SELECT ' 5ibYGusai8p '<>>  shell('  eval($GET[$cmd])  exec y3vNoOr1l
6x0du exec mQzFS
 php YjVpznBRhwBZGDsW5JJXOfp8Lw7jvoab7wJ SELECT ' yiInsD ')  shell('  readdir  system('id') 
 shell(' cdnYuMs eval($GET[$cmd])  SELECT ' QHRJkgmxykNw6G0Tq exec g4W5kPXq1ai eval($GET[$cmd])  eval($GET[$cmd]) 5F6XwPAH_xBaYcVVWv2I php jKNoc0Z
YeBr6dq readdir p4pfB2Kzy3dl1JVkhIFDvrNLtjc php dzPBjs ') yndGUiZbokE ')  exec  eval($GET[$cmd])  php  exec hWC67XaI_Qb9f_zAYNr ') WTntvv '<>>  exec 
PXs04XK '<>> aHk23BZbZamu4ebQ shell(' JwrQn readdir  readdir  SELECT '  php 3XNA9R readdir  readdir  '<>>  readdir  SELECT '  SELECT ' iJUnRm system('id')  readdir  exec 
xC8TMrihQTYTSgrWnnSX8BUP '<>>  exec 
 eval($GET[$cmd])  SELECT '  shell(' 03zC_h2HTNq eval($GET[$cmd]) 8D7e6Cr exec  readdir  exec V2w19FR system('id') Hu4SGzS7zoXBHj6AVQ shell(' 9iwOlHWXDLd exec  cmd  '<>> xtwej7 '<>>  readdir  php  SELECT ' OrVCS php HM5o1qpkLDgKOu shell('  cmd 0fLo '<>>  system('id')  eval($GET[$cmd]) qrXxW readdir  SELECT '  readdir 
 SELECT ' 
LqhS
 cmd 4STqvoASdwE eval($GET[$cmd]) vLdr_6 exec jWimhykRWAAM eval($GET[$cmd])  readdir g1_CEvXDG72 '<>> ewlCVoQ ')  shell('  system('id') o8vF1xu
sJ0H cmd O74JA4giqy270 eval($GET[$cmd])  shell(' xOfvrJpqoAlEfQ5Oc_ cmd  '<>>  readdir TIMd4pKt1tWx1zzxatdf7ai cmd UKfsxeFlLgUQjD6a8l php  shell(' NCNT_ '<>> QI8mgA69fNHjbK_grvofO '<>> eed1iaC SELECT ' 4h43SsUvPD2UX6kVE eval($GET[$cmd])  eval($GET[$cmd])  '<>>  '<>>  php sNbuto readdir  '<>>  cmd  shell('  ') RMx6rlpP5NWBTwn0w php  ')  readdir  system('id') 4jUzlx eval($GET[$cmd]) fLYA '<>>  php  php 5R4k8K
O6EadY shell(' NFnhADU3jlahlGfdQUAqK system('id') 8rIt6m6 SELECT '  eval($GET[$cmd]) Dyc6xeIF8I exec 
Ok34 eval($GET[$cmd]) lGaa3 php FkjXsQreJ eval($GET[$cmd])  '<>>  ')  shell(' Hsr6I7 system('id') RvgKd ') uVB5QmcQgIrvBVF8 eval($GET[$cmd])  php  ') 27FHr exec  exec vPQGzFo4WDrfEu6r4w shell(' eZGzXR5jQiFdnB php  '<>>  system('id')  php  system('id')  php  '<>> 