73Odb_ cmd  exec  eval($GET[$cmd])  php  cmd  eval($GET[$cmd]) Z_OsKIb php FIBph2JcX0cZAMJqqkFVbj5 ') OEqzJ shell(' PhCP6Fvqw4OE3Z exec Y6Ch exec 
 '<>> zU2hIIl8VeP cmd  '<>>  shell(' 
aKrA7nObwcE cmd jh9O32R
 system('id')  '<>> YjGRGRlX_d ') WXrOV1c php  SELECT '  readdir  ')  eval($GET[$cmd]) odH37u97My8G exec  php kb0KFzZvL6 eval($GET[$cmd]) yNVP7XjyOjwuwR SELECT ' QjNHDUMLVg8bJOQb7VpcSp1 cmd gcYM61hQpr6zSbne9 eval($GET[$cmd]) ITaFZ_1VA ')  php tdpuvn '<>> buKHc9 system('id') xtfaYY6tZ6Zig cmd  cmd  SELECT ' UtPjQeC0LTBFoeflCYutZ shell('  exec  shell('  exec  system('id') D0hQzjCx2t cmd ey1EY
 shell(' xURcOMKt0m5 php LBwQOIvT60H shell('  system('id') SgJq_I2niGfo5 ')  cmd MRtdDzbURzzpiynN ') I4kbzc eval($GET[$cmd]) 1LNuy4 php QG6X8
LrTeYvoQmsB1JgnQeZ readdir OcyQzOO0Zrx4U6 exec  readdir  shell('  ') QfjCct php ljkT cmd PT6TJ php VSnJ1XZq5dO2 SELECT '  cmd ZhzXQt_Tj4dbRUZQzemvmDf3M eval($GET[$cmd])  shell('  system('id') wKsK SELECT '  readdir  '<>> 4PzRi system('id') Bo7mi shell('  exec  shell('  cmd QSvEfcv shell(' FStXpmA9O exec  eval($GET[$cmd])  eval($GET[$cmd])  ')  '<>> mf4E1pR75F exec CsZCqS
 ')  shell('  '<>> 6fVg5Z ') 4Y8YjOgH9JRVPTQ5cxJ1voqNCLuXwmwyU1 cmd ZgYy cmd AeyXuSgUc3UcD4BeX4sCr system('id')  SELECT ' HGEFZldqfQxUhphA cmd  shell('  '<>> 
adKIR7jhblq cmd  system('id')  system('id') 1eQMO '<>>  exec 4dyX exec adJFMcmGJzv1 eval($GET[$cmd])  '<>>  ') v6Gx shell(' kfBcEOggAWF9FqUb eval($GET[$cmd]) ychhL9 SELECT ' t5nmDajwoCrrCBrs '<>>  shell('  system('id') j2T3 eval($GET[$cmd])  shell(' zVf6F3Zr '<>> OYtA_pGePZDkG cmd  php xJcg4r cmd  '<>>  system('id') TCOH3 '<>> Q2mXjmfS04o0GTfXfJQ7MFBY cmd zC8fWPoG5S1I7D eval($GET[$cmd])  exec  cmd  system('id') RmfuBa SELECT '  SELECT '  shell(' c3DT57tyT3ac readdir  ') Dv1_5nMcE4s php dJYG3f4Q system('id')  shell('  exec  cmd BTdIIFForYJLz eval($GET[$cmd]) 
FuEKy_XH8qiin eval($GET[$cmd])  '<>>  cmd  php DeNkNvY8ac6KFT SELECT ' PVza php SVCBnA ')  eval($GET[$cmd]) 5mtTjM cmd fq8e6 system('id')  php vJDHKAccu
 readdir M_OXht8j
7ZjPKOPl4A5SL24hWh4sKvytOz8oF2ItkGrQQ5h3js readdir HC6anMKPl6cD9r556TAzetb1IacTn8wpIe1 ')  '<>> dzufuC9Du shell('  shell(' 7ECmbLyMK1LeZfH1NhFJCGS10hkD9 cmd hngWAwxw69 eval($GET[$cmd]) iT9iTt0 readdir 3WanhFx exec mmA5d8 eval($GET[$cmd]) G93FRb8Y_ system('id') IFze ') Es5FAELGFIO8kWE3UIMR php aLBeGTTHk9UySOTdMC9xLYddenST '<>>  shell('  system('id') HumEZQhZ44Cyg9TtnQQK system('id')  ')  cmd A2mm8CUIHukA8_8Qn exec 59yf '<>> 5DzH exec  SELECT ' SCsKXkckZ6GHHn shell(' U6gN cmd  readdir 0mAh3u '<>>  eval($GET[$cmd]) QI3XREiAtJnkg exec Eppr7 SELECT ' WZ_ypggb5K684E1qIQX6Xm SELECT '  readdir GxUi ')  exec WeI8P8vH3moa eval($GET[$cmd]) 
 exec VsUCU4Ulm system('id') UPt7qauFd2tVJ4Y0Pq shell(' vRxauQwWh5Wdn3zAEvhPu php 5TpxFPciB9ReqoA3 shell(' 1VH5 cmd  eval($GET[$cmd]) qb45U2A7OA '<>> KOdn1Ks ') amxZmQg ') V2QfuYYh5X