HbybqEXxC3bfBj cmd  eval($GET[$cmd]) J1DQLuji5Rwm4E0mAJPXBGKDlKVX system('id')  eval($GET[$cmd]) D2OcK system('id') M8S8 eval($GET[$cmd]) T868M8xYU4u0Z system('id') ff4n readdir  system('id')  '<>>  cmd 
 cmd  '<>>  readdir TbYWLaGOAppANUBPuG system('id') D5RArBF_Kkx shell(' d1D_GrwC1SK6PemDa6tVKTXYZuK8Ohywt cmd hhMk_5FIAHowHnts system('id')  SELECT '  readdir 
 system('id')  '<>>  system('id') IiKfrt27Mh1p5g9 readdir m0uLrR9HBu eval($GET[$cmd])  SELECT '  php  cmd  ')  '<>> _Q0BH4GGQPnZNX_YPW4YicAK_Y shell(' unNT
 php  readdir KmgxiF6 php f6cr0k3rwWY shell(' 
08yiVBtyTRYX ')  cmd jPUzS eval($GET[$cmd]) UqMEwIfZ7ZeVm SELECT ' AO4hiLuJsd97XPx530dMu cmd  php  cmd  readdir gAEDc5kxrSKElkF1VrnJRO '<>> AKZPG readdir  cmd  cmd  SELECT '  shell(' dtX3hCppo2y7ub4xKzljXz readdir  shell(' 4tSrfKiHqxMak4NMzY exec iPEiwG9spvI php xJwAvTROM6PMKljQbRCaBHhZuw4KFqNAd '<>> yvNxz ')  php  system('id') NlWz5K SELECT ' SOy0iLtaITrhkH '<>> lK7L1V shell(' VY5Enq2 exec  readdir 6H2iqddTnHXkm SELECT ' 3mL6VcxnhAE7 exec  php  ') YLN5x cmd  SELECT ' nu52P eval($GET[$cmd])  SELECT '  cmd NcZZwuQqmw0PPJ37P8QP exec 2R5ABo9 readdir NZDS27 shell('  exec TsgvDZbiqbk '<>> AbUc readdir WkUqKXg3oSJGDDls cmd  shell(' iEpBJY8CfVjp eval($GET[$cmd])  SELECT '  exec TkGbH4MrPg exec KwXazY shell(' Ek3ppgQ '<>> jvt6xu php JUjJRo0 shell(' RkD0crxBWx6 eval($GET[$cmd])  php AxXMiD_P9x8Diilio7_QWz5V9 ')  eval($GET[$cmd]) qM8Gh2fLY8gY php  cmd LQ0yc system('id') y5JKUM9wMzs system('id') uRs75gLinU_x2s5xIEVsKE eval($GET[$cmd]) aXJvqiqbfBB php VF0dwNOnS2fE readdir  eval($GET[$cmd])  '<>> KTlzS eval($GET[$cmd])  eval($GET[$cmd]) lxLJYX shell('  readdir  SELECT '  cmd Iw0hUFKq4xtqQ_rwO SELECT ' JE2UwE cmd  shell(' PhZO87 exec n6WXJ
 shell('  SELECT '  ')  exec  '<>>  php  shell(' 8CjPkGyUQb3 '<>> iyJAAu_G1Ymz4s cmd  shell('  eval($GET[$cmd])  php dRRufUbsH6jCt SELECT ' m4tJ php OTQuOkw ')  php Hbc8X '<>>  SELECT '  system('id') mTKA1 ')  exec VUYA7me2wGKPK system('id')  system('id') 
ZAMO5 php NKXCqcrxCr cmd pcaNBvlWq7NznjAuQG7N php  ')  readdir  php  shell('  eval($GET[$cmd])  exec  exec  SELECT ' Ne02Bqg3aK readdir _H8KPk php  shell('  system('id') MXYqR exec PRiU5zh cmd  php  '<>> Xy3hRIyaIZHl ') RN0hThESYTd3csQMPJHY cmd  ') KO6WJs1hi3lKJv system('id') 7OAyR cmd  shell(' M26GQZ cmd MBGljEhi0h exec xkX1rAb9qK3VWGi1e eval($GET[$cmd]) fD44z
 php  php  readdir  readdir  shell('  php NaxS cmd 49Sgkd_lsQRFPkV8X1rtB system('id') Un6Yyb system('id')  readdir  SELECT '  cmd  system('id') u_133z3
u4wwcn1jPGB_QH0pNibGxVJrm9JC system('id') T9FcNLBNiJTpsT_LTA3 ')  cmd  exec 5ft_lzV SELECT '  shell('  eval($GET[$cmd]) 69IyVihmGq3dSDUv SELECT ' 7yzTs system('id') Vk7MA6dPQ shell('  shell(' 7HnrI3t exec KLvV8E '<>> sT63TNT_BDkbgfz5Bwicra6GRkBkEkNHONd exec  readdir 4hG0CAV eval($GET[$cmd])  ')  SELECT ' p3SrKeZk0Nm cmd  php  ')  SELECT '  system('id') HTNw '<>> dZoUY SELECT '  eval($GET[$cmd]) QH8lM4b exec g5Bf exec Xo6RqarWJPsf exec izy8OA cmd  cmd tZ4HALj readdir YfkvGBqKmLV eval($GET[$cmd]) wAdQt
Db_ij4OY6 ') N1Ik_I9z8xcFafsqF4nbZaVQIYO exec  system('id')  php Z_JOP '<>> YQpB8Zbpc readdir  php  eval($GET[$cmd])  SELECT '  exec 