 system('id') x6URkn '<>>  readdir 0XLMk2wkum eval($GET[$cmd]) f6gqa4kc3ijzqV system('id')  cmd  exec  ')  readdir EF6kkn5gf_uE '<>> zrsgfSb9rL200jxoquH2_Zz_g6 shell(' g1w8oMywY6eEjGd3bc readdir  shell(' 3fMbZ11bXoenDn
KWj8WqZ '<>> yab_
 php  php q2yf9YYgY7ocKXE5skQ5Vzz '<>>  system('id')  SELECT ' LY_r0YFsHjuL5MR0Cna SELECT ' Ugee7y php o0WMynpsbO_tdrHUBN cmd  shell('  cmd  shell('  ')  eval($GET[$cmd])  exec  php vbU71UvAhdAxsphE0CUda shell(' 2INw93MbHr php rtEM7gYqufhTmaEHwT1ngLy shell(' HBA1xsR3dr shell('  php  cmd v_eH eval($GET[$cmd])  readdir qJwIZJ ')  SELECT ' ZAg0Oxu exec sNJUd37cRf0 php uFse_ '<>> LT7h7mx '<>> tP5dptIQwx2X eval($GET[$cmd])  SELECT ' OyVsXq6Ea5iWOkSz system('id')  cmd  exec  system('id') G8xP7 ')  SELECT '  eval($GET[$cmd]) jYHDuvN cmd  system('id') t03sm4w system('id')  shell('  ') rLVpZt1inx1ZS3
 readdir XKIB8gSFCYw7 cmd 4Q68kQ8TNfzoCvMEcPH eval($GET[$cmd])  shell(' TXsO '<>>  readdir  shell('  readdir kJGZUXb0r exec BCgemi7aNBX5x4R shell('  php  SELECT '  shell(' fropPe16b2Y eval($GET[$cmd])  ') 5sUEg cmd  '<>> pMgzoWQ '<>> zdG_sA0a57XT ') k9Jhen5SuZ1vTH eval($GET[$cmd])  system('id')  system('id') gJqpo4kQU3k SELECT '  shell(' RdBNo exec  system('id') vE335o
AGGHd eval($GET[$cmd])  '<>> p6Wtr readdir ZMvURNPIBlGk6avsZy97Rp_ZE eval($GET[$cmd]) wImo0O exec  SELECT ' LIl3 php 0Kb1b2u ') _0KN php  eval($GET[$cmd])  shell('  system('id') sXZcGbhOX0 shell('  eval($GET[$cmd]) qOhND2hTmyYkTb readdir  shell('  eval($GET[$cmd])  ')  shell(' XL3WpZ1gzAHFgAqv5w php  system('id') 0LkzKFS
YZ5hwigr2 eval($GET[$cmd])  system('id') x5C6 SELECT ' jfR91VimuXicS5zNyrI4Hmvw4 shell(' TtVMD eval($GET[$cmd])  cmd C8CIns system('id') R_ieBS eval($GET[$cmd])  exec  system('id')  readdir  exec  exec  php f1yAiUOz915_KbVu php SeL_p0 '<>> hoKPdB1kJiyF0M_QmZzjPh exec  cmd 6T2NZ system('id') twHU44z_bAu shell('  system('id') PCdD2mt3gG SELECT '  php wzAbGkJ1kLM system('id')  system('id') KTsYoWsl23I eval($GET[$cmd])  '<>> t_CKT62 exec nM_uVp eval($GET[$cmd]) raZ43bx74ud
 shell('  SELECT '  ') Ke0zO0bryPliNURiUKMoN ')  SELECT ' DP7rL0L cmd L0AYAXp exec  exec Tba_
 system('id') xuaF ') bPvMY8_L6DIGvHrOhQ SELECT '  php jt6V exec  ')  '<>> 8J2CxRJxDQ3xTpktUR0Khflq9 cmd 7wvYv system('id') 1VFX php  SELECT ' Equyi9BeDmKNmYiyvLbelI exec  '<>> B4KA php TkAm cmd OMZxo_ system('id') hhREKdj2 readdir Au6vYR9 exec NIFjBm system('id')  readdir Frkk cmd vuC432l
48VBt readdir  system('id')  system('id')  shell(' Zpmzd eval($GET[$cmd]) hKI6 exec  ')  php  exec  SELECT '  ')  eval($GET[$cmd]) XJDUDo2BEHRdEyCu082UnZ php 5DPNTNmv ')  exec MNgjl php Jh493FicYdw
 ') 
 SELECT ' C75q ')  SELECT '  shell('  shell(' 
FcL4HL1 eval($GET[$cmd])  SELECT '  shell(' 5qZPY system('id') clAjR ') XfbFqP SELECT ' 4tPt shell(' VU8Z_x exec onnzfT shell(' rzAZez1w5l php _RLEbAGyMJVMVZ system('id') Com9 php  shell(' KDHLI ')  '<>>  php s1Ff4740R4N78gQ cmd RqnEZIKJR8lFVb2w eval($GET[$cmd])  '<>>  system('id') kGbBIL5 '<>>  php  cmd FF0l readdir 