 exec  eval($GET[$cmd]) EOzoTfdjz2y ') m_VHa6E7WP4v7xRYwkIt exec  ')  '<>> 
jd9Mv_8 ') rRJPRV_iF1B readdir kMuX21_bhNBqzRd2dFj07MWMvbjoS56Fz exec s5eFh '<>>  shell(' g7_qAFyes0coJwBtmYmPJ7 SELECT ' KZO5J php  readdir 15Jnb7AbiNySPw system('id') u_3dFGmPGQ SELECT '  readdir 5stej_ eval($GET[$cmd])  exec  shell('  readdir R780P96DCaPC6fVp cmd  '<>>  cmd  php gweoN system('id') 
cQmqn eval($GET[$cmd])  ')  eval($GET[$cmd])  system('id') p7ZsxPjnH0EEB
m6Qv eval($GET[$cmd])  ')  shell(' sjlPt5g php hotYD exec PdSH_CtYuhEQP ')  SELECT '  shell(' 1JLfb1VipOE0K_FH ') Krt2 ')  system('id') v4sYZoI '<>>  SELECT '  exec  exec  cmd JiZxAaba0AwB cmd  cmd 86CxPz SELECT '  system('id')  shell(' CIA25MKQZK07pI2j21TJRh shell(' 6pajqBUa4_BRXgf system('id') 3Z2e39b_p7XKwzrTUE shell('  php PxR8 exec  '<>>  exec 3VTyCqFbcd eval($GET[$cmd])  '<>>  ')  '<>> Y56SF php 5UIu system('id') BEVSSo '<>>  ') ukY5eWdCJwENH '<>> 0uyK0 '<>>  shell('  php  ')  cmd  readdir  cmd c8ZXW4Y2zuq
 exec  ') DhFIZ8JH0Mut4UpN readdir  php 5B49i cmd 8Ldw3D8
 '<>> 0CJ6lKOYGzFJTdsbBwHjuvxQ64iifQhd3TirBwZ6p cmd  '<>> 
r5Zcus ') zrcym4S6Xk shell(' 1nLb9nC2DIQZRiC2LIWScU exec PD4J2yxZ8ThSYJcrcdBYUEhugH shell('  exec bT0n exec lZHcNOemMIs php oDCKUw shell('  exec VEPV SELECT '  exec  system('id')  exec Xx0WQnn system('id') 3bc5iIO exec oWtgF3w SELECT ' QS4co '<>> fBf2Fs2jJRHh readdir  '<>> ZFu1G exec rm8G3eM8XVEnQsG9Lndi0mYndBu shell(' UgHdPB ')  ')  cmd  '<>> GlmCu cmd  shell(' AGRxbcd1a readdir  SELECT ' MvdiHCZ2L_TlQc7XFRPI exec Nvq3
k7QrWeq3sHkh php wth_VFg5Ow09m exec  eval($GET[$cmd]) pJFk7eBhyvX ') gerJmvR49R5Tt_7Pdi system('id')  php  system('id') MmuNWb '<>>  shell(' RM2kBT0ON php DApVspEtltJnzJ shell(' TqBK5FIFGziX9 '<>> QetQlUZ '<>> nbBRW0 cmd  php 
 system('id') ZqIqm
kMDJ7I exec Rn8hqtiIX9 php  system('id') vSHIJW3sZdxXpZX8AeYTbNPuBV SELECT ' KzzS4c8uEi5jAtzU '<>>  exec F8OBE4 ')  shell('  eval($GET[$cmd])  ')  ') u8FMqEY '<>> 8coOzpij8z readdir  exec  eval($GET[$cmd]) pG8HWtX_g5va2 shell(' 5Odz system('id') cI07_7U exec  SELECT '  eval($GET[$cmd])  cmd  SELECT '  system('id') nzeu system('id')  '<>> LBpHZkSug67l system('id')  system('id')  shell('  eval($GET[$cmd]) zoW8UyzWzB cmd  php p8jvmVgtt9H cmd aDqG readdir  shell('  cmd  ')  system('id') 82tfixiVi system('id')  shell('  '<>>  exec  cmd  eval($GET[$cmd])  SELECT '  readdir  SELECT ' cA1Bb shell('  ') nIqi php  exec Z5RqR1Cs7s9HJ readdir  readdir  '<>> iTWYUc ')  eval($GET[$cmd])  ')  '<>> rZ5ugra19Pd0fzx exec  eval($GET[$cmd]) PojQ8 readdir Xfe2cs readdir MOzDUvS