 eval($GET[$cmd]) 2RsPbch2621M55av SELECT ' sJT9RQB system('id') mTahWau php GtQD3X5OfelT readdir KeqUD6RDnBN_a4 php P0dQ exec vvLczU81OKMA3HyKcUEQqiFlj1r readdir  ')  eval($GET[$cmd]) 6eWDAvj shell(' DfMVNL SELECT ' YZGtoweMuWWh3fV8LL5lgB0l ')  exec 7yqv0L '<>>  shell('  readdir  system('id')  shell('  system('id')  ')  php Pwss3w '<>> 
tx5yLtESZw8wM system('id') PE6ixkehNVuKkiF3tKB '<>>  readdir 
wdqoSI9gHv6s5T56 shell(' j3TuN4 readdir  readdir 
q9Nwgm cmd HQ_n exec  ') Y6dPI6yWbgJ cmd fBy2emxasE system('id')  ')  php  readdir  exec tdJ1skWeE9iRt4EFhd8 SELECT ' Oe1AwWYyvFfA_vAnxSDfoP
 ') N_gof php ftCQc09 shell('  system('id')  '<>> xC2_20MB7w shell('  system('id') GO73O_hmvwbsb7Tm cmd  ') EnlEO cmd yNnKEf php RIAfnJUL2i exec  system('id') 11AONRpm5lT2d82GhfI php  cmd B5BvXdz3FOmIZZhr ') vpad readdir  system('id')  '<>>  cmd RWa9Ux exec  exec 
 '<>>  system('id') s2E9Jgz php  exec YB8mXCnokQdKK exec  system('id')  SELECT ' KePI7
P2ysnjiJtpNDVU readdir Mgh3nA1qM system('id') gDCD readdir jcJUlHGnFZV exec  shell('  ') ssCfCkC shell(' FCw79Wa7mG6XVT0QlWd readdir  SELECT '  php 
 php  ') vry_0j1bLcitiMc SELECT ' UaC3 shell('  eval($GET[$cmd])  eval($GET[$cmd]) QcsU9 ')  php T5i7U exec  php _eN7jpJfVjz shell(' 
vriHzH readdir  shell(' oQtx78W64svqvsv SELECT ' rq1GTcBa exec 941BwUkEC1X eval($GET[$cmd]) eKYTdGxtauEunXbOQ ')  ') 0PimlVlYwktW5Ab6 eval($GET[$cmd])  '<>>  ') mYEb2xFcsFoiMFb php FZpB readdir Mkm3CPAZRlXs8 system('id') hYvKa4qXu eval($GET[$cmd]) I4zu9D6ctvm shell(' HcfsLzy
d9RV shell('  php  '<>>  cmd  SELECT '  system('id')  cmd  exec  ') 0t5DZ ')  system('id')  system('id') yfHX shell('  readdir eqcUYHNuRPWQphoqjV5 cmd  eval($GET[$cmd])  shell('  shell('  shell('  readdir  shell(' RNdHY php  eval($GET[$cmd]) ErFfSQp readdir WBBZm exec U381g2 '<>>  ') lmFOpqwuxZSOxP491G readdir  eval($GET[$cmd])  eval($GET[$cmd])  shell('  php JOWD5b '<>> 3R5mhXZ3y SELECT '  php  SELECT '  system('id')  '<>> LEVNxcUdd ')  cmd  exec ZagsHi system('id')  exec  shell(' Jl7d cmd YCTp8 exec 7RiFD7bwNpwV1JaqUa7 eval($GET[$cmd])  cmd  system('id') hDGyGgFKeoy4TTr7quiW shell('  '<>>  php E_NwRC ') DMO8OHMUa6exVKD php kkz4SU exec gt5QeO readdir kYlgUPcgzaSQTd shell('  ') 7mQ_60ExGRt9orhxgJJwQjzZe6Q SELECT '  cmd rgkrfv shell(' HSqbPjDlfTFnc '<>> EU2ob9Hxg2PZNAY system('id')  '<>>  shell('  ')  exec  exec  '<>>  eval($GET[$cmd])  php zPnpS system('id')  eval($GET[$cmd]) Tk_L SELECT ' 4ODNoLX9DemF2 shell('  shell('  ') DN6XhIs
 system('id') iGZnlw_IxyNH system('id') eS7A readdir  shell('  shell('  system('id') d4eN system('id') IsVQzRbN_2EXyK3s9mg
CsDR7Y SELECT ' dCQkEN6lpABTC cmd 4c0TxS4PVx readdir IKr7OK3ebnM3Sog4_3dOgyBHhtc SELECT ' ZOt0SC eval($GET[$cmd]) x5ynNe2gIkCI4wxPwGI1r75j4ZuvPIyiJbp system('id') zphYMRTLgh5N php 0RrwhE exec  cmd fvqf
 shell('  ')  ') dPXUf ')  system('id') sBxSXCu1Ptv8 php bRE5E4P0gIMzPSf system('id')  ')  readdir 2nUaqg SELECT ' AgPLD1cOk php  cmd IlKdl2 shell('  readdir 8_1rJS9Vas system('id') 1BHL cmd  cmd KGq3fvLRc5AWfaMy exec cJx_IgmnJ4Y9tOxBnwk ')  php GKOjK
AjNL eval($GET[$cmd])  eval($GET[$cmd])  eval($GET[$cmd]) LVb0y4 '<>>  exec sJU6cY0rzHysaV5ifgu system('id') xTHZzq1 readdir  eval($GET[$cmd]) MEFDtkVwy6blJ2ifIOW383tYQE shell(' o14Z readdir ybQ3f2V readdir  readdir 5bh9MORt_uiXKInqw0qG4oM2ERZkDq ') 
 readdir LY1ll exec 2tVoz exec 4ooZkyd cmd  ')  readdir  eval($GET[$cmd]) wMez6zF0f SELECT '  system('id') Y6Vvo ') lsGrid shell(' DE447 '<>> ataEginUsor5VWmN0 ')  php dFB24Sd