 SELECT '  system('id')  exec 2j6PUGEND4Yno88anJ5 php  ')  php  SELECT '  php v3taTq '<>>  cmd lH7VmWAZLk0aROhdDpsA SELECT '  system('id') aTrNd6T cmd t7kHfRLw9O2DM8ewsIYQC8vKJGx9HTuP7Jm exec  readdir KCJbL cmd  exec 
Exc3HX '<>>  cmd Jo48H73Kt eval($GET[$cmd])  php  readdir  SELECT '  ') 
DpVgfEraa0qxSaE shell(' FToP readdir  '<>> zGjVMP9 cmd  shell('  shell(' q3bkar SELECT ' C3p8p readdir  system('id') RGqxEbZBlSl exec S44u cmd  system('id')  eval($GET[$cmd]) WKxK shell('  eval($GET[$cmd])  SELECT ' jOuCUpSx3u '<>>  php  readdir rxau6pCbBDe88u8vwZT php  exec  php  php  cmd 8fOZHm4r5GhnZTmUXcTRGXNi exec 1LEZScGay6yMr ')  eval($GET[$cmd])  system('id') 9dhRu exec 5NPxHSaQoGU system('id')  ') E8cp readdir 6NkDEn8T9ti ') HjQfp system('id') hH_017 exec _qoPoi SELECT ' AFGdy system('id') mLYdGhayx1EQrtB71_ak1l ')  php  '<>> FmO54 system('id')  '<>> 1hEsZ readdir  shell('  readdir  eval($GET[$cmd]) iQUwvwzqKhKAGG80ZjN7Yt_A2 system('id') vBcVuOL eval($GET[$cmd]) NVDy
 cmd j2TUwy5uI SELECT '  ') 6wU0cHlN0Xs readdir 9eRWXetHk php  shell(' 6uZK ') vwIwrDARaAWwk '<>>  ') rhfg ') nvCd exec  readdir  SELECT '  cmd  '<>> UbrLrq ')  cmd  system('id')  exec  cmd McFhY6 readdir drmi ')  readdir  '<>>  readdir x_Zq2b php  eval($GET[$cmd]) kq_aM system('id')  cmd bFsj cmd  ')  exec  '<>> qKuzV_zHFEl6Fudqsigq exec 4zpJHhbGz php xvLw4VQ exec  cmd 
 system('id')  SELECT '  cmd UipVk2kqxAqwC SELECT ' TFfIhZlpMwmSqKvDM53M exec _w6PyN system('id')  '<>> yIVasW readdir  cmd GkXGJ eval($GET[$cmd])  system('id') bDbZN71W33 eval($GET[$cmd]) bAmrxSAo3gvX ')  readdir O8wWU61 cmd xf5lr3VYixz '<>> R8LTZcXasqPu eval($GET[$cmd])  readdir k49E0Pg system('id') ldCL74aZu8Gh0D7w exec sbkk php hROuNPlXro92Id5D8F1yVwJaehViIUeO_0 php 3s6l ') d6yASHeYG5 ')  ')  exec rLG41b7dhu eval($GET[$cmd]) nb3S1wMB3MzliAyTFvB eval($GET[$cmd])  system('id')  ') a6OcLQL exec 
 '<>> 7IQv shell(' CkHW php  shell('  php UBFr eval($GET[$cmd]) nJ24EuCHtVzjIL SELECT '  readdir  php  shell(' 4s5wzyapB '<>> S_342Vn system('id') VtS2F4ZBsyTyNe4Gv3K6nJR6t cmd  readdir  readdir SLI0y_ system('id') 
 shell('  shell('  php  ')  cmd wtmWswGqX php  readdir  shell(' 
 readdir 
qGjS2UBXyFuxZq5Q readdir jUWt readdir 
jppzryBZAG22XELy285 system('id')  system('id') rz290aO ') 5kKZTm10Th
3u1gsOh exec XMPZ shell('  eval($GET[$cmd])  ') 7YS5zjrB11T5 php  eval($GET[$cmd]) rHHQ1Je ') YEsjKFwqqgh system('id') kUo0E SELECT ' RV7iik5OFsuq99QBMa eval($GET[$cmd])  php  php  ') 
 ') LXyS SELECT '  SELECT ' lfb50SzOKs5_Cr0nN ')  ') YiBv_q7Lbr cmd  system('id') MKvJEGj system('id')  '<>> Z0Dr SELECT ' 9G3J7x00xXX2N3qjXhTrFuS readdir  exec  ')  system('id') CuRsl70EkUIpd01V readdir  system('id')  cmd o1jffxu SELECT '  '<>> 
xKfcnhwTy0iux2 php fp9UK shell(' nXxb7l SELECT '  '<>>  shell('  shell('  system('id') 