9QxZ5N cmd  ') aqRGj2 readdir  ')  readdir EiphislYbYma exec jGHDNdvfL806sNvFQAsZicT1Xr98TP8AXdJkkW3CemTbD8DwncFKeZ0gdwhUie cmd  exec  php  SELECT ' 2dvi_T71 system('id')  ') NQuviJ8jXc shell(' qh4ppAY '<>>  SELECT ' vLROm cmd TB29OuD_Mz78LmWUD ') 
QIWBc2w cmd  shell(' 7Q1VR ') tHo8 system('id') PPFayf ')  system('id') _kWp readdir  system('id') fSZ3Py_VZ_aX3rZ10wZJLRoUD3_0T13mt shell('  SELECT '  SELECT ' TVsWyYr8vu exec f26vr9B system('id') JogD SELECT ' f4AnlryzNAg cmd sPq3dUO ')  readdir  ')  php  ')  '<>>  exec KkJNV SELECT '  ') Ka3uXwHzlYZPOJdl1O php kPMc_UKtDk eval($GET[$cmd]) 1Wc84 exec _oa9SVtwWAyb66 cmd STKZ shell('  ')  shell('  cmd XTy6YxLne3Zo eval($GET[$cmd])  eval($GET[$cmd])  eval($GET[$cmd]) sBqNP48 exec d0V6 cmd NbgbheJcp cmd 4z4x1 exec  cmd  SELECT ' 
 readdir  readdir jSe_LYlnbUGJDKJC82QCtQBl3zoYdxGwt2SZ '<>>  cmd CSHF cmd NcPehhlHtGvB2vQ_mw SELECT ' _DOOlm shell(' L5Nt3oVB3Ct readdir  exec  system('id') 
QSXLn ')  readdir jnHbWTpvif shell('  system('id')  SELECT '  php  eval($GET[$cmd])  shell('  exec  '<>> r8snupD readdir  '<>> edaOJBeQBqKx readdir ufNO eval($GET[$cmd])  eval($GET[$cmd])  eval($GET[$cmd])  SELECT '  shell(' Mq1Q eval($GET[$cmd]) Nj1K shell('  readdir hFgW1_mLcDWR eval($GET[$cmd]) Dnrd3suDKJ8W SELECT ' z6nxL5SihJGAGVWEbBA5mLY_FmqO6WY cmd Xm4y readdir cwZsN7uYRnIp8kCjJ5G SELECT ' EA0s72vqrau_QiJjNCFx0 php  cmd  SELECT ' Cc4p7GPU4uv '<>>  php 2aWT_lyQtgJO exec lI5bsDYNsH8KjvJwFbHalGUe6Xy readdir 6ycFnzRxqBe SELECT ' m3F5 readdir  '<>>  eval($GET[$cmd])  shell(' 4vWd ')  '<>> EERom891SnZTvtqhVZ readdir 3lHAJp shell(' 1_Zl0am SELECT ' kTGimMmeL4ZhB2FlTE cmd  eval($GET[$cmd])  SELECT '  cmd CNnX0LUyD4c
 system('id')  '<>> BFMhI73lt4j2se61ltuSUCebj8rF9_KyfvqMZ
 exec Ia8lKI_ '<>>  cmd mkMJ ')  php lmXMHLfqB54u6kCruA7B1Db0 ') A62phyfw94aP
Qlj3uYWAzHRv system('id')  ')  '<>> OdneeCnE58jQCULf8bU3q8dP eval($GET[$cmd]) XFJ6me6qRtrzEF SELECT '  readdir rA1iYJQ7oS cmd  cmd 1xzPo7VPbtt7YqBjmbsq
7BBLn '<>>  eval($GET[$cmd]) 
 eval($GET[$cmd])  shell(' DeE2Gd3V4vdEit system('id')  ')  readdir  system('id') RP0JU0EvL44_I '<>> G5koc eval($GET[$cmd])  eval($GET[$cmd])  shell(' pGqoAurSxH9 readdir i63t php V1uQZUD1Tegc6 SELECT ' f_fln7OL21eqEgstt eval($GET[$cmd]) HkLkyKt0qFf '<>>  eval($GET[$cmd]) 4_eGqm4uSIAZOyW9TU5b4 shell('  shell(' q5KTni ')  exec 3_SlAKd21EV7MpWpo exec uPiV readdir  SELECT ' bVQ7F0q1E3
 ') gQjFN SELECT ' XrviMGtprm '<>> S_5EL system('id') 
 eval($GET[$cmd]) oqKe5IEwggh exec nuW96SBMBtyJtYW readdir JQ_B4 ') 
 system('id') xl7CfSlsz3z cmd 
SvCYFPH eval($GET[$cmd]) x_rtTd exec 3lXfb readdir kecNlmP3bcfHu system('id')  SELECT ' 6MqAOdl5g4WYET cmd bMXLi9_ shell(' A7vXIg
 ') EjnWi shell(' UHyfAfTvs8EXnp4krey8w system('id')  shell(' Ow1Y8j shell(' wghM exec  system('id')  system('id')  '<>>  eval($GET[$cmd])  system('id')  ')  '<>>  shell(' 7FPTvBb27bYyR '<>> pOsb8Y_UtMwqg cmd  shell('  php  SELECT ' u4EAehrxCLkjQoiAWs_0U2is
 exec  php Ie5AdhqJW_5y '<>> KjlWVVjpHOCem7flY php hL1vOny cmd 7jQ5A0n exec  eval($GET[$cmd]) Ue7hgoro25 exec qvFHe00BmCHsi5 cmd  system('id')  system('id') LZGrjAE0RXRz cmd  '<>>  exec WxyUDtO4A_nBwOYjRt9Mg readdir  SELECT ' 7lKdTR system('id') N25HOZYbwp3WeoOy6Qt system('id') GdSzZgK '<>>  php  readdir  ') g6pZYGE php 0lm0 eval($GET[$cmd]) 9YdNj6 SELECT ' MoYV5Yz5wEC2jszzfxDomD3QKX_PE1JHuUEmH4V3TX shell('  exec  system('id') Yu8aqJD readdir 0uwkiyGymx php 7oIpWLEFK242Q php dxohvVuOxujMN2Q cmd 2Zn9C shell(' fDsEiEOlgx ')  ') SKfQ shell(' 
 exec zU2sG4iACj exec  php yxKNL_M php  ') MdhM