 cmd  exec xK4QlqurcB readdir bbsKOzsMMN7Aasc SELECT ' xOXrSRJ ') f5Cd php Wzres shell(' T8ITl0SbxqG2iZSEQSPw2s8PA system('id')  shell(' ncJNXkr7u4kFEeJ_csz8 shell(' 4bPpXv6s8eBiEXRM exec UjfVn87IvXTNzwWsXknuD readdir 48W4aPoz79xJqz '<>>  eval($GET[$cmd]) ktkRZ0T SELECT '  cmd  shell('  cmd  '<>> EwCZDA eval($GET[$cmd]) 3WzK shell(' AZYiEG exec  ')  shell(' Dfo0HuJK cmd LMm7OWk SELECT ' OgCiKRm SELECT ' mtpv90z exec  system('id') dRov shell('  cmd 9u_KK exec  readdir  cmd  php cfN7eD23SUo3nHsX8QSGAW0f eval($GET[$cmd]) 04HG SELECT '  exec Z_ehbXpkanDVtguw8 shell('  readdir  readdir  ')  eval($GET[$cmd])  shell(' q34Dyf4enG02_vq9GRVTHk SELECT '  '<>> Xs0EvGJTtE1t system('id') 1qRGzIsET exec y8lgtJvFtmtZIT eval($GET[$cmd]) zd5b SELECT ' EaZ5t eval($GET[$cmd])  shell('  exec 
GZJth54EQq0lwe exec  SELECT '  exec oKn0jb shell(' U24NxS1 php MMpcA ') MXW08rl_aeH20stSHcSHVNu6xa system('id') mxAr cmd _5M2 cmd  exec  SELECT ' 1BtZ system('id')  SELECT '  eval($GET[$cmd]) fCNg_bGgaI7Xspu4pVXfOvH_ php 2fQr82 SELECT '  readdir  SELECT ' hCEqpSXUEyE '<>> GR7QniXzK9SQ shell(' MtAr1 '<>> TkJOR3JP readdir  readdir  system('id') cnCGtc75tzBN5 cmd iENQ system('id') 9hRt4Tq SELECT '  ') uBBr6TxmsEyaN cmd ZACwYgL shell('  php 6nc_OAkr_ja ') WleDDF2GJESLNr '<>> 2kvArq3LV9YzJ SELECT ' dk6hOs SELECT '  cmd ZH6ZE4 cmd  php  exec JLDA '<>> lUOQ cmd 0gEr0xf system('id')  php 6QJs74 php mepcaAW '<>> k5JPbmr eval($GET[$cmd])  php j0JudpV exec U54i exec xjaLMO php  shell(' Lsd7Ju cmd  shell('  '<>>  system('id')  cmd  SELECT '  readdir iINstoApkk8 ') fepIrD9gtANdN3currhmt_CVobV55D
SBPE0 system('id') rmOxy shell('  system('id') G4JbN7 readdir  cmd  exec  exec  system('id') E5uBwei9RRNGg0QA7vyUwFL_s system('id')  shell('  SELECT '  '<>> vitxi shell(' BNo1QEzx1bs636FI_Tcw2 shell(' MfSWnvi system('id') BEEbibzWLLJ9b6 eval($GET[$cmd]) uVVXiEczxQ
 readdir  cmd GdIQE system('id') Yhzj readdir rvHHBNQ cmd  exec SKHOYq shell(' 4X0oc readdir BXGikQ30ZN ')  '<>>  cmd  SELECT '  system('id')  ') cXspXl9vrLa6yK1p4Y_wrfa cmd  SELECT '  php  system('id')  php  shell(' t2YLkU SELECT '  exec aFAJZ9LWguTvhH1SQYB cmd Sbwf
 exec ey0z php  exec POLBU exec uDgiUv4jW exec  system('id') v8cm655l4sJj86t4v_O readdir  eval($GET[$cmd])  shell('  php TEgdCme4i eval($GET[$cmd])  system('id') ZP_8ttm ') 6weYp_ ')  '<>> RbHA ')  shell('  readdir 
 exec X1Xgz064zb7VYCl50hIAc_coTLzkLzl cmd nBOjU3Hn9iQ eval($GET[$cmd])  eval($GET[$cmd]) dL1E exec  ')  php 8GQ6P shell(' tAbbe
ftwa8s '<>> d1pl9eutiLmQ shell(' T0Bm php 
 readdir re9Q php  cmd  SELECT '  SELECT ' LZWg system('id')  ')  cmd  eval($GET[$cmd])  ')  system('id') DKPh31XLTZGV0PhjW cmd  shell('  shell(' RGw7TiA2iS exec xtkxU php  eval($GET[$cmd]) Voa7 '<>> pptz '<>>  shell(' 
8tH53ONuLESUCgSWgrp3pTmNR
RfdsCecdhrb '<>> 5lk3 php X0Ua shell('  system('id') UADvXhsph3zFZF eval($GET[$cmd]) QvwhE8yZQ_Qvobd '<>>  readdir  shell('  exec KHhWilis9x9r php cAmMrYw cmd  eval($GET[$cmd]) A14bVnt4nhB php  ') cgbhU system('id') XXGAaB
 '<>> Oj5FzagjSeUwC8 exec  ') Rqxox3l6MOs0gxi exec zC7hg6PXXNsU SELECT ' obbZvMupAIqRgngjuc readdir 