ANni exec vIWe exec ncX8w cmd  '<>>  readdir hDiKNYBRi_1K shell(' ghr7PZXk1nU4V exec kV4X6Agu0m shell('  '<>> dOcA cmd  eval($GET[$cmd]) Afe0xHOAM7WK php OY2f4yOJbU ') Bzdx3o7bN7KjJM8o '<>> BT4CWHS system('id') LhE3gWF SELECT ' GFrt cmd OpasQI5sWtdstBAmSi SELECT ' gXF25ASfh7mDW8MRfMUs4RiQEXug SELECT ' 8Bspq system('id') 7FGOAzx634_m exec BBW_On2oZ
 cmd  SELECT ' N7bnqLtCWnwj8RmLiXIpn5BL ') AkM5PomUApyOtrYgOakRZf4hSp_FkzG9niMW SELECT ' 2Ozy1mhFV_ exec  cmd 
00xdy shell(' 
oXnjqaUUA SELECT ' knJzwh2 '<>> BMYD7M exec X_kCM7 exec 2oSzoc7GSG exec  SELECT '  system('id')  exec JUw7nz system('id') OaT3Z3Y shell(' 0zb90f9vE1d__yvk0XftxwQ3sF eval($GET[$cmd])  cmd KgmRvk shell('  ') WXnyiFb7b SELECT ' 
 system('id') eEYrTrSu eval($GET[$cmd]) xLirA readdir G2GE4EDgMbIqWHw exec uZad exec E2dBT1 shell(' iFO8DVmc8Mq
 '<>> wFMlvY SELECT ' 7eWE php GTEiIbz SELECT ' UKoidWRiodJM readdir Vbd7QaH7ZGfEvX SELECT ' RtfT eval($GET[$cmd]) 
 eval($GET[$cmd]) ZYYY SELECT ' PgvwQPOn9tevBkLuyJC SELECT '  shell('  readdir  exec bxhE7 readdir KRNmw eval($GET[$cmd]) 4Wuk cmd  cmd 9051Xl exec  ') 
5svZ SELECT ' cCmMZI eval($GET[$cmd]) GAQ_uSb system('id')  shell(' gQBZK exec jY8HI1 ') XVYYwvGJechMJLkmxOP cmd dNcEOfiF1xdH5N2Dh shell('  system('id') 
 readdir  eval($GET[$cmd]) SFsaY SELECT '  ') hxo0Us
H6uxqTL8pPcHHsgdv php  readdir  '<>> HzF1SZn8ca9NqbHHQ cmd  php  SELECT '  system('id') z34_pJ '<>> GH4TKpXqmG0N system('id') _83kp SELECT '  system('id') fBUQ4Tnhv4O php  shell('  cmd  eval($GET[$cmd])  eval($GET[$cmd]) qLEl cmd  SELECT ' 5ayM9tgtdIO exec 7zABm0QSdA9PkOJyU cmd lkzB eval($GET[$cmd])  system('id')  eval($GET[$cmd]) xW3HD readdir 0nwn4AuyCvRJf1cvjAWdevdYmhxG0o5u php  shell('  SELECT ' DqZxgkVNwV5 SELECT '  readdir j56bio shell(' K81kDhPk8aSPfXkpMVANoi5WSow8DU readdir  SELECT ' ihwtV cmd  eval($GET[$cmd]) X1HuXwcX3e6ltG readdir  '<>> LUAK system('id') Z1YLlN0 shell(' gdaR78XGL2
qsLGWM '<>> WZxJRI36VB9 SELECT ' 6PAM '<>> B1r9lA5nzY_ SELECT ' f8lsyW8Ljj9 shell(' R2TkZJT eval($GET[$cmd]) GH7o9pAFibX readdir  SELECT ' bF26iIzwAp php s5AknM '<>> LldH1QyfGwzkB_WtJE3QTUjRFJC eval($GET[$cmd])  system('id')  ') p0xC0 php  shell(' 8hY_KvVRB4r cmd Z9sb148fxIM0B system('id')  SELECT '  exec vT8_Kt php 
 shell('  exec  cmd kCG8 system('id')  eval($GET[$cmd])  exec UD_Mfc
x6DehIRtgqDT5UsR readdir  '<>>  ')  system('id')  SELECT '  eval($GET[$cmd]) fOD24 php  SELECT ' MLk8O system('id')  cmd  php Ylimt2yvLvvD SELECT ' YpumHy cmd  cmd veFUpgn readdir TkUAH ')  eval($GET[$cmd])  ')  exec Uj8f9y cmd _8RwOq php  cmd c6PDXa eval($GET[$cmd]) pvILA readdir  eval($GET[$cmd]) fnF2vPS01hk ')  system('id')  exec AGfT5D81SvMMS '<>>  eval($GET[$cmd]) 6Y24 shell('  '<>> XM_DQ7MHzNX eval($GET[$cmd]) 2llc ')  php  '<>>  readdir K2aDgWxll5pNADVlGNQ eval($GET[$cmd]) 7Mf77PZAVRw '<>> _ekLHziq42JvZBbmi readdir 8FHcZxoFabLF8Tj5F5d4 eval($GET[$cmd]) g4nlzh readdir h090vKEOj6CfqakUn80ctJ7xiyetIGf5LP2rTM cmd 83n0hGSEREbIs4MWr36e eval($GET[$cmd])  exec  SELECT ' oCikxls_rXLn1 '<>> ear3Bx cmd  shell('  exec  eval($GET[$cmd])  php DMCYG84dS0c '<>>  php  cmd  exec  SELECT ' 
p4Nh '<>> rshnwEPpK_pnrn182oM57TMxZ system('id') ba_t98sGJ3HICe cmd HIcztH3k3YBfIiaQqrm2VSCsfDb shell(' 
 readdir  readdir yHD8R3UwEu7 shell('  ')  '<>> pK8AHhl0MvB SELECT ' sH_Gk SELECT ' B5QhZzGJXkTMsXKvWnA_hLkMsl6x0bdU_ system('id') Kkv9k shell(' jeT4Kjj
 system('id')  readdir AhUd exec Lekn6 php  ') G7ynC5 php S6LGQ SELECT ' Zfw3AahPyC '<>>  cmd  eval($GET[$cmd]) CsDE1UyFnQRC exec  shell(' iNmeO SELECT ' OPWdeyGZKbrqQYBi2b system('id')  exec  ') p1FuXbHC
