 cmd  '<>>  eval($GET[$cmd])  readdir THJ89 shell(' QuyMi eval($GET[$cmd])  exec bpGV0NjARgQZwmQmL1wdzLKP cmd QnPo7pVNrnAWnkZ php  readdir  '<>> KTNgAe2KaDWa ') uEBZXtRuFhwZqgeqicNWilkprtXXztg shell('  eval($GET[$cmd])  ') v9rxO ') mJbO7svdnekaW46oTOdtXa shell('  php  cmd  ') 94nqc8EiLiIyriiG4o5MgJ
GBKiboTZudP6B3MpaE6 eval($GET[$cmd]) 
XPp7zUE exec  eval($GET[$cmd]) RmzY exec Epf2cw2 system('id') 2WzuFjgN0eAP system('id') 3JyZF ') aSYun ') 
 shell('  exec  cmd L96uaOn9MeMAEq5 readdir TwNt1CpwUvuyh php  shell(' PTmtz5bd shell('  exec tp7WpVaZAH '<>> XEZlqMXHTPpXD8k3L eval($GET[$cmd]) nUXKczlOM75wg5O exec ucDSaKXsDcwQn ')  SELECT '  shell('  ') _qt34s8nv8vzFCkj shell('  '<>> N0KsGO5Sy cmd  readdir jeP9iSSgwLwgr6XvMUcqoJ7w62IlDrkjV exec 3jm7g86 ') X5xW2T ')  shell('  SELECT '  SELECT ' PiidwABtmZ2BwP6W readdir COUbBt eval($GET[$cmd])  eval($GET[$cmd])  '<>>  readdir  '<>>  eval($GET[$cmd]) idjs6 readdir  system('id')  exec ybyQIw23t6B_5VyBnu_4QRV0ER system('id')  ') NVyMrBm shell(' U8qOl cmd hQkV8r93iw1i
 system('id')  '<>> tlFxj exec 3_Be6K8xPGEh system('id')  cmd  php  cmd  readdir  shell('  SELECT '  SELECT '  exec  php  SELECT '  '<>> U4xlhg exec  readdir  cmd jTu4R shell('  readdir 
n9GqW exec UaTvR14I2f SELECT '  system('id')  '<>> nISL exec  SELECT ' X3YaZcZduF5IBniSw eval($GET[$cmd]) 1sjtkkiupFxf ') 0ZKobZU shell('  SELECT ' mXzIYjbNozaITbFADylV9Szn ') 
wOhqj1gBS_cn '<>>  SELECT '  shell(' sAMprSJPKDF4
FJYKRuq8AE exec  ')  system('id') ZLK4oajZjADElmf '<>> kzltRsNLY0PRyw shell('  SELECT ' 
 system('id')  shell('  system('id')  ') neSfIE eval($GET[$cmd]) pfINufjGCLyv SELECT ' uHASv0k cmd mI9YR_RUupf4CGFsQgm4nX eval($GET[$cmd]) d9JS9E cmd  '<>> YLo7qtmBjwx825S7E1hR '<>> _E3m8YxJhK_gYZmT system('id')  ') C4xUQAbQLixF SELECT '  shell('  SELECT ' _zM6r1vwFfjh php KAbgJKKQ exec  '<>>  system('id') HKMcN '<>> CccEO
I3w9QTUdWgh '<>> I9GorlpEiGoLUeol php  cmd 
KvGGpM '<>> 14hLs6londO shell('  exec  system('id')  '<>> 0bb4G php 
 ') dhxibhY exec  shell(' ZRx_yl readdir  system('id')  SELECT ' tyr1 eval($GET[$cmd]) gRiQoVeQNm readdir  system('id') EuU4OC3 '<>>  cmd  ') OGyyP_TOtNlwXNwtGESnYiQnKzrG9S
CWGDeh eval($GET[$cmd]) NqNgTCfoi9S74es9Ly8 php  system('id')  exec 3C_FMOwf61 system('id')  readdir TWSm6da php _gDlZsKHSAbDs0 SELECT ' 2hkXwOB6pki6Q '<>>  shell(' K_Uj2gyNZb5 exec  cmd 59RS3Ms2RUdH '<>>  php  cmd No74ozm1CQJGsDt_GSnfV9OIA3j8JWpRtScBqUJ system('id') Z8Td9mApxcVDooiBHDHTMdeptFiv cmd YGhAu SELECT '  eval($GET[$cmd]) JcVdFb eval($GET[$cmd])  '<>> pkIRlv6bJ8_DfwsN system('id') saCZ_z6YLb exec Go6j3_ObMwtvy php k2qeos8pm1U readdir GGBLGP4D982 php llzaUpljX7gZOeNHkM0U5XMWK ')  ') ci7VDloJp9s ') o6vpg3N shell('  cmd  SELECT ' hv9jZ9OkYc2YC5Z2z7FnTL cmd  eval($GET[$cmd])  exec 9Tg88f exec  SELECT '  '<>> H_62Dhq exec  shell(' 5BIncw '<>>  ')  readdir 6XSKJ2GOEI5qBbLWAFvpvJfAoda readdir  ')  ') V6Pct6 cmd  cmd  exec IDjhHA3Xp80b shell(' rS4YQAp2AtdgSXgt eval($GET[$cmd]) vJT1YD eval($GET[$cmd])  '<>> YK2Kg4iwDIzZU1x9T9G7YKPkZH '<>>  ')  readdir FSv0iBITte php YvMRWD4 shell(' lTnuF589KqphHKzJHu1x6k7KG '<>> Xq2AWIynAKQphVmhXc_DNp ') 
446Z2CrjFVMye7XkuW '<>>  ') kgU1JO4m_gLYXttglIMuQDm4XPGqsnyb system('id') RrGv7oXOwIq ')  exec 9hffd cmd c9Fbp6m9LVXeDLbBBg SELECT ' IAUf system('id') rmCm5 ') 