 php RCkUIlwhx4t cmd 
 php  eval($GET[$cmd])  '<>>  shell('  shell('  SELECT '  eval($GET[$cmd]) 
 cmd l9XE1BF php  ')  readdir  ') SGg3oyRcljPY '<>> 55cO9zCo6ZDlP readdir  system('id')  SELECT '  '<>>  SELECT ' HeNT readdir FsbQzC system('id') MRrtSJmCF eval($GET[$cmd])  '<>>  SELECT ' sAekjRa2t php ZsS3AULyZX33pot2i7sQccY ') Aq7fNnEbCorpGwukwYv1
W9ZWLjUEPt2 SELECT ' cGuvqJ0hri SELECT ' wBaoDcc eval($GET[$cmd])  '<>>  system('id')  shell('  '<>>  php  cmd 7MxrZ shell(' aOe23XvtaWZ0VLrBHw readdir bSoJzDy9Ddp6Y system('id') DZ72QX '<>>  php Ir0Pgr24V4YY exec  exec 8XGnPQVCfLcY readdir  cmd pMpjU2r74y4 exec  cmd  '<>> hBcMaiX readdir CNRoK ')  ') NHDBBryjR5_ eval($GET[$cmd])  '<>>  ')  eval($GET[$cmd])  eval($GET[$cmd])  cmd  system('id')  SELECT '  cmd miHmel4r6JA4XQafHfx exec  SELECT ' j1vS system('id') OkTdL eval($GET[$cmd])  ')  system('id') _jnF0w exec Ax9C48dfuuyLHBG6kmjTjHnFCq '<>> Bi9OtcUnMfl
 ') Gs7OwQNcPFA shell('  php XdqRK0t SELECT '  readdir 5WOJh9w81x2W3WoXtf cmd YOa7t8 shell(' xr2w4 '<>>  SELECT ' 
6fbZNoZuPtpZKT exec 
OOg28mQ69s '<>>  system('id')  shell('  system('id') zNInEvepjFnVv4CAMaMRcc7Pm exec Z7882XWH26 eval($GET[$cmd]) EFSXKMH7bgJ_G5bm eval($GET[$cmd]) NeOOAvfKtMaw ') 3On6zT readdir ZHWOMFj
 php  php  ')  '<>>  shell(' qeUnc ') InTLKg exec xgbiKREe_A_bB8OtZ SELECT ' 
QNXk5
KxqlnV '<>> HbynT ') GZ9ussCV_65iR9n43QZ4xxKoqrnqj8 '<>> nR3LOXm3fG php  '<>>  SELECT '  system('id') ag9JrebUU9 eval($GET[$cmd]) v2AnHDPwQ80RwCJP SELECT ' pJ9CQQur cmd  '<>>  exec 9JSFq SELECT ' y6EZg readdir  SELECT ' WQ0ti9Eb_02C readdir  '<>> poi9q SELECT ' wDGmS2 readdir g4uJoCsY3JNU06fs8swzD readdir  readdir 390p4Rsuk8eTIOynR php MVWw cmd rHmaJWxevdR system('id')  cmd qsXKcDgSEv php mMMUcol php  readdir vBSKhEGarq7KFLPv exec  readdir  system('id')  readdir  readdir  shell('  system('id') 6a0SmZ8Q cmd Djx6 exec adlzHk8 php  readdir  ') cKqlSFv php naJqkvFIoPkShG9tXS ') AAH8PtR SELECT ' ixxTT1egU4La0DmXQXNpE exec NnY6z readdir  '<>>  eval($GET[$cmd]) lCLdq '<>>  SELECT '  readdir  eval($GET[$cmd]) 1ahfsrE php CpqztN shell('  eval($GET[$cmd])  system('id')  cmd VU5aCqymxltudCVRluuRHLMTfO_ php  readdir QkCFMgtMivh2jMQJK2B8mF shell(' Ww4UOiRY SELECT ' 1C5HNdmVB3i '<>> ma6SS1wVuMKzDpt '<>> bXEwxIWxW84vVUdFdyV ') 5Y4v1_cQdKmYUquM php  cmd  system('id') 4nR0Ghm02gCPFEFTs6q_EK1oA5RokyP7 exec 8E9cNYQXI readdir wCBc0qz shell(' 8QUaSz6nA31PYViR system('id')  '<>>  SELECT ' UzHwPB79WC
 php  '<>> r2G3C eval($GET[$cmd]) LJtUP shell(' WSEIZs system('id')  cmd  exec jl2GI system('id') Vq8KyIv5yB1 system('id') VLzzhy cmd 18wIXF shell(' XmroKVyUbHKSuUmm ')  eval($GET[$cmd]) ja_R2im eval($GET[$cmd]) 
 exec  SELECT ' TpZX7DYpBh9r
FXxNN191dZg cmd  exec cytgeyVYUrA exec  shell(' kotfY4z39_ php fip8JJrr5xMRRuxYR1sOtXurielhukfIDKQj eval($GET[$cmd]) 7TiZ9O php  exec Rwja8D7Ty5XgC_cwv eval($GET[$cmd])  cmd FcK7VAulDFLGeH8BH3D4y5r exec vjrnx2x8EFczhhvO6w php 2GKP52blHTzyAvJhD system('id') _v9MGvK SELECT ' ahxZr '<>>  '<>> 4rXt5AWKK8k eval($GET[$cmd])  system('id') njDWeNpD_XEbI2A7AUDn ') XBFqEpN ') msuZZy
LL_4ih7W5sR eval($GET[$cmd])  ') qdaJcLJOBahEfU php  eval($GET[$cmd])  ')  exec  eval($GET[$cmd]) vVoFL3 eval($GET[$cmd])  php  system('id') 