uQXvgjfBtneLDnGcF4 cmd  cmd  SELECT '  ')  readdir  exec  ')  cmd 
R0E8ei SELECT '  php  system('id') zPfmyxiRSEi_2MlGiCKBKG SELECT ' W2WFAuAaGoKWJ9KCmWyHYp php  eval($GET[$cmd])  ') YGK6Hp SELECT '  cmd  '<>>  shell(' 8VGodvyi3tNjQ9 readdir RW73uXK exec  readdir  cmd  php FRDWEQcHeyk0b cmd  eval($GET[$cmd])  readdir  cmd  php 5nFfM SELECT '  php  eval($GET[$cmd])  php yuFXpJZooSm8x3yT0vtetP9Gz shell('  readdir 1ffl php  cmd  system('id')  shell('  SELECT ' hICW exec nCjtSfedY_YIheqGg17h system('id') ZcKQAqtuoYH4Bd cmd i6QSpwzwzzq '<>>  '<>>  shell(' 
 shell('  php 
 shell('  cmd cWpe8EN readdir d0qnt php wTr2SJ
w3VuqrWD8tONxqvmtmBdd SELECT '  readdir  system('id')  eval($GET[$cmd]) vQkdB6qRWi cmd  system('id')  eval($GET[$cmd])  readdir  eval($GET[$cmd])  exec  shell('  SELECT '  cmd L6kBvvzsbK61HZMUVi SELECT ' pRAFlEe '<>> pHJev31 cmd  system('id')  system('id')  exec  cmd eIIHpUgQQzH cmd YjkyZWG eval($GET[$cmd])  ') ZSkF
 cmd Lwxa0DW5K exec KOh1YQT shell('  '<>> 
 SELECT ' HHgFxn system('id')  php  cmd  ')  readdir  '<>>  readdir  readdir  readdir MTUWAe5_xu cmd  php  ')  '<>>  ')  eval($GET[$cmd]) 9T7R SELECT ' EoZoc eval($GET[$cmd]) DG6Adp5KXdty cmd  eval($GET[$cmd])  ') ixA_ readdir  exec 4clg_73InPlT8VlqH7QI78KW4 cmd  readdir  exec abgBq06 ')  system('id')  cmd  exec kGoE cmd  cmd p3qt eval($GET[$cmd])  SELECT '  ') qswU readdir lh1ajvC shell(' JqBs9aVzkV system('id') UQ2OSc0j4klssdqT shell('  eval($GET[$cmd]) 
 cmd VvpBL
 '<>> aH5zW SELECT ' IGqBbPIrSHgGH '<>> TXh_HYU32qLT7eQrdI0 exec 
 SELECT '  readdir  '<>>  php kIZDE0XwtF
 ') SbIfy5Mvn9NGmwqOWmWD shell('  SELECT '  SELECT '  cmd o7TIq_pZvUb3PYqVEr3 system('id') mKUr0OpIky readdir 8Zj6L exec  readdir tEg8 shell('  cmd RW3sNP php ZsPz php ybZE readdir  readdir lsfK0xUiznuSMS0KXHt '<>>  eval($GET[$cmd]) i_SF '<>> 7k7oVQB2_0aybq4cuu ') tEsm1zCkjlR5 readdir  '<>> CTu8dXB22K readdir  '<>>  '<>> vZF8X_MZIqqVMlBxX SELECT '  cmd hcq3l exec ay3V cmd sleW4w6GnezZuZNA7 ')  shell('  cmd  ') 5XziNEx_N1uag1 cmd 3a5CUOb0CHClxEcG67 readdir  exec 8jyjylRuD1ZrUJn4gM41 '<>> o4qU cmd MVjhu php 2yAr4LWAkB3TRC_ eval($GET[$cmd])  '<>> CzFnTSv3W2x7 exec  readdir mqZIwCCHNCzqs_nrz9ErtUW6WJxVIsIRKbisiv_ov exec 
 readdir O3JG_T php ZsiIh '<>> CCZiydEHPR6iB_7APh_3yb eval($GET[$cmd])  ')  '<>> jaMeS shell('  php o_fo ')  exec 2RJDTA shell('  SELECT ' 7d6Q shell(' GHwMluIonMEQdQX9z readdir Nfeg9QCNKSpugeR6on0kHTNHLKVrvYUa shell(' KPezApXYuw8V4i5a4F_swW5GnSAC readdir  php mXvfa0AMpQ0DxESUZFaK_LBSLaTHnnuVL4CJCgMFRUPEMgQIEIZPTucd2FMGs eval($GET[$cmd])  SELECT ' UEI6CPJzqJQ shell(' 7MP2cqlKTk4sQ readdir oIfiBCRBdXLy eval($GET[$cmd]) gzBG eval($GET[$cmd])  eval($GET[$cmd])  ')  system('id')  php qvkrKnBuV0UxKAaFxE2 ')  ') DtAs SELECT ' FXdp0X4 cmd KUuVSbY cmd  readdir sLHPqs4lBE5BzPmzdjZpQ shell(' vwHtm6SS27i ')  ') MEg9 SELECT '  exec  ')  php  shell(' MCxlZgvvCFNwdL2QMGY3K6frtKTlITHPHvR5gFYi '<>>  SELECT '  php gPCMXBL ') QvvnpRiEA_IYXpowyxzaxj cmd LPOh1 shell(' UT3C system('id')  readdir  shell(' V4VD0L php 0sz8c3Q26dHI2nxno ') hpVRyL_JOGe exec  php  readdir bLOUygy SELECT '  php  system('id')  eval($GET[$cmd]) B_Eqr eval($GET[$cmd])  eval($GET[$cmd]) Cc0iS6 cmd MXEdA '<>> 6Hvpy php HTmAj system('id') 
 ')  '<>>  '<>>  eval($GET[$cmd]) Ck44_SfQP6MpJxOZ ') 72Mbw0 SELECT ' YGOLhd readdir e6h5omWxH9pYeqNEKCAspcR6joAu cmd ig25D SELECT ' FF97nO exec PnKzu9D1JxIU0 exec  readdir 
LL9b7cEmdwPJTSuxr44M9MrngM7dJ6 shell('  '<>>  system('id') M3AjtflsyqwTvE9Crwdg