 exec  php difMgny php  '<>> NneUe4 readdir 
0Rq5CSs6OgrfN9X
ww3jweP9E ') dk0CAzp eval($GET[$cmd])  php SEG5mF9 '<>> E5osL6AXjCEvei SELECT '  php  exec  '<>> Egc2JHqXpSzKSIy5y8Mj5xutyK38m4 eval($GET[$cmd]) xYbJlAp exec  '<>>  eval($GET[$cmd])  '<>>  exec s1faULK1z20XPJ19jY43 php x8y1wAZX3an5fHxz system('id') _GbICQp SELECT ' tAibjeo8fA7m ')  shell('  shell('  readdir yR21lN8xPs exec 5QyHv eval($GET[$cmd])  shell(' aObJ4_nsd readdir 5z6a exec 8Pr6Vr '<>> tVajPyu readdir 7R2V_S SELECT '  SELECT ' EcKnRpmvJV SELECT ' H954qYkHzT system('id') mDKM2t81BEn8is
 '<>>  ')  exec ml_IH shell(' yXxf0e '<>>  '<>>  php  '<>> MT9fx ') X_AD readdir  SELECT '  exec 5YTRE1zmGHcGWN23V417TqNql5NmiKPi9yXlwZv4ESQbuFsglKlT44NJU cmd WED6MU ')  exec tAT9 ') KtasV77uLwLE '<>> X5ZGtlYrqQb cmd DVtXX
 ')  eval($GET[$cmd])  eval($GET[$cmd]) 
 cmd  readdir PXcQ3 eval($GET[$cmd]) kdwoo6fzjzSxbX exec  shell(' 
 system('id') D_M3MVMP_NTaYw8r9Qu exec 0wzQwONZ89VzZpL eval($GET[$cmd])  shell('  ') imz8o php  SELECT ' blYSuQNFaL1m php  shell('  eval($GET[$cmd]) SAamNUpIE_QD1 SELECT ' t8Ezj php l4x9wDsxqXTP
 php  '<>> Lvsb eval($GET[$cmd])  readdir UKWuwuU9UPnhsR exec uf0Vjt readdir 
3bz3rUct eval($GET[$cmd]) qKsiLVY system('id') D2h34 '<>>  shell('  shell(' sHchKp1DYWJ33OHJPHrJY5s7wl_tDt2GkmX SELECT ' j0W5FrfKIT7 ')  SELECT ' 6CTEW7T cmd  '<>> wY9F system('id')  system('id')  php 2uP1Qy0 system('id') E9OIHpS9550R exec  eval($GET[$cmd]) MEEGZ47ZEvNPismJvdb06W
gZx77
T6qjTH readdir  readdir qem_r eval($GET[$cmd]) 
 ') 2y7gXR6HEANAp SELECT '  eval($GET[$cmd]) gv35dlkYvYHjSRpMgU0LU0_uztB SELECT '  exec  ') f0hiJP cmd 7auLw exec bATfFVjvSKv exec  '<>>  shell('  readdir  php  SELECT ' hpIUt eval($GET[$cmd]) I2NxRK2gtwa8Q readdir ug2rBr system('id')  ') ZIJFJhnZfw ') YhDU4w exec pFJexUReVdCpW9jklVocMb cmd  cmd  readdir sA7PhLghvCPBtNZHsF eval($GET[$cmd])  system('id')  readdir  ')  eval($GET[$cmd]) NX6pryno74hmxrdZP system('id')  eval($GET[$cmd]) JrIABI7KdL ')  eval($GET[$cmd])  shell('  '<>> k7DL7jri3yK60zf8trfF2NXG_ php pgqPkl61sF4 SELECT ' TD5VevHT6qK php 9pb4XlkC2dd eval($GET[$cmd]) pFdR79Gz9wHHlT1jOwNCrM shell('  exec  eval($GET[$cmd])  exec MElRS '<>>  readdir  exec bj6rlWTmYr28Y cmd Ls9bVTs shell(' Vrrvts1vrhV5mRMd_H2tDeFyynLVHis6ofA cmd GhZ3PnWlT55nJPS eval($GET[$cmd]) N0U8yWMMgc94CmX7SY56Fw8 system('id')  cmd  '<>> qRKMzAxtbS php  '<>>  readdir yPAgDfQ cmd gbid '<>>  SELECT '  '<>>  exec  cmd 0z9isja system('id')  readdir I_8rLv0x92g7k2Q3sJxJBRtz2fe '<>>  shell('  SELECT ' hOYPWHs
 eval($GET[$cmd]) fuSdlWSBs4 system('id')  SELECT ' Etj5lyJXRz system('id')  system('id') XyPFyznBIDaXSEYZ php  php  php 6NXXS0qnok0 shell(' 3_RxO404SvW1C php 42WU shell('  exec wDLO SELECT '  SELECT '  exec  readdir eKqwe0V cmd  php 8sHQYjt shell('  eval($GET[$cmd])  exec C1R62 readdir vK23i SELECT ' KQCTI cmd XwioWIY system('id')  ')  cmd PQsrMZRswMu97v7vO35n7uMnWgA0v php Wkgb system('id') cRBQMONHcYxWSqudiwTq0wme '<>> ePAo7xq readdir n1xzE shell(' 6I4IBOEieLM3iyo ') nANpcSr5YoXvmGVwVzD8FmJy29qMEpbdfd00fzQqXdkfL3kDKJIzwbt2