 readdir  SELECT ' M2Nfb readdir  shell('  php 
G4iC6 php eDY3A cmd 
 ') YURDJngE6b1ZohZkOT9R9euq cmd  SELECT ' _dcpYFpR
vthz eval($GET[$cmd])  system('id')  ') AfANHt php rx7f cmd  SELECT ' dtysIjeXFh eval($GET[$cmd]) cybBKkb4un1 eval($GET[$cmd]) HmaRO0WcyX cmd  '<>> WaPfluY3EV SELECT ' Fc0UVMtMdSj8kLh shell(' bao7kaR eval($GET[$cmd])  php  exec  system('id')  cmd  readdir QDzWmy readdir  shell('  system('id') uUqxrchsd7vE readdir  php  php  SELECT '  cmd VK9f3A6xb12uoT shell('  shell(' 6npWuXCZEWehRzN1Q8 ')  php FNhw system('id') ZqATZdBmuVL7 eval($GET[$cmd])  system('id')  system('id') pHBA0LrfmUjd6jXW exec  '<>> VxI1up68oIfXhABTI SELECT '  ')  exec 8DdOw2D9y0vI49
 readdir zNxU4uQ cmd UaIUtmr shell(' 42S4HA
HBQ3kYwRH7B47nbLTc1Sd SELECT ' IiZIn readdir  exec WeZrshMlXsM22 system('id') 8k9DFAfhY shell('  system('id')  cmd L8fQ3Oi shell(' 6IiWgak exec  cmd  '<>> VZfFkIt SELECT '  cmd CrbCnZKIltl SELECT ' 9AvEpWqF5vY exec  shell(' ThPPwVY system('id') huvcX1 exec xb4sMYxPYY php TLFy2yQ67FhMW_QA ')  system('id') xibFcL SELECT '  system('id') 
5woi4CDvpYhUw9x7aBTIhXGmjg8eIZ php  cmd 4PzW0 system('id') V_B7Z php DMuog3 ') JMu5BWYMNd9lN39sKEAUrm9 exec  cmd Fd7n system('id')  '<>>  exec 
 php 
BGvrW php dCZBym6Cd '<>>  shell(' 1l36or readdir  exec  readdir t7TGfWW9JM9OzcukIfABMVGjExD ') M_tq readdir rGcPRFHidxN SELECT ' x1HZBgT2nxCP1nV2wE_6nbSLrqn readdir  shell(' 5AH_irjUMgBk php 6tOtQnkHgbBHTEpqwQzt0 exec DTB_ exec  cmd  ') qwFhO SELECT ' GVYiyH '<>> Ttnipui6Xk php  '<>>  '<>>  exec  readdir vpOiesvtK5A6zw8CMEGp
swWaAnM system('id') SNySSK4ACEY '<>>  '<>>  SELECT ' KO68J exec  eval($GET[$cmd])  shell('  exec XOy5Cpv '<>> paJpm1L system('id') 7FGtIjOuREr9qSrOejtP_i
 eval($GET[$cmd]) DV1YqmMKynNanCvcOhzV system('id') P5IKT php 92qa4NaarDNbfxfCVMrCAM php auECoTeHtmtfGRrX8driXkr readdir  '<>>  ')  exec 6M5RL exec  exec  '<>> lLhF '<>>  '<>>  readdir H_SjnwTu8frnoA8VMVi ')  php rP7H1Y5i1W0 system('id')  shell(' o_oBd0 system('id') BTA3n6 eval($GET[$cmd]) 6nSxGmJkVlB_gZD2h7vA5gs cmd  ') X54TJOckIe eval($GET[$cmd])  '<>>  shell(' cKzCynPq readdir  cmd nBG_u3ZByE SELECT '  exec  cmd MtBXd5CC8Kq cmd bj7MdCJRfFqm readdir 7C1YjO0tfMvr ') jZD0
UmS1H cmd AtEdd '<>>  shell('  eval($GET[$cmd])  system('id')  ')  ') hcWBExM2bH9bqp_UCVWT readdir  system('id') 7GbmTg '<>> h4ms '<>>  ') 7PLbrq eval($GET[$cmd])  exec GAx2aIy SELECT '  exec nK4h ') kPhzY eval($GET[$cmd])  cmd  exec xXb_cG_ cmd  php a1SMua php USOjw1K exec  shell(' H2NmCy4Y53PFLru5H2V eval($GET[$cmd])  readdir  ') i72La ')  system('id')  php  system('id') d1qN7T_R5pwC shell('  system('id')  exec sP3aENfG28XIt readdir 