FBJ4u ')  shell('  SELECT ' TIdO SELECT '  '<>> 
 shell('  php ZArqr shell(' 
 ')  eval($GET[$cmd])  eval($GET[$cmd]) F4WI_V0VIpMht0AhcvIxsiA php yEp3Ty8t0eg1st exec  ')  php ZvLv8ET eval($GET[$cmd]) IM6m1 '<>>  shell(' JRtJdE0tz3vnmvzeQ8dU3 exec 1lBS0oqPZ4v readdir QoCUQ ') vNvgyu cmd  cmd  '<>>  '<>> n_5J_Vv exec 8yxvf php  cmd AFl6AU3GpL shell(' xYVx2FQ exec  readdir Bvkqu_Kphgu_5f4Fk8fBwjqr shell(' Xjmbx system('id') ghtRdA ') reaVA cmd  exec ukBjxbWdmp9 eval($GET[$cmd]) oLCy SELECT '  php 9EzYAQQigQZD_ '<>>  shell(' oD9k617NT50 eval($GET[$cmd]) KyuOOpqAnYD1bzhrQ php  readdir  system('id')  SELECT ' uRcIJl eval($GET[$cmd])  eval($GET[$cmd]) O9nNmT php 5Vls97T2aVc1v57Ah1q '<>>  shell('  php  '<>> YbGA53BfWQF '<>> ZJ3jWfkkeoxKT eval($GET[$cmd])  '<>> EFBwb
dH0YGsFYXtvV5O6Si system('id')  cmd S0Heg '<>>  php zZwQ '<>> XovB_WXOhH cmd Pte6AuXINF7exJoRawNuh shell(' x60A0_KTSVcJ ') ddjjc5q php ABDPJ SELECT ' jEBGP4B_jeuihmaO3H php  ')  eval($GET[$cmd])  SELECT ' leTB95LF0ZrXPGWKpn89hzm php  '<>> n4EqpBCP1OlAuqoBOLkLJRpiLlg4wz system('id') Tr51dh6Efxgl ') F730ciU eval($GET[$cmd]) nOPN ')  '<>>  system('id')  php  ') 8ubzots SELECT ' MreOBf7erBUiXGTYQ ')  php  ')  cmd  system('id')  SELECT ' teqhfEfe SELECT '  '<>> qF5h3Snx9kUe '<>> n5iGgu1 SELECT ' IiZ4UpuUbOubA shell(' e3Xxokr2AEzt ') Q0ZMmUY shell(' oCPt6Wc eval($GET[$cmd])  system('id')  shell('  SELECT '  shell(' NG6e eval($GET[$cmd])  '<>> TZuyuxzgQ system('id')  SELECT ' 
 shell(' cPtH6eTUzIEOIanOaPCUwguj03nvbO_XOiS7q
Mcv0V exec lCZVcEJ eval($GET[$cmd])  readdir  cmd  ')  SELECT '  exec  ')  shell('  ') QjegB20VNaAKui readdir  exec  system('id')  system('id') nbd00VAR system('id')  '<>> qWLBNtVyAKqmGfpBlo eval($GET[$cmd])  shell('  eval($GET[$cmd]) BN29W SELECT '  eval($GET[$cmd])  php  shell(' rfBmivB1 system('id') yFoxECZ eval($GET[$cmd])  eval($GET[$cmd]) v7WlC
cRYHZ ') S9TF exec P1LYhpM system('id') R63vF SELECT ' KfknG shell(' aLsaF3 cmd  system('id')  readdir  exec  cmd HWwvAME eval($GET[$cmd])  '<>>  ') KyLDeduSL3Vg system('id') rO8V3T system('id') zWQV eval($GET[$cmd]) kpjtTxZSyA_BpDgGZCIt SELECT ' 
O4ixPu5hkvZomA5NOwzaqzz SELECT ' 4lPIEE php  php BqZ2 readdir 62Yx system('id') pX6g system('id')  '<>>  shell(' FFLZNO ') iOJkDc eval($GET[$cmd])  exec JysJ51jhqeosS1bnd0GFWWgVmd8tljFFMH_5tTy readdir Cax_6h3 eval($GET[$cmd])  shell(' 5tQrJOtynv SELECT ' 
LPCRiWmBeT6K exec 3bTtLi7 system('id')  exec yr_hY system('id') qeN9O_Ktmv9N8_ cmd 74I_zSjlAweXBG eval($GET[$cmd]) WdchH98
7e2JzRLTrESxOzYpoXsDhiy8XNFI cmd  system('id') zXtPwdi '<>>  system('id') u1wYcnj '<>>  eval($GET[$cmd])  cmd  SELECT '  readdir  system('id') H0hNsEA3kGe readdir  exec  shell(' w6dLv66rueonuzWYCj4GlZ0x cmd 
Te08M2Ts6d2AF shell('  ') fadzvrpv66 '<>>  readdir  eval($GET[$cmd]) GK5_HwF cmd  php IeSX4TM3I0NGUiHfmW '<>>  ') JZ5YsdV cmd  ') Xne1K7VdBgQIVID eval($GET[$cmd]) oaXj6LP eval($GET[$cmd]) dHqYXXT ') kTSF shell(' L4Sc7 system('id')  '<>>  system('id') DLrDfKf '<>>  exec JWCb5z4Y eval($GET[$cmd]) FFgWDGcVJni exec  readdir  eval($GET[$cmd])  shell('  exec  readdir  '<>> P4P9Ywh SELECT '  shell('  SELECT ' ETLUzq cmd NnP3O eval($GET[$cmd])  php m_I3MCn cmd cQCmzj SELECT ' SHkE_OO54HkpFCT '<>>  exec PkQq4Vg SELECT '  ')  system('id') 
 system('id') Nu0KWlwQvZ3F24wH '<>>  SELECT ' ca65h php nr0i
1HBBaho6 SELECT ' VNFLndPzpJJ '<>> _ZoxN system('id') 
dpN25FS
6v4K4vEY3gvD exec  eval($GET[$cmd])  SELECT '  eval($GET[$cmd])  '<>>  SELECT '  ')  readdir wVyoGFv4gKCyPnP cmd  eval($GET[$cmd]) d85a eval($GET[$cmd]) czq19r php 
 SELECT ' ZCy3qZXFxRhmn2si0xUmkyWH_4loXwUobTclbW ')  ') YpgE readdir  readdir ZU7c exec  '<>> 3GjW