aLCr php 2NCg3Ay shell(' pGLtz shell('  php hlS57 readdir  shell('  system('id') 061EfluisnzB4mqCRs02HHZIwcrkoN9 readdir zg90AZ1 cmd Al2Thpssk57A php X8TpDPZ79iB48S23rfZcCa3huY shell('  php  SELECT ' NJx1Dvd eval($GET[$cmd]) jAaiZA9Vobdh cmd YTpI9ZPKMd8 eval($GET[$cmd]) EmAYFecrmG eval($GET[$cmd])  '<>>  system('id')  '<>>  SELECT ' 1hPCZU php Yc8qJ91MlgX
s9YjX shell(' t4wBj3XWaQslmv eval($GET[$cmd])  eval($GET[$cmd]) UBgcmqoUYxUvlWeHZA exec  shell(' mKkWnCr SELECT ' ogGngs php MNePWr readdir  system('id')  php 3kw_ eval($GET[$cmd])  cmd  system('id')  exec QNKoWsMIUkIVcTjiXDdy4f5TZghw ')  cmd  exec  cmd XOlygizx0bUj cmd  cmd  php y5BG '<>>  shell(' RkKh exec 
 shell(' DaoJxW system('id')  readdir cBUDkB65OIzA1UbqGcZd shell('  php  exec  cmd 
 shell('  eval($GET[$cmd]) 6fxgRz09C '<>>  SELECT ' 
 shell(' ZACt9PgdrYlzMvKyqN6vO8lK2n cmd  ') 3Mhpo7 shell('  '<>>  shell('  system('id') Mvva76 php  eval($GET[$cmd]) mmdrRggHD shell('  '<>> pne2xgfzI3jhqO61t exec  cmd  php 2q4tEMBgy shell(' yLmN_ exec Q0u3LxXGsNs1Sow exec ccXGcguD8X4a eval($GET[$cmd]) SuYR9Ns ')  ') qhGEtCe8GCNzlJzX9F eval($GET[$cmd])  cmd aTnTJw2OKB1 shell('  exec Z5870b4fHBlE_ shell('  cmd  shell(' Ire9A8 ') EDWN_azgQQ ') sDq_sld php  readdir Jdznqb9iBtl shell('  exec  eval($GET[$cmd])  cmd 564t4XgXa_mW system('id')  readdir  php  php  shell('  ')  shell('  eval($GET[$cmd]) 
 readdir TFy4rNWoLbY4UA02e344774o7ghxC eval($GET[$cmd]) wZFDNGl7eqUfG7fQj shell(' fyLEk3OK0WDZQaG system('id') l2inG SELECT ' OOPsZ9 system('id')  php  shell('  cmd  cmd yUIYIfTaRxsi6Hx readdir  exec hE2B5 ') pBFZ '<>>  cmd  shell(' wykP353HN1eE56ERpsC SELECT ' ZlHTAY3CRQ4g ') Il2EbZ8y292wn_EC9uW SELECT ' wPHC2 php  php  shell(' n22Rg_b ')  eval($GET[$cmd]) YXIyA SELECT '  '<>>  exec  shell('  eval($GET[$cmd])  eval($GET[$cmd])  SELECT ' SZEnKnMDjPy exec  shell('  cmd AZbW '<>> QlmUwYPZXAW eval($GET[$cmd]) Wm5i eval($GET[$cmd]) 
 ')  SELECT ' OQ9E1 SELECT ' k2U2wF '<>>  ')  ') EI1RX7LluRdRNjkjGGJ5XZN
 readdir oiSK_BNci57 SELECT ' HZPsWqz ') r1pTz SELECT '  '<>>  readdir  exec  ') Q_xrL2DllASA eval($GET[$cmd])  cmd _gZzd system('id') GhujypbZYFqe9 '<>> d3RU php  SELECT '  ') 2q43u shell('  eval($GET[$cmd]) IGb9I6AwAIL5Usajx '<>>  '<>>  system('id') XMxbf ') Nweu9 eval($GET[$cmd])  readdir MvEbl shell(' B5lcO1 readdir jny06ye cmd  cmd  '<>>  eval($GET[$cmd])  exec  cmd txKOVo cmd F4rry '<>> 
 php 
 readdir kh4s5oQTh2 exec BGvHCqf ')  SELECT ' 
 SELECT ' vAOs8WdlApuU system('id')  eval($GET[$cmd]) up0AOyg readdir  SELECT ' zS8JEArD php KQxl9 exec 2H3SzsbRqCNVzew2UQD2K78vz readdir  exec  '<>> Q7xYq6UEEYi5gKp system('id') JSwFSEBDFq1aAnRzj '<>> FGi_Yqomaz_uMofBJ1s readdir MaXEWKh php cnNJwbg eval($GET[$cmd]) sLmhL4cLDdJmoFD05G ') _2RfBT exec  shell('  eval($GET[$cmd])  shell(' FIxt shell('  php  SELECT ' FWSR shell('  php  system('id') PYK4Dx450nIP '<>>  '<>> 
 exec  exec dHqG8Zba28wAZ system('id') Mlv8S0TC5_qDC58 system('id')  SELECT ' RrUg8EHxwx eval($GET[$cmd])  cmd Q8K2SGFcRrn ') rbR9p2i
iGCcFB1eR ')  readdir mtWjE php  eval($GET[$cmd])  exec  exec  shell(' TSTT4m php  '<>>  system('id')  cmd rzTOZgE_uOTY9Te0rRE0tr4ri SELECT '  shell('  SELECT ' H8LXA4CxHFof_Hc cmd CzcaY cmd  exec  exec  eval($GET[$cmd])  shell(' yNVnv4k