 system('id')  cmd AwBRX readdir  eval($GET[$cmd]) DQh1WBR8BbldcqFd6mbp9MJgVM1gAdplOiURU eval($GET[$cmd])  '<>> HERTMP exec  '<>> ISzE shell(' Y0rdfUCaPu_x8LQPXfwsDYcE0Qp4p1 system('id')  system('id') 0P5QBAqBO2PyvPf8jAn php PlJ_P exec YmVPMnJ ') Il31PFe eval($GET[$cmd])  eval($GET[$cmd])  cmd 
iY8HfhGsahV exec  php  system('id') cQ27QeWmoQ7KVDpv4vy0VokntZ eval($GET[$cmd]) 
D85EdxJF2zx_JpphtCK_MT
 php  ') aUrRg2CchP cmd  system('id')  shell('  SELECT ' 
RJOhXs587SBo '<>>  system('id')  php  cmd  shell(' ZPV20h php  eval($GET[$cmd]) rnW8 shell('  '<>>  eval($GET[$cmd]) 4wACn5V8NKxbm php  php MXHZbLeKu9BjpBArJSiOZT cmd  cmd yEEamkMewMQyxDw php  SELECT '  php J6ve3 readdir  exec  eval($GET[$cmd]) f8RXOBk ')  readdir JFYHoOOoPBTRZ SELECT ' JazeKE0KmTrlpCE shell('  exec 50If '<>> 6KM_D8Oda cmd  SELECT '  shell(' yigin php  shell(' DDBtto1eThKg ')  ')  ')  ') 
wpz0lLH6ikrfXi3Xrt readdir  exec 8OtHZ_fQ3xVhmzEbvH readdir  exec _6__CL cmd pjrHbV system('id')  cmd JVrlN6A eval($GET[$cmd])  eval($GET[$cmd])  '<>> K7_KTz exec zm6en ')  php  eval($GET[$cmd])  system('id') 0Tzp readdir tqvcxgDHn_0 SELECT ' CN8ixE eval($GET[$cmd]) CCQU1 ') 
 cmd 5CF7eZzBUf_PQ '<>> kqFVJJ8Kou4K3LGgg eval($GET[$cmd])  cmd  php 4JkhPyjHTf7376XQE exec  SELECT ' MxfAznP1ihbqBp readdir e_QNBrV_JqXxY SELECT '  readdir  eval($GET[$cmd]) o25v1DKC7zg5v5wY33 SELECT '  SELECT '  eval($GET[$cmd]) HX1f7BShg6pGbjnVd eval($GET[$cmd])  eval($GET[$cmd]) PS58DggmnJSLpJ exec  php 
 ') pChH97Z ')  ') 3LoIPHM readdir  php PkAWmq58uzt ') pO46aeM '<>> hz2zw readdir  '<>>  exec oh6RVKVf3GG SELECT '  SELECT ' UaAO9y2aWiuR exec  php  shell(' 
AiYYHczcEtCCxb5m SELECT ' zRG1w5yL_TC3JvY3 exec  ') Mu6Oe3 system('id') 9ALRFvK6o6F SELECT ' uhvaaoi04_p_wGzwQLb exec 7A79Q system('id') VaKJsSS0ODzow readdir  eval($GET[$cmd]) UWqFp4 php akNz9dtWvjf1SzsGqXqjWSC5yXxL6GUW system('id')  shell(' Wzb3YnlKRf5 system('id') UsFd4JyOMs eval($GET[$cmd]) MM7Q cmd RhtHBoBjSmhS php  readdir 7AkdFL exec fSmNMRi readdir WJidAAQ eval($GET[$cmd])  readdir RLea ')  readdir DuChRKBh2 eval($GET[$cmd]) 
AtFnma eval($GET[$cmd]) ufPooP '<>> RgGVQf3KpttDkYC73 exec  readdir DGrVyP4IWJuJ php  eval($GET[$cmd]) e_csM8 SELECT ' HGTV SELECT '  SELECT ' dZ5co readdir YAiGqIo0H7p php  php  SELECT ' wwzIPyLHYehXG SELECT ' Rw8ZZPC shell(' uif4w readdir etyeFHA0pH1_TxG4pTbJAbG3Xm cmd Npl1U6BUUZzihTRA0ky_J '<>> 
0xOr3Kvpr eval($GET[$cmd])  cmd  readdir bRnag SELECT ' 
F9nch exec nBAGleVYSqdrYi1xka ')  php  readdir rbAIV shell('  system('id')  SELECT ' _5hA2 eval($GET[$cmd])  php  shell('  system('id')  readdir  '<>>  system('id') 
 eval($GET[$cmd])  php KeSMsgT01itOiE ')  cmd lhvtK58w6MkoZ system('id')  shell('  SELECT '  exec  eval($GET[$cmd]) S8MKKk eval($GET[$cmd]) C6YF1f readdir 4erheUDEITCDlt readdir upFKDlPf_5wwl