CVX0ooO exec dSkTfJ shell(' oKUx system('id')  eval($GET[$cmd]) M7FFxc9S9dqNrfza eval($GET[$cmd]) 7m2sgDF exec HjtKC '<>> 
 php  SELECT '  cmd  '<>> p5SnrJtfnzAH_EPUGbggeLm '<>>  eval($GET[$cmd])  shell('  shell('  readdir B2bN eval($GET[$cmd])  php ZdR89sy_LZBEOS '<>>  cmd 9xCH ') 
 eval($GET[$cmd]) Bv3EWC exec  readdir  '<>> jh2aHIq2u7nK '<>> PhkPKB exec GrnhYJ4eMIFVDqwMAnn7eO cmd  exec  ') hiqNxVRgtdt1HpiTFhF shell('  system('id')  system('id') 61yRx readdir  SELECT ' CkS3lwM exec 5kCS_t cmd  cmd wAdx0ypNFwd ')  shell(' HOpk ')  readdir  eval($GET[$cmd])  cmd Pl9vKG1D0NE1BvwC99O4YQq1H6wn eval($GET[$cmd])  php  cmd  eval($GET[$cmd]) plSfZ eval($GET[$cmd])  php 26DjgERADxdlYsrsxgRICiQPcT1 '<>>  system('id')  ')  readdir  SELECT '  php J9RuYC readdir RHLXQlca2ysHscYSk eval($GET[$cmd]) mjWHWp shell(' 0N0NcA7 ') OVBgI system('id') v2feejK exec qiKNen readdir la7be system('id')  cmd  php PbdF shell(' AdT5X0SpAmkg3CyoY_ system('id') 9EhZs190Szprw0bFP6 cmd DFSrnn system('id') t4QLaDI cmd  php daQQc cmd 
m94ZzEKo2fuc3U shell('  '<>> EmrTes eval($GET[$cmd]) lre8wAKpdt_ox system('id')  ')  readdir RgvXLNCOh '<>> a3K2qCCOFQtDRn exec  shell(' ziw30S3 cmd  shell('  eval($GET[$cmd])  shell(' YJcgDRHthO8z ') p8H3B_eQoEr6yp8pwMZCXNXG1 '<>> 2c22q '<>> z_PkcG9bSuGp8 SELECT '  exec 
i1wBrPdw3e4 shell('  readdir YsFKd cmd  eval($GET[$cmd]) Wki3 cmd B8se cmd  shell('  exec kHSnY exec  cmd if61N SELECT '  system('id') VEZeplv cmd  system('id')  SELECT ' O8hNtK ')  readdir yiwe8ocus shell(' vOehpYG
Zvr3R6JYSN8r8zR_ZmS6wpW system('id') aPTIAf shell(' 2qSiE
 shell('  readdir  cmd  shell(' LvqmRZm shell('  readdir RhYeC3sr3EooYyVdJ2JOVpP '<>> iC_LapAP ')  readdir  system('id')  SELECT '  ')  SELECT ' 8D5kPmGjrxJUr1LZ8b php  SELECT ' DH_AJD php  '<>> rLAWSI ') MR_NLCSrsCs_zZ2L9 exec qZSgH7PgIVGKEx_gVHC system('id')  shell(' jRQTwrKD5VlAa2 exec z8nIWVo system('id') lFVlh7UG8dUU6
yzOsIniyh '<>>  shell(' MfPPruB9rX readdir  exec XxCUut ') QfZbKoFAnP ') ZSJe SELECT '  system('id') N1jqE1g1ZjZjXZQz
 SELECT '  SELECT ' WJgfa3 system('id') 8NgpuL8EL9Yh cmd  cmd  system('id')  ')  exec  eval($GET[$cmd]) 4QbXq '<>> tcmlQDxdFsC8vEDYar_k8xuZv3dY_v3Rrh system('id')  SELECT '  ') xzrBswupqw9v4 cmd rcbA1p '<>>  shell('  '<>> zbQ9I shell('  readdir F44KWX7Wxfmr exec  SELECT '  eval($GET[$cmd])  ')  ')  shell('  eval($GET[$cmd]) vTKZ readdir 
e5s4JDV SELECT ' zyM1 system('id')  '<>> YmJjW6lpxmuiL php hbWH1 SELECT '  readdir xRVYQ6
 eval($GET[$cmd]) d0BM_QeQ4Ablk eval($GET[$cmd]) dhRuBXA eval($GET[$cmd]) eSF01J '<>> 6Vc_O8 SELECT '  eval($GET[$cmd]) fTwx system('id') kIWvuM cmd  cmd  shell(' uYcBotYjdQIG2MJVKy
 '<>>  readdir  php 9Okzh readdir 7VzgT readdir 2daJ4oX cmd  ') QBHMuC2kDm php  SELECT '  SELECT '  shell('  exec JEedpRe cmd  readdir f6d4vdY56j8 system('id') c3f1 SELECT ' kDotq_0W0GQgGtSo '<>> kVoS readdir 6VAt readdir  '<>>  exec  ') Q4fsGDnJUMbTPcGwlb9c php 