 '<>>  eval($GET[$cmd]) ky9e_x_l8nBdv '<>> 4SAe7UbukyV system('id')  SELECT ' WiuD shell(' LNHm8 shell('  readdir  shell('  system('id') CeOSMl9Df9P2rrxBwF5M4Pyik exec  SELECT '  ')  exec  '<>>  SELECT '  exec VXsZosKgAr9M readdir  cmd  ') FdYh exec 
VWVxtY php  '<>> 
 system('id')  SELECT ' axwmwPHp php nK9oF2wGcQio eval($GET[$cmd])  system('id') CFOn cmd SH24 php  php Bc0cJKh '<>>  ') bsRmYw '<>>  exec  readdir  php  readdir  ') 3Jk76MDCiLXOU3fwZb
BQzQXBpf_7mZU3Z cmd  readdir  system('id') 
 '<>> 6MXZSp exec  readdir  '<>>  SELECT '  readdir  exec  SELECT ' 3ggZh9LdiN4p6KD exec pCmQKJw04O2I_b3ks
 shell(' yj0avoh ')  php  shell(' YvdOMs ') 5qHr_WmuxY7 '<>>  cmd Bc5kPBQQHRugRdPpVz php 53rTxVU cmd _5T78XOjEzk system('id')  ') jyoBh readdir l9z5vQ92DnEFeaTZNtMPfjJl1 php  readdir YtMPDa cmd 18CAZ9Slthf ') 5oxSjw3SDSrTQZv9V readdir  eval($GET[$cmd]) VUrxbsgOVk readdir  shell('  exec  eval($GET[$cmd])  php tJP3BkjuX
UwRWsv
yTZp '<>>  SELECT ' 3InzKa7xW1 readdir VtBA5PGaVLz '<>> wFh_od1 '<>>  SELECT '  readdir  ') ZU0yKibsCOi system('id') LIsx_JD5JL9G cmd FqOWCpqBtXo37iRzo system('id') QF_g exec  eval($GET[$cmd])  cmd JYuCx '<>> 5Fp3SJr eval($GET[$cmd]) 2Bze ')  readdir v3ww0H6c_HPCamScm6vM readdir  SELECT '  php PyT1c_j SELECT ' c0EJ SELECT '  '<>>  ') jqsuObkofuQZc cmd  cmd  exec xLBV4CeppCtQshPtxqONm6fwUS0 php  '<>>  exec  ') orqQu_PJI0atzb8urDFlRARPlNqoey cmd  cmd  eval($GET[$cmd])  cmd CO0U system('id')  SELECT ' Ew5VXc php QPFADdFG9i58ZMTM8tz cmd  exec 10GNy SELECT '  SELECT ' 9uOFqAx shell('  php  shell(' dsYYso3ozAEG exec WJg4F ') rIMRqXI system('id') Hiiife cmd  exec RzQtZ eval($GET[$cmd]) r0cAMYHoKQOULBC SELECT '  ') OZvcNV eval($GET[$cmd]) dPHDuzIi96iquVZ0Y exec SmEmB system('id')  '<>>  exec 7cRfFG0TfTw32mht system('id')  eval($GET[$cmd])  eval($GET[$cmd])  '<>> oV2Z system('id') QmIa
SRimvRk ') cRZEOT6 exec  exec  eval($GET[$cmd])  readdir 0QKy '<>>  php en2lkjxSliGWuAl php 0l6ePuT shell('  eval($GET[$cmd]) zApjyg SELECT ' GKKJ7 exec  eval($GET[$cmd])  php  exec  eval($GET[$cmd])  cmd  system('id')  eval($GET[$cmd]) Bq8ANmQ cmd 
 readdir  php EDBoBGkCyjto exec Aojdnsq '<>> 46YK8Ms exec  eval($GET[$cmd]) SBne0ci readdir  SELECT ' S54TwcY exec XP9v '<>> B2ylpWgoWt eval($GET[$cmd]) Q03E '<>>  SELECT '  system('id')  exec  SELECT '  exec  cmd  '<>> rFyz '<>>  readdir bwXv readdir lzZzdxa readdir EYIbRNQ9p php _LMNoTCG9 cmd 9isGK3g7zyGfi1a48dJbg4 SELECT '  ')  exec Cro8fqz system('id')  system('id') ACHzBUpvzr system('id')  eval($GET[$cmd])  readdir knL_BDFll91QwDH3dmBxSmF ') BfCJjk_e2eI '<>> q_FO4wp08DF69JVu2d cmd 01Qh4NJaP8bXqKePxH8B12IfMgOMyZ eval($GET[$cmd]) N9rUMc system('id')  eval($GET[$cmd])  php cfJHNJ6lndb3vKFpL php lYcRD1 eval($GET[$cmd]) xDw420H9R2_Y13XBLi system('id')  '<>> 
 ')  system('id')  exec  SELECT ' FuT3 php ixkm85
 php  SELECT ' cZ7B shell(' 4aRJA
gl0FGBOaSvwNsAxy8If3h61q exec 