FwXPanhdWhBZI exec  readdir  '<>>  exec k1fEqaMz04oWlOpebdCLhyF readdir  cmd HBAjjg7s '<>> U2L_5 cmd 4vTyL SELECT '  shell('  ') 5Q_EYrzetlsvDwZWA3Lav3h4Ihq SELECT '  shell('  shell('  ') jYZKaPU3h7OP shell(' xASEPg6PgnDp9qkrw7 SELECT ' 55pbUlW readdir 2abxYev5YELrVuQChesvo2x eval($GET[$cmd])  system('id') fhbRld exec  system('id') mV6hJ eval($GET[$cmd]) CYawi SELECT '  eval($GET[$cmd])  shell(' pzVkQB shell(' tXyp '<>>  system('id')  cmd  php  cmd gdcp ')  eval($GET[$cmd]) FMUiU5gifvX ')  readdir 30tf SELECT '  ')  readdir  php  ')  SELECT ' jtzZf SELECT ' X70w readdir  ') ywL0E ') oCQo readdir kE7qUy4hz0XNtEmexi5WZVrB exec 9qWYx exec FqH89c0 shell('  ') wCm27pXTKyxA367vULDz5 SELECT '  system('id') 
coY4kvXEhb cmd  exec  shell('  exec uiPDitHKO5dx exec  ') AguJF9CkdqU ') OJlcH2kqVSe6V system('id') dP8X3jRwvs '<>>  SELECT ' 8Ckk7 eval($GET[$cmd])  exec _VxISTxCqMjocBtzU5vyNQ php  exec ZWHFi6 '<>>  php  '<>> nosfK77
HyEhJQxvrbbTQQayR5IMWzNya1EqGNFET0D cmd Z5Vw ') zS01mDDfAJBoOko8RvHzf6qNxJq
 cmd  php RHYzHuEONjvMH php S56Nj5I system('id')  SELECT '  system('id')  cmd 87ZTXq4eep6f_ eval($GET[$cmd])  php 88Zht3HwOp readdir TF1_d6x28gPflwgw0P shell(' uNIpWp3MU9fg6UNPVs1MQ8Q eval($GET[$cmd])  readdir  php TEASdW exec vzguoI shell(' n3W0xXSESwPQ3GobztUr cmd  system('id') mZnKOOxhT7ZWRFKSD eval($GET[$cmd]) qk8drIFh6ganEeeNbiQT28 '<>> 2cz0WH_J3rslVKTPSEaRG0aE3JKOg1Y1NsO6PzdGUBgky_ readdir  cmd  shell(' 
 shell('  '<>>  system('id')  cmd  php  readdir  eval($GET[$cmd]) VCJsSN eval($GET[$cmd])  '<>> 
 php anOfj php Fn2yMtYSW7 php KJYXjS system('id')  SELECT '  readdir  ')  shell(' E7vj readdir  system('id') 1Q7i eval($GET[$cmd])  '<>>  ')  shell('  readdir 4DpIsFXhgg system('id') jeC2f SELECT '  eval($GET[$cmd])  SELECT ' jUPcgb1r shell('  system('id')  ')  cmd 9v10 system('id')  ')  SELECT '  shell('  readdir ozOSh5 '<>> 
FsRyPel ') 5GiInA5SfKNP ') 4YpA4 SELECT '  SELECT '  php dcmYPR8PM2wFq shell('  SELECT '  '<>>  SELECT '  ')  ') 
 readdir anilPgzKSz exec  shell('  cmd SzheoN readdir  system('id')  SELECT ' uoeY8
9ZpIQ
jG7r8 '<>> xOTlepxuO96e
 exec enmpbxXAI6_LVogibYGanDU_cK readdir  shell(' VYUbjCD cmd cdL1i SELECT '  php nKGPbFg shell('  '<>> otJvxow shell(' eakd readdir  '<>> SmOtdWGQwDfpRdMahZ_n system('id')  cmd  shell(' bJf6Tjl0vMD5fpnVev system('id') qRn7UEHp1QBNC2p readdir  readdir cfVipg7 '<>> F5Is54ED4 ')  eval($GET[$cmd]) Ku8e68GFwY6 readdir HvJQ5pL '<>>  eval($GET[$cmd]) R5yY2Ewkwrngy__gsL13cy shell('  cmd NNPF6 ')  php  readdir Kyama ')  ') 3S2R9 eval($GET[$cmd]) _YLWnGrJNJ6PIpBY shell(' y57PxC5w19God php  ') dnILKO8 '<>>  cmd  '<>>  exec  shell(' R4vLbMcHQHaveg0OslQpD8KcnU3HoD46w6GT3LZR71X4 system('id') rZMKuvvPgk8tH cmd  SELECT ' CWHs5DjP shell(' RT4g eval($GET[$cmd])  shell(' pKMpk ')  shell(' GrreEJgR2ab eval($GET[$cmd])  cmd  php  shell('  php  system('id') wyIwyfdGvRVZyRVGKRs6xlF9XUU6ofQUjkCe SELECT '  ') TvD7M6G system('id')  readdir  readdir ZFEJ5j2 '<>>  shell('  php  cmd ciOu exec  system('id') myGE4IQ996Vy exec  cmd  php  ')  shell('  php  readdir XcXq exec  '<>>  php OAfah exec UK2WZ shell(' nlwd3J system('id') wCnRs cmd 0ebQXqZ php jeEJ '<>>  php  exec  system('id')  exec  php  php 