NiaGlml6oL1 shell(' Ze_QBrT6wrpNJwymfwzGXD readdir  '<>>  php tXiAdLy system('id')  cmd  system('id')  cmd rDslGC47A2_Br47Xqv '<>>  eval($GET[$cmd]) crzQut readdir 03i8UMLUaJblO05Sr
 eval($GET[$cmd])  readdir  shell(' V_S3QCe exec s82G60rtQ_Y system('id')  shell('  eval($GET[$cmd])  SELECT '  readdir 
A73yrQJA_C readdir vM0NGPQOJ7eQ2GyMUM2 system('id')  readdir  '<>>  exec XPEsLXA5WK exec 7txEk readdir  shell('  system('id') _KfJPA shell(' 5TWN
hMKCXCFKo shell(' pG9BypeNcvp7McvpfdD3 system('id')  SELECT ' 3Yp0C7QEVbqmK system('id')  eval($GET[$cmd]) fBe07QQxS9dg1ZlTUoNnb3mRh5l ') l1yp shell(' WaIPf_ZND_7 exec  '<>>  shell(' xP3GvTr cmd  shell('  readdir  '<>>  eval($GET[$cmd]) ZC9IHFEwmIFAhG exec GX7_f eval($GET[$cmd]) 
 '<>> xhOn2G7OGcF7 ')  system('id') 4dtLcYDk7ehQTL14dtwhAW64TQ php 8yy5 cmd  cmd YPRNmZy php  SELECT ' kX7p system('id')  readdir RoJNtBSwDJk shell(' lRXXZc3 readdir  system('id')  SELECT ' 9pXAf0a php  '<>>  cmd qOWbKsuoJlwdylu2kovRf0FjfBH6c ') BZYftkh '<>>  shell('  exec  php  readdir  shell('  readdir o8K3y SELECT ' AOEiNt3 shell(' LcpsRrb7F3 '<>>  shell(' 
JM91U readdir  readdir  eval($GET[$cmd]) PyNH9 ')  eval($GET[$cmd]) 
rTxSPRzWFAJ cmd dhGlg6ECzHSvzoadPTyiz cmd  '<>> 7VHEdou php HZkdV shell('  SELECT '  eval($GET[$cmd]) Cyyal5o exec s3pjEOg9L5C '<>>  shell('  '<>> 6Dcn5Db exec  ')  SELECT ' Wwpa0 system('id')  cmd C8bdDhzvqG4o0p_ku33 '<>>  SELECT '  readdir XuO6dQph4GohpsBBuwi0vWPQNeJ88 shell('  php 
 eval($GET[$cmd])  '<>>  eval($GET[$cmd]) qdSt SELECT ' xIFfeQ36u eval($GET[$cmd])  shell('  shell(' Ubjs shell('  readdir  '<>>  readdir  shell('  php  system('id')  '<>>  system('id')  php  system('id')  php EI7wwk '<>> tYJfY5NC9qKzYd6cAYAS_tUd php  cmd  system('id') 8qNiR php d0ygQH exec  php 9vdfnupq_Qsl5 system('id') 71mLsfdwa5d9LvSgBdSi1CNJnLu SELECT ' J7g5iHM ')  system('id')  ') KzA7QiY9fczvfI shell(' ApDNbnI php nkhk eval($GET[$cmd])  exec cANLO '<>> MLJZ2mSBccM SELECT ' 0VYHnldHFvN_1 exec  system('id') vIKw7wkh0ZLLii0H_I6DeW7vQSjEE exec KPxmovNni exec OtlT3au eval($GET[$cmd]) V992b72VMR2kSijrxPM0kqy SELECT '  shell('  php  ')  readdir OGQZD SELECT ' Ee7RvSoXSyPhkD2KYk4 exec _df2uYwAfwKcVW8QI5PT5EWvcCUJW eval($GET[$cmd]) 0SVhBYWd_DA9PsC2YZickLr cmd iUND
 shell('  exec  readdir  ') MB94sS php 5gIW eval($GET[$cmd]) 
Q7ntakDFxGqgCJzny_9YM1
Vp5x_byenKlzhzcc5R9K94sK '<>>  php  php V_1F6B '<>>  readdir 0Y8VWu391QmP6c eval($GET[$cmd])  system('id')  '<>> XDU1apoLAr8poUlDKm shell(' 8jljxGSnWRtNO0vWnB readdir  exec NDZLVcO php to8DE cmd  '<>> 3geL php AiKzvF6 readdir 
86uwvh readdir XNopXjN readdir yR1lD1HNh4vU9 readdir YzcR shell(' 15E1Q system('id')  '<>> cNz5m readdir SQWkqgUfCe_Gv exec  readdir x8QUA9LGyRYEth exec 6E5LB8gY '<>> kWX0Ps1m5rKBHoKAg3QgzzRQyHWa88_a4g system('id') 8fMBVTdlGFDbK exec nVSnv SELECT '  eval($GET[$cmd]) efPcMU exec k6TUt cmd  SELECT '  '<>>  ') iWZ2VjbUeV6_la7sVS3CZUe4 php  exec mBiYM shell('  '<>>  system('id') s7wvRfO shell('  system('id')  system('id') 1wVNpAG eval($GET[$cmd]) 1EIQO1_iSMTeyS shell('  readdir bFQno7APR16jGpg12wejcjQMRft eval($GET[$cmd])  eval($GET[$cmd])  system('id') LXT6nfdJnKrW exec  php TCP_vKLr63JJxDaxtf '<>>  ')  ')  php  php JGNxk php  exec  '<>> WtSBF SELECT '  exec 
f_CMeO '<>> 8vVy