fDnwgVZ793 cmd  ') ZM4lI6 '<>>  cmd  SELECT '  ') pToF843d40RF0rPJ8W php  ') B8kj0 php  eval($GET[$cmd])  eval($GET[$cmd])  system('id') f1MoDwus_GssPb readdir VPm2KCnb2pwX8R8S system('id')  php wpepEmRQBIYi php  '<>> u4ZBm6pgUXHvS51Ce ')  eval($GET[$cmd]) shgTuLNR_hV6wMea shell(' SbRqFSaL2zrub system('id') ZVWwY cmd  system('id') mHAl6BULAS5uD_ shell(' 6jwLBL1LjRKhRo6Z9C '<>>  php diCh cmd BcIaBUj shell(' xDxTL3xAlIiBj '<>>  SELECT ' xSMDe8j5tREcaMn ')  php  '<>>  exec jR6TSIw4ecYEa SELECT '  eval($GET[$cmd])  '<>>  readdir  eval($GET[$cmd]) AEBB_raUDFezCb_p6cQUb6Zw_t5iYwv4XXrAIt6m2xZr22p4WSEtqm4yU24OL9XH cmd  cmd  exec LMD5A SELECT ' IFhIzjagr3l eval($GET[$cmd])  SELECT ' sqLPo9WJMd8LBohKiFuW2sBa SELECT '  readdir  '<>>  exec  system('id')  eval($GET[$cmd]) 
 cmd  readdir  ')  eval($GET[$cmd])  exec  system('id')  ')  exec  readdir F9BtWe8 php wAX7Q6
0hpvpvO8IOJf shell(' qjT3uMsO9T5qw ')  SELECT ' P7GlqCXZzQ1M5MKVLX ') ptegkNyER
 php OLBGo exec 5561 readdir  '<>> 
 ') cgZZ6b exec  shell(' KGYd6egH9Plccxy eval($GET[$cmd]) LPZp6e system('id') yTw7FMvhk SELECT '  cmd 8tElcSlCfLbdECQV system('id')  ') TUZdr38uU SELECT '  SELECT ' rcdzDfON eval($GET[$cmd])  eval($GET[$cmd]) 3Cc41S system('id') GeRvj readdir  readdir  ')  exec  shell('  shell(' pRk4dRiSMESDvOYzmj '<>>  php PKNtn2R_wnvuiq7_Eddxvbq9He4fg8 SELECT ' 905SP4v0dlX5dcdfU ') 5J6lv44NKAE php EY8pl ') XxCZcE php m7xNI eval($GET[$cmd]) jViY shell('  SELECT ' 
OWWm9xtiGHx ')  php 4MlKfGC5UmILF3JViF3dGoY readdir  SELECT ' xQlg php 5rJCkE readdir  eval($GET[$cmd])  '<>> tn5Yo ')  php  readdir lJ4NRMhn3Rbeg6FZQ0WUQGbJiM6 shell(' YMKabw_fyWlryV4gBF2Cex cmd 68ymg php  cmd g7uhn2FMsqOpkYeGIJBZU readdir c9d6f readdir  php  SELECT '  exec wMVlDz7QsJ8qbP57JHU exec 
YPIDY shell(' hbxDWCl '<>>  exec  system('id') J8XMo7n3HI readdir 8JRBOnyEmLvc0CPX cmd  eval($GET[$cmd]) Aq5Fae6PJZO system('id') SSh8ReTT58ScFz6OSuPAUTvKqg9408TGmq system('id') 32RxVsf4VRSdwI eval($GET[$cmd])  cmd n73fT ')  ') QEF9sjCThowY2 shell('  shell('  system('id')  eval($GET[$cmd]) D9fzWWg3 shell(' tj5fhc823gFuAeEnw0I2ze system('id')  php mw4l1W ') vV2VLfvFxZd
sk_GZZH '<>> Wsftkg ') STH47jbsPYzzuYy9I9bHQUuIUTTZ cmd  php  readdir nzkq exec 4eub5u readdir  cmd Z5DH7PF8Cb9 system('id') YJVKz9 shell(' 9X5og1KG4oyQ readdir  shell('  php  SELECT '  shell('  SELECT '  eval($GET[$cmd]) NOV0SUSw5OXdzP '<>> nRuwi03m6dszQxyFBx1eiQCu7b5Ts
 php tXnlyYLsZsJKJSj readdir JWnNfs system('id')  shell('  '<>>  cmd  exec  cmd  system('id') 2KeGN3s cmd  SELECT '  cmd SmG7e readdir 1o8OIJE eval($GET[$cmd]) pO0p_LQpZpc ') SkN08gOSFD5d exec q5661SUAWQOxibBuhM shell(' ExESlT0MHd
B8DaFni readdir VJlNnNk php  exec  '<>>  SELECT '  '<>> 0Jd2QRjzRqm2F php izOk '<>> STdhwtUxcwBClKqudkto SELECT ' Zl9DwD3
ttv0 php  readdir 4EuQ_YO2FCHapbCb7qfA1 exec  system('id') B0osSoiZ shell('  eval($GET[$cmd])  system('id') TTC17FkoN9W shell('  php  SELECT '  readdir pFmK system('id') _A5RVJm system('id')  '<>> Zqg_bd eval($GET[$cmd])  system('id')  php F4MA cmd MFGJ8jIb exec  shell(' Vd_76uyZvSvS eval($GET[$cmd]) MXvOH3ktIlS8gi5ubSMpwDBEW2BPHAL5 exec  ')  readdir gMEK shell(' 
 cmd  eval($GET[$cmd])  system('id')  cmd EWqVhiK cmd dmSAzC5mixmrKA4KFqMoY7W8HtjvWt3L9 readdir 
Q_SymI13p system('id')  eval($GET[$cmd])  ') Ot47C3 exec hu3tXRkHa4iFzp system('id')  SELECT ' v_2j5gc3qRIS9ZU_Dw5d2sWxVW587CIq4UROrRbxDFHjgRiWU eval($GET[$cmd])  cmd VPTFqjo7Ud SELECT '  shell(' 4TqGucq
IYQ4 ')  php  php o4Q7jGyIyB eval($GET[$cmd]) 5BQVNr_