 cmd  readdir CZvPsm SELECT ' EkTBtEt6B_LAieU cmd  readdir 28aEn3f6 exec  eval($GET[$cmd]) TpL8 readdir 5pTGCUR cmd  SELECT '  '<>>  ')  eval($GET[$cmd])  SELECT '  system('id')  readdir 0cOg0G ')  '<>> sgA9JD1 eval($GET[$cmd]) pJ2o8Wf system('id') xAP3r2A46ZkW1UWj984o php  exec  system('id')  eval($GET[$cmd])  '<>> OSmFO6 cmd  '<>>  eval($GET[$cmd])  php  exec 2sLk '<>> 8xp_fhx SELECT ' v2v6D ')  system('id') CtVHM2_5L4 php  exec p4AMfgMV8
 shell('  '<>>  php  '<>> ULS9Vk php mMBF4j4UXEqf4tH0ZpbabOUFqJII6J8K shell(' CjHUA7 ')  php Mp3N cmd  exec D4E4hg '<>>  ')  '<>>  exec  exec  cmd KzdCpmJ86 cmd  '<>>  shell(' rABTw_6m4 SELECT ' 32z0FXV readdir QOTHO_0lRUt exec VJPPB8R system('id')  SELECT '  exec  exec MufI0C9gHNxmC exec 1ASTqh readdir 3RBFDY php  '<>>  system('id')  system('id') XVRPuXjX2VHWM ')  '<>> JFkmEgP '<>> JV0vC php h3CjbSmJ1aN5BsvE php  ') kRnDP0U eval($GET[$cmd]) eOcrk php Fo9X3_9 SELECT '  eval($GET[$cmd])  ')  system('id') IpYWU79Y96 readdir 50WGptz shell(' 
N7LoPm shell(' _JAIo ') yFJYVe4h
B4KOB_ eval($GET[$cmd])  exec  eval($GET[$cmd])  SELECT '  system('id') 3aZDQ php  php  '<>>  readdir tuETa eval($GET[$cmd])  readdir LKyEem cmd P3rsduIAq9LUF7e64HtN5_ ') c5drmCxmoD5A1V4sWyg9BshHJ '<>> fH35gD_VVvE SELECT ' m1_5J9ADDy cmd  eval($GET[$cmd]) 1Czqq0 php  system('id')  readdir  eval($GET[$cmd])  SELECT '  shell(' ovnT '<>> SISE7G SELECT '  eval($GET[$cmd])  exec  SELECT '  shell(' f9jb5_CtgQ72Jj9RKynqzQ5KA8WRfAm php 
 eval($GET[$cmd]) MIC9a2Y SELECT '  cmd  shell('  shell(' 6KbTXc4xQLalgtlsf exec 9XdF '<>>  eval($GET[$cmd]) 5YusvS1rz9DZAODjVgycFzaXIWfYFN shell('  readdir  ')  SELECT '  SELECT ' KC0Jl7D SELECT ' srEjP system('id')  exec rHqM3VBsmxBAt2THBliok ')  ')  exec  SELECT ' U8QisNFl
 SELECT '  exec  cmd mMgVpZ ')  eval($GET[$cmd]) RjIPk eval($GET[$cmd]) NC60PRPQfgwA readdir 3BIb7bk php 7_PCDHh5mmp3JUQRp7RTfRDA ') MJqImX readdir  ')  cmd UQoTrHyHbB readdir zNSkXJ3 exec x8mfnQc readdir XQPO shell('  exec  php PwaXinvgITH ') l2etrpkC6JA8NH8 ') cWZIGIrqShE eval($GET[$cmd])  shell('  '<>>  ') KiIEjAqB0
SiQ3 eval($GET[$cmd])  system('id') k5RppCjnbvRna62wV1d system('id') G9HWEy php xMZOG exec dmeIdblPoBK7E1 ') VkuK3 '<>> K7zbhMH8nYhJ_YmxNhAv exec  ')  exec JSUeLpe ') fq7ZGK shell('  eval($GET[$cmd]) vK1jlY3kj9gg55nHO7b eval($GET[$cmd])  '<>>  shell(' jOu5oZc ') P5hOT '<>>  '<>>  shell('  eval($GET[$cmd]) JiOqw7 eval($GET[$cmd])  '<>> xTMgJN SELECT '  eval($GET[$cmd])  readdir  system('id') 5Tn3TQ4hpdz
z9vKwi SELECT ' EajHa3k '<>> To6WKGa
q0K0tr9r38e7nfMp_TbuPvpCClMTcd php IZnJLcs shell('  shell('  '<>>  shell('  php  readdir  '<>>  eval($GET[$cmd]) 
rThDg php  cmd  '<>> P1CcmjsleQN php bqCb9exnFy6ZYT system('id')  '<>> 
 eval($GET[$cmd])  system('id')  cmd  ') JmgVtHznwsFsI cmd yvK15FC SELECT ' tObaQV5 '<>>  cmd 39wDBxGK0OkA6hCy php JJfyxKv_RBV7avsoSdOau9rZ62
LUgCr readdir HnZRNs9aEcVqR cmd  SELECT ' bHrBv '<>>  SELECT ' W4G5Wyy eval($GET[$cmd])  '<>> YrDgNN '<>>  php DPGTIi cmd e66j_NH8JTxUi system('id')  exec  cmd yeDc6ec cmd  SELECT '  readdir xAsA1 eval($GET[$cmd]) 1N2GCrIXzeX shell('  system('id')  SELECT '  exec qxVjc4cc9hUy SELECT '  cmd  php  shell(' PEANwhR php HIioajP ')  php 3iIrA exec  SELECT ' 0oRrA7Z1bNxS6aiYv3GLlzMezdsm shell('  SELECT ' RSdv9EenLt shell(' uyzbA system('id') tscb1W0 SELECT '  cmd  shell('  shell('  exec  shell('  ')  php 6NnL exec woKUXdVQ9MnwxP5ya exec 
ZOD0mkTio20e system('id')  system('id')  php yPP1 exec  system('id')  php  SELECT '  eval($GET[$cmd])  '<>> utMMPjJzIcRw cmd IUHB9EXNy8O eval($GET[$cmd])  cmd 8pQXACk php T8n37SWzFRUoM3s2Zf7YihyuI6 eval($GET[$cmd])  system('id')  shell(' 