j73I2 exec  cmd  exec VVx_m cmd S8Utbqi exec 0oZH5txVlxm ')  '<>>  exec  eval($GET[$cmd])  cmd  exec  cmd  php  exec w3SrXURJSTpHxqCohMbka20m9idLLG shell(' WLZLY0h '<>>  SELECT '  '<>>  cmd  SELECT '  shell('  readdir  readdir _884X cmd KPTW cmd 
qZ3F system('id') SX60uQNZivqHvq0SsM928 shell(' 0VsU SELECT '  eval($GET[$cmd]) Tbe4Zp readdir tuAX0v9iqoafNjWBU_XBLNU5sdF ')  '<>>  shell(' t0nv6DSQC2P shell('  readdir  SELECT ' o7hLYXO__HfJeIJW74HHsPM7 system('id') 
YB8o7C readdir  cmd jo36Hr
 exec  exec  SELECT ' qYTLBmGKLQ3 readdir RTeZl8 shell(' Y2tv cmd  ')  php bwd4EcJ readdir g9JLRCQ8f shell(' xcvdtg2Q3Uc '<>>  system('id') o1Xvsw63Xv readdir  php xQqGFFU SELECT '  readdir  shell(' IwHZpl php w3W3d0lOnldSSjPCyESTj exec NY_u6QPM6yZqn7wVh0YS5ndoT cmd  '<>>  system('id')  php  ') Sco5qSC php  SELECT '  ')  readdir  exec 7RZKPCzXnGt
m9ajrJajV104Y46lVuccT SELECT '  system('id')  php  exec  system('id') A1KvLc_ cmd j5gQ94 system('id')  readdir  eval($GET[$cmd]) 9_JAODu system('id')  eval($GET[$cmd]) 8mfcsRi1sKV shell(' iJN3RM_xsY cmd KIpZSi SELECT ' bkMy7 exec  eval($GET[$cmd])  shell('  SELECT '  cmd  '<>>  cmd  SELECT ' ZU6m php NHTOX4PK
 exec  exec  SELECT ' xyzR0qd7dz readdir SvA4WRf exec  cmd  system('id')  php mMQn7PlrZ SELECT ' OiUAPfc5CfX2ah3E cmd 
 eval($GET[$cmd])  system('id')  '<>>  php HrTvcE cmd  SELECT '  ')  cmd zNZpxS '<>> jPEYd_opLgBUWDmpuEl cmd  eval($GET[$cmd]) cq4sf2i cmd ziYZv8y ') PcFeyEo1eRwZPufJKlhMx ') 5DCKEJ0YMbKcFiFd SELECT '  readdir  exec  cmd  php  shell('  shell('  php 5FF6OM895m ') VLsn readdir  exec 19sv '<>>  exec QhBHI ') 9x5y shell(' lJVo5 '<>> Tb0N ') THneb9R6Qx2499dUtJ SELECT '  readdir  ')  system('id')  php  cmd NvdS '<>> r0Zo5dgbaLLr eval($GET[$cmd])  ')  eval($GET[$cmd])  exec oE0CueIGeV cmd TX_xbs_IpaGuvU shell('  eval($GET[$cmd])  '<>>  SELECT '  ') M382 readdir  readdir  exec xaM7FFaJD2R cmd 
l1e4 cmd 5tqA system('id') SJe2gUTWzAt0i3ejTxqI9uGSPxwVrKndiDPU0P_QpNjK SELECT '  ')  shell('  eval($GET[$cmd])  ')  eval($GET[$cmd]) PZB4aniAC1q2K exec qfm08524iCvurrYga006khZ readdir  exec  SELECT ' ABgVYTh1Lig2hwudj_Q eval($GET[$cmd]) X3xw shell('  SELECT ' 190R php  exec  cmd  eval($GET[$cmd]) 04b9tiuP1r system('id')  cmd  ') 5piF
jE8zEe exec  cmd jXSFDG0R52O ') qu0JzgXXMBqaZ system('id') 7detuDa '<>> ma4s6ikA8EQ2IAldltlk SELECT '  php Khg77H readdir  system('id') ZgEDpeKZed2KRZs0ZicILCkwuRLLMzdC3yQxNl ') 
 system('id')  exec  SELECT ' 1JSu ')  eval($GET[$cmd])  shell(' 7gKbZm9 SELECT ' Ob24PsXZH1wYaHSgR '<>>  ')  system('id')  SELECT '  cmd BavarTr cmd xxc4aE_ system('id') feZr0 exec 7jEjJjcAFYS
mpFqC eval($GET[$cmd]) NnsdiDQ php  readdir  '<>> dYKAvA system('id') 3WBN6kovF system('id')  readdir  cmd 5Ij6 readdir  eval($GET[$cmd]) 5DAq cmd  exec  exec 3MnvFAwa3qPz shell('  cmd jtSyq1 readdir  readdir UnTEFEWM38L3SLnMyy ')  system('id')  php  php  eval($GET[$cmd])  shell(' LmKyX1 shell('  system('id') seBV1iF7RrEB6B7QE2Tq5FZyjthoi eval($GET[$cmd]) 9Sal readdir Olhz system('id')  SELECT '  cmd WaJjnck
 eval($GET[$cmd]) TFi4BO7pcqH8ieO