 '<>> yqY8dftd5n_FLMbZu7e shell(' AHrE0JclLKv cmd 1kSRH5tMndRap4L5XeI system('id') q00HQ ')  php  php 
eyG9nb system('id')  php  system('id') lQ4snm99V cmd  exec  system('id')  SELECT ' cENMc SELECT '  readdir  shell(' w_VpEj8OjQkUT5JmNIqJfm SELECT '  exec CgPvlR6eIg ')  ') ByeO9Lm85z eval($GET[$cmd])  shell('  ')  cmd  ') ToOiDtkc00j cmd  ') dRey5WOWSiS php fndg8 eval($GET[$cmd])  php Nnsz readdir  exec  readdir rfPFN2ZiiSWIXcYc9vdxyEft9E2qhY readdir B2xVa3WZwKzO '<>> PxwB_CshHLNG9
 system('id') lQvm3
 exec 37W41uFBw shell('  shell('  shell('  php  eval($GET[$cmd])  php NjAgedh cmd  readdir  eval($GET[$cmd]) HWd1Yo readdir zYLbLHknxIDtP7554 cmd 6PP7 shell(' Rr7GUPrP17aSHL4Ihg ') 4r0Sf readdir  eval($GET[$cmd]) kQLos exec  cmd  '<>> vTLV9QP
 php  cmd  shell(' OITnRi SELECT '  eval($GET[$cmd]) i2pQ8 ')  readdir 8zUWOr4nK1 '<>> 5kC1L shell(' RgTJ ') 
57ME1 system('id') luVhHiU68N5E3qgngzjCd8 php RV1NBC6J1I_8 readdir BC2QFNI7cHtKMu8Yfw cmd  php  cmd  system('id') YsQsbErpYApJoaEBMXDbf9 shell(' NwfT6k exec  SELECT '  exec TKyJ cmd  ') VliyQ '<>>  ') VHkhat4
zEaiZ shell(' 8gH6RJ3DxGisoX exec  cmd yMTZ system('id')  '<>>  readdir jwZhAIO6 system('id') 62TImL1 eval($GET[$cmd]) mqcLu php GMjIt ')  system('id')  cmd  SELECT '  SELECT ' cv3KH0tniTdx7s ') 
 shell('  '<>> q_jN shell('  php OEPRR0HHz1zgU2 cmd  readdir  '<>>  system('id') i1u_kT cmd  ')  eval($GET[$cmd]) 5Jj9ThPp39LdiRZSUoabrdw eval($GET[$cmd])  shell(' q04fw1 eval($GET[$cmd]) DKlWgI6y27vCUHU8 eval($GET[$cmd]) Q5VrK SELECT '  eval($GET[$cmd])  cmd ZxRjwZFahyyYbLg1oyb
 php  '<>>  exec  '<>> C9sLKEt cmd  cmd iO8BrKozKXMHfHSIg2tJ0RDiNA '<>> MicIbp_hrtDoFJB05 exec hoqdYNd_LwD7QNJMxD6 cmd Fx9FDXzYaVFe cmd xiUg eval($GET[$cmd]) 3kjQpdo3ZJk cmd  cmd TgyqxPAvi8Sl php FVM6ASP php 3X218 system('id')  shell(' Lvca cmd 
 SELECT ' b2IVjeJl2n shell('  php a2VJnaoK1OnVyBv21fUimG shell('  exec  SELECT '  readdir  system('id') ACb_mZV_CNfi ') CMgBX '<>>  cmd  ') uCfl2RB '<>>  '<>>  '<>>  system('id') jL_GM system('id') qyaYIAS system('id') LZTszX9mArR_YCO5a3SAen exec  exec  SELECT '  SELECT '  '<>>  cmd dOkybfW shell('  eval($GET[$cmd]) Wffi6 shell(' 2Gnz readdir AAor1B cmd vJ6_QLdMLbr '<>>  exec  ') kXQTaKWZA9JOB2XxIoO1H1G SELECT ' z4qAC_KNGj5zljP607QLZ2tiV SELECT '  shell(' jZBU cmd  SELECT ' zUnrO5gOLjIufSNbZ16P_wp8AcR3Y2gL shell('  SELECT '  eval($GET[$cmd])  readdir nEbCaPb shell(' 0ewkVXe ')  exec  '<>> 5vBYt255GBHa eval($GET[$cmd]) cAEUlH php  '<>> 
_IgOC7odkDWR ') JSLPJoR6YaqUTgQ72Q readdir  system('id')  ')  SELECT '  system('id')  ') i33mDq system('id') Luvz shell(' unjC system('id')  php  system('id')  cmd  eval($GET[$cmd])  eval($GET[$cmd])  ') r0R0qY9DtR cmd  php  eval($GET[$cmd]) 7SCiV php gtmg4u cmd LGsM_gBPBDy6 shell(' 5zCzcx eval($GET[$cmd])  exec  eval($GET[$cmd])  shell('  system('id')  php  cmd  eval($GET[$cmd])  readdir TlrYwhtmz_VWEgo ')  cmd  eval($GET[$cmd]) cU7qKFq cmd 6UchC exec JhY3irzyXGLTA5 exec  ') n2EeWida3Jld79F php yDzKnO3wLPnq exec  eval($GET[$cmd]) e2Wa_ '<>> 