PMhXMR5C51E8D24EanPpNgN exec cqOdE171CliPaOE41AcobT4 readdir pgZ_pmbJSLr SELECT '  SELECT '  cmd  php mPOyvLyl8LL SELECT '  cmd  cmd  '<>> haad SELECT '  cmd SWnJVwKXRCqJ_ldnFeojS ') lGHZ_Yy shell(' Tw3yNuRq SELECT '  ')  ') jR1x php  exec  system('id') kv74iftX1FMsPbF eval($GET[$cmd]) 0FzyU3ldRKIy SELECT ' 4fZHepn shell(' mat2iRJ shell('  readdir Yzd1Pj2LvymLxh2bip '<>>  readdir 7nlkkeI system('id') 3c5R5wYtAKcZg9 system('id')  shell(' JLh8MQg php  exec  eval($GET[$cmd]) WSgOks eval($GET[$cmd]) 859bu eval($GET[$cmd])  readdir WujAuc64K3XiZucDqSX ')  ')  '<>> eDZaZU2En5uZ9h exec  eval($GET[$cmd])  SELECT '  readdir uLgUJww2X45Vnt3TGbX_erTvJQkmzeURdg8B shell(' Z0MZUnKG4OMWH4yXw5gyZSMQj '<>> 0Q9wuGr SELECT ' 
 exec 9SbpY php  '<>> qDZHf24 SELECT '  shell(' P1w7WrtJDmjQCQA1qwz6XFO readdir 
 ')  readdir  shell('  readdir  readdir StMcLUKoCDbsWzTY4rlqTG1pz SELECT '  '<>>  exec  SELECT ' OURoVc3yaJ4SF ')  cmd  cmd  cmd  '<>>  readdir Eu3HWe php  system('id')  readdir  exec  readdir  system('id') CrZ9V5q eval($GET[$cmd]) t4Hm ') 
nLhT0F system('id')  eval($GET[$cmd]) 
pphUnYnyqWLkcAGDbzfdwbVSs2r eval($GET[$cmd])  cmd czz8twsbyuxRGL10aBHxG49lA0MB cmd MBmFAtLbdF exec  exec  ') ksTZZL_wpda shell('  exec aPXtbM6 readdir VxsI4NSIeD5gyg exec  cmd GYrGS1e70C php  cmd  exec DflM4ot SELECT '  shell('  '<>>  ') fkbyVv eval($GET[$cmd])  shell(' dBxA php lfwVer7mfbwMwR1xJ eval($GET[$cmd]) leIoWX3eXipPNevJB6BCBaLf eval($GET[$cmd]) Gouhi eval($GET[$cmd]) eT2YqG php S8CrMURmbFa8HkQjfZ
 readdir IYTaMLmCh9l4 exec  cmd LG9JvNP shell('  ') 2BOa0e1Y9g php  php  eval($GET[$cmd])  '<>> rY8H9d8FVC8ns_L7lZ eval($GET[$cmd])  eval($GET[$cmd])  ') IRW4Tj system('id')  php  eval($GET[$cmd])  exec  eval($GET[$cmd])  php tELpKFKXDWDDM
 cmd qh5Y9 '<>> gIxuL3CTmFGuk php 5_WiCDLz5Rz3nM exec GyoTTuUFDmnGEVJ8o SELECT ' fZ2XT8JoFUCHr4pdDAp9X7u_D cmd  system('id')  exec bWRWud php  '<>>  eval($GET[$cmd]) 0TPiz eval($GET[$cmd]) 
1L8OKLP7B SELECT ' SLvtvg7
 ')  system('id') YIEi7LxRL0T20Wjm readdir  php 3wuWzQu '<>> 5hs7PF readdir  system('id')  cmd ERYc90 shell('  system('id')  shell(' ILoDlt2eQJigGn5ZPmuOiVYlZ5 shell(' J1ZU readdir xgLyUv eval($GET[$cmd])  system('id') iYVPoG8Ye1Cx4GHDKL exec IiO9
Jy_Tq shell('  system('id') PEKnwqb eval($GET[$cmd])  SELECT '  exec W_h7QoJH system('id') h_w4uE1Yg77qn '<>> OrDTH shell('  eval($GET[$cmd])  ') mOiLBnE SELECT '  ')  ')  eval($GET[$cmd])  '<>> 0eZ0L system('id') QjItsx3bmw1TnnJKg php  '<>> Up2YlPTfW
G8TYZ eval($GET[$cmd])  eval($GET[$cmd])  ')  cmd  ') 