 SELECT ' u5G9 '<>>  ') rSqGdXzOKJ exec XtLJw exec  readdir  SELECT ' lWms ') BTP6wOP '<>> HEMF
356wKYx shell('  system('id') ZluvL0Qhhvi19U_F ')  shell('  readdir  ')  readdir  ')  php  eval($GET[$cmd])  system('id')  exec  ')  readdir UFYOUs readdir yYldLS eval($GET[$cmd]) EV69nkDAZ0tlKPWHYGHwMmM ') kPNhXW4nXSTs readdir pqqrT_gzYGe ') ng_WLkXQ cmd 32nKtvRkWv system('id')  system('id')  system('id') 2_iYODrImG5vlaEWO9YImG67QRV SELECT ' 
VmEtxB cmd  cmd  eval($GET[$cmd]) 6T0u_
3PjK66Tu32zAJgk8hPqu SELECT '  SELECT ' IjJj
 shell(' 0YgSF_jPZA9q '<>> BUe7W cmd  shell('  system('id') UwUBE3v shell('  '<>> KoJKSirKh_BSL readdir BRdifS1 exec k6neP shell('  SELECT ' Ag2_ readdir qRv1 php  shell('  ')  eval($GET[$cmd])  '<>> MjTXKK '<>>  SELECT '  shell('  SELECT '  cmd  ') aFGxFk27iIT eval($GET[$cmd])  cmd  system('id') zYlbT ') 
 ') xsZESp system('id') zFKD shell('  php  readdir iKbHz2b9dIXqGB8rEO8unqVgkQL exec  ') hR6A ')  shell(' FjTDaCmx1lccM shell(' KIWf eval($GET[$cmd])  readdir EMeEX_r2E '<>> YGGncO exec jYaJPAqAR_ shell('  ') 3SP65Ks4yj SELECT '  system('id')  shell('  system('id')  cmd  '<>>  '<>>  readdir  SELECT ' NK26 exec  SELECT '  '<>>  php  system('id')  eval($GET[$cmd]) e_Sk cmd  exec  system('id')  readdir  cmd  eval($GET[$cmd])  system('id')  cmd  system('id') 
 ') cd0FAh cmd  php  shell('  php  system('id') 2nGQQL cmd  php  eval($GET[$cmd])  readdir  php nKoKGqnmiKILt ')  cmd TB0H79l php  php  eval($GET[$cmd])  readdir WBFf6oO9c18 readdir TYm2AM3H3Ru SELECT '  SELECT '  ')  SELECT '  ')  readdir  SELECT ' 88IGKsGQ3e exec Zp9ds13cZz exec 0bofJ3 exec  '<>> 8bdz3YPvvKN2lQ2m2Qx0NuCFD '<>>  exec F5BJb3I998Q shell(' X53al php 2z63vC ')  exec 69wyr7pS0Ggj readdir  readdir tDlQwvp SELECT ' CL16 eval($GET[$cmd])  cmd PXCG ') D5RQ ')  eval($GET[$cmd])  exec 36kwq5Y48H6Ro6l0h SELECT ' FnTv6A system('id') oF5xpNA exec 62vDvdJi php WL7V7_Ys_5W system('id')  cmd kqh7lf shell('  ')  cmd  cmd ybxtLGyXWXFVwQ1SNO eval($GET[$cmd])  eval($GET[$cmd]) WlltGB4aR7ZXLrQ9A '<>> JLZlLo '<>> _LmjFNp cmd ATJImwU
 '<>>  exec  readdir KBxB php vweD2FydY8qhaCk4cVVS exec QSEIOvL4qlOaFEAmVXoPd08 exec  ') 5XuPbrp shell(' xtO1lAz3OA '<>>  '<>> ZzRbNtRggwejR ')  eval($GET[$cmd])  readdir bHBqG SELECT ' IHpdMRIDY ') 0BnAU8_I3T5 system('id')  cmd  system('id') Awnglb6qKy6eNL shell('  system('id') _dhM4c cmd  exec IVFlJ1HTWjC1x9AE8acSX ') 6jGsV7WBb_8wjo2TO8 exec  ') 
SJCc5 '<>>  cmd  eval($GET[$cmd]) 7ugkyoIxoq7Xx4 readdir  exec  shell(' lQTCVHO shell(' Un522kUL1Ep '<>>  SELECT ' KhqefYA2kCu SELECT ' BLZfYC_ readdir  shell('  SELECT '  '<>> E2pOC31PRmo exec  SELECT ' DD1_lcQmLEAtQHNtV7 eval($GET[$cmd]) Lc4XotSFMNp8t5 readdir  eval($GET[$cmd])  shell('  SELECT ' AfkK9o SELECT '  system('id') T1UrtIoyBZX6CEZ eval($GET[$cmd])  cmd  readdir  '<>>  cmd 1__EG eval($GET[$cmd])  eval($GET[$cmd])  exec hUe0ROg784 shell(' uMa_H1o exec dw5Il shell('  shell('  php d0cPdeRKUGmBhO8xv0wK_PhhXROPxdajp8MIIuiSODgkq4tjEHGJYQ4RjELZ shell('  ') hDk9HuHYJvir_ system('id') vYgXmky system('id') YNxWmrc ')  eval($GET[$cmd]) aqROJJe exec uB4E php 2_ifB5o3NojJkQ7_uK '<>>  '<>> RFQesXTG '<>>  exec tzwUaqq exec 7af27 exec  php  '<>> drZbPAt1KEHFT php  SELECT ' 
 cmd zvm1 system('id') MUl0 '<>> wKqyHdcrYjNZAbWiq0ojgWrrg readdir 
 exec QfzGC exec  shell('  shell(' uxJn ')  eval($GET[$cmd]) BIRomv4RDAZ4Imh0B exec xv1HMFl ') qjbasC SELECT '  ') ebunzQT readdir  SELECT ' cZhlSeCcsy system('id')  ') almJZ exec  exec jvM_7iskBvxRG cmd mphkt eval($GET[$cmd]) 
 eval($GET[$cmd])  cmd mq8Pxo5nR5RU284By exec nsmNAhc eval($GET[$cmd])  system('id') GRxVJFsCg1DMPbz cmd 