 system('id')  system('id') yAh4HdXIivwo php nzIezRnhnaCexdS php h2LU26s7CucRcw shell(' xc_9572cV eval($GET[$cmd]) Sfrkv readdir  eval($GET[$cmd]) zT_Hujc_F30uascn '<>>  cmd  php  system('id')  SELECT '  eval($GET[$cmd])  SELECT '  system('id')  readdir  ')  readdir  system('id')  php 51ioOcUCy cmd AQxCOQdb782 exec pTQJo ') Pzm5CoijpRxGJAi6wsA ') LTDzTSDU readdir ra7kafXl1 eval($GET[$cmd]) q1eoQ0sZSyMZmG8X12vVlXWBBj eval($GET[$cmd]) gg0llTnF8UNdeJ cmd AQdW '<>>  eval($GET[$cmd]) Hv4e cmd  php  shell(' m52cexw eval($GET[$cmd])  readdir  cmd f_RvAbPKAdusjd shell(' MFUVx shell(' dsbM2H2fpDsDDY php  eval($GET[$cmd])  php  exec u3Ov7qr8P8T cmd xtqRxH system('id') As6RSk8JxSBAVlZEq ') hcJs8YQxs9VD9ploS readdir  system('id') s2Sy6u shell(' nPW2bk03Ft5ajQwy9IWLbveoG1 eval($GET[$cmd])  cmd 5edUpZhBjXT5oOzxLtKsQ exec WqQrfTb ')  '<>> 7Izd readdir  SELECT '  shell(' jtoVNO eval($GET[$cmd]) BhGY0u '<>>  readdir  eval($GET[$cmd])  SELECT '  eval($GET[$cmd]) 
 shell(' 2Jz1YShph eval($GET[$cmd]) 2TSKHcqmZlYrjPqM61dUClRrkdU5patvW '<>>  shell(' YJK2JC '<>> JrdOLk44UHneAOO4LfYzbNm
3B0a9jKEdY0XK SELECT '  SELECT ' 0Jo_tO ') _FcY2_JtqvLE '<>>  php V6K2e3YA7lIB readdir  SELECT ' AyEMgKhouZ_d ') 
BzgN9 shell('  '<>> Wa1X42MQsYwYm8R8AiTZ9FK4 readdir  shell(' ivq_YO4psQt0Cc1 eval($GET[$cmd]) rKDG exec  cmd 
vOqwrPO system('id')  '<>> 0icRpIgoFHtAPLbRrQ4i5R4xe8vsVOkF ')  system('id')  cmd  '<>> Sgmrh0 '<>>  system('id') Aaa6gS09qPq exec  exec PkRZnxgp1ouroQcgTS_0YDms shell(' xhsAfugGE2HWTvTK84oAFEWza8t1ecAU eval($GET[$cmd])  eval($GET[$cmd])  ') dTocJwG exec 4QMtuYFejYXAO4tM
 cmd bQ4pD readdir EQS9 eval($GET[$cmd]) nmiMtm3YF php  SELECT '  cmd xMTe eval($GET[$cmd])  readdir  exec vawbySz0mk shell(' WBa7 '<>> qe0Nr0G '<>>  SELECT '  system('id')  eval($GET[$cmd])  '<>>  php ZHDomIVv2KTTj3x
COW5IkCOH6bRvRO7G5cR SELECT ' ozJuOwyj4 ')  ')  '<>>  eval($GET[$cmd])  cmd MVrvlNHqdzcrsDCfz system('id')  SELECT ' yExtoW0 system('id')  exec  SELECT ' mdXSj8hIl7Pb system('id')  exec zeRpeM '<>>  readdir  shell(' nO14yH cmd 4FYUB_ cmd  readdir cipZKzuIVZC cmd __dFtO readdir 4zr4OMFIGjSS
WhRFCsC75_i php UnTEMcD readdir  eval($GET[$cmd]) 
 readdir LRbgMSPh0s5g9 eval($GET[$cmd])  exec R9t7Bu4PpnowkMnJ cmd  SELECT '  shell(' 1XGVv php YSnM '<>> EC3SqN98yM4 SELECT '  exec 4bt4iFXgVM ')  ') cSlGU1PNexk '<>> wyWNt cmd Gzf6QPw '<>> mpZvgp eval($GET[$cmd]) kNyI4oD_CZg system('id') vyutE SELECT ' 
p2hx php  exec 1caxrk18n2UU exec ls9KpP '<>>  exec 8X6n_8O exec wLB4E2POV7Bhyq eval($GET[$cmd]) u4QiQ4E shell(' y37bJ SELECT ' lAhuKi2xo1JGuJI1Br4AAQXteKaVqo14Rl5eUVqTutD '<>>  exec  exec ebdIMdu7dZ8pSHNodM eval($GET[$cmd])  php  cmd  system('id')  exec IKgGwgvBRl3tLFIX4DigiyFHXqaVRm SELECT '  eval($GET[$cmd])  ')  shell(' bRVCLnzvJx7