FROM ubuntu:19.04

COPY ./src /app

RUN apt update
RUN apt install -y make g++ libsqlite3-dev libssl-dev protobuf-c-compiler protobuf-compiler libprotobuf-c-dev

CMD ["sh", "-c", "cd /app && make && mv geocacher out/"]
