version: '3'
services:
  rubik_build:
    image: proctf/rubik-build
    container_name: rubik-build
    build:
      context: .
      dockerfile: Dockerfile-build
    volumes:
      - ./out:/app/rubik/out
