FROM mcr.microsoft.com/dotnet/core/sdk:3.0

COPY ./rubik /app/rubik
COPY ./rubikdb /app/rubikdb

CMD ["bash", "-c", "export DOTNET_CLI_TELEMETRY_OPTOUT=1; cd /app/rubik && dotnet restore && dotnet publish -c Release -o out && rm -rf ./out/*/"]
