version: '2'
services:

  drone_racing:
    build: "backend"
    ports:
      - "0.0.0.0:8080:8080"
#    volumes:
#      - ./data/database.h2.mv.db:/home/drone_racing/database.h2.mv.db
#      - ./data/database.h2.trace.db:/home/drone_racing/database.h2.trace.db
#      - ./data/session.key:/home/drone_racing/session.key
