version: '2'
services:
  database:
    image: oscarfonts/h2
    hostname: 'database'
    volumes:
      - h2-data:/opt/h2-data
    environment:
      - H2_OPTIONS=-ifNotExists
    ports:
      - "1521:1521"
    restart: unless-stopped 
  web:
    build: "backend"
    ports:
      - "0.0.0.0:80:80"
    environment:
      - PORT=80
      - CONNECTION_STRING=jdbc:h2:tcp://database:1521/drone_racing
    volumes:
      - programs:/home/drone_racing/programs
    restart: unless-stopped
    depends_on:
      - database
    mem_limit: 1000m
volumes:
  h2-data:
  programs:
