version: '2.0'
services:
  nginx:
    image: nginx:1.17
    ports:
      - "0.0.0.0:8000:8000"
      - "0.0.0.0:8001:8001"
    volumes:
      - ./site:/usr/share/nginx/html/
      - ./default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    mem_limit: 2000m
