version: '3'
services:
  front_proxy:
    build: ./front
    ports:
     - "80:8000"
    volumes:
      - ./data:/app/storage
    restart: unless-stopped

  uploader:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/storage
    restart: unless-stopped