version: '3'
services:
  front_proxy:
    build: ./front
    ports:
     - "8000:8000"

  uploader:
    build: ./uploader
    ports:
      - "5000:80"

  storage:
    build: ./storage
    ports:
      - "9000:9000"

  mongodb:
    image: "mongo:latest"
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    restart: always
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles --logpath=/dev/null # --quiet