version: '2.0'
services:
  front_proxy:
    build: ./front
    ports:
     - "8081:8000"
    volumes:
      - ./data:/app/storage
    restart: unless-stopped
    mem_limit: 2000m

  uploader:
    build: ./uploader
    volumes:
      - ./data:/app/storage
    restart: unless-stopped
    mem_limit: 2000m