version: "3"
services:
  db:
    image: postgres:12.0
    environment:
      POSTGRES_USER: tracker
      POSTGRES_PASSWORD: zHSKoKea+FXCxY+an5Q=
      POSTGRES_DB: tracker
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    network_mode: "host"

  app:
    build: .
    depends_on:
      - "db"
    network_mode: "host"

